### ISSUE TITLE
[Task]: Allow users to delete profiles with balance

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2035]
### Task description

After improving the deletion of profiles in 1.3.0 to fully remove the data from the backend, it is no longer possible to delete profiles with balance on them. This is because to delete a profile we first delete each account, and the wallet api does not allow us to delete an account with balance. We should add an api endpoint to the backend to delete a profile no matter what.

### Requirements

- [ ] Add functionality to backend for deleting a profile not dependent on balance
- [ ] Adjust front end to call this new function

### Acceptance criteria

We are able to delete a profile with or without balance.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
