### ISSUE TITLE
[Task]: Disable pre-commit checks on unstaged files

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2036]
### Task description

When working on the code sometimes you would like to make small distinct commits, but have many unstaged changes in files. Currently the pre commit hooks will check all files that have changed whether they are staged or not. This slows down development, therefore I propose the checks are only done on staged files.

We also don't have a svelte prettier plugin. This was added in a separate PR.
### Requirements

- [x] Disable pre-commit checks on unstaged files
- [x] Add and run prettier plugin

### Acceptance criteria

Checks happen only on staged files.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
There has to be a separate PR where the linter is automatically called if prettier style is not abided by.

**Comment by Tuditi** [comment]
I investigated the following options:

1) [`pretty-quick`](https://www.npmjs.com/package/pretty-quick): Formats staged files with prettier, downside is that there is no support for eslint
2) [`git-staged-format`](https://github.com/hallettj/git-format-staged): Supports both eslint & prettier, but requires python to work
3) [`lint-staged`](https://www.npmjs.com/package/lint-staged): Most popular, supports both eslint & prettier, easy to set-up
4) Manually writing a pre-commit-hook: Downside: takes more time, might be complicated, Upside: no external dependencies

I propose trying out lint-staged and see how that works out before spending more time and effort on developing an own solution.

**Comment by Tuditi** [comment]
This only impacts the local process of the developer. The CI still checks the whole codebase and sends an e-mail if something goes wrong.
