### ISSUE TITLE
[Task]: Lock firefly when user locks OS

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2037]
### Task description

While we do have the auto timeout feature, it would be good to additionally always lock the firefly application when the computers power mode is changed.

### Requirements

- [ ] Logout profile when powermode changes from one classes as active to an unactive one: i.e. sleep, lock, hibernation.

### Acceptance criteria

App locks when power mode changes, app locks on existing timeout too.
Works on Mac and Windows (would be nice in Linux too if possible)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
