### ISSUE TITLE
[Task]: Add support for Firefly web

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2040]
### Task description
Since the beginning of the Firefly extension's development, the desktop wallet actor system has seen a number of changes, breaking communication with the extension. This task aims to re-integrate the extension, including some suggestions from auditors regarding overall security, and re-organize repositories / dependencies.

### Requirements
- [ ] #2187
- [ ] #2188
- [ ] Ensure correct build environments for production and dev instances (between Firefly desktop and web)
- [ ] Identify all potential security vulnerabilities (for @Evanfeenstra)
    - `chacha20-poly1305-aead` pulled from user GH repository, used in `extension/web/wasm`
- [ ] Adjust or make additional CI workflows as needed

### Acceptance criteria
__Must__ be able to be built and demo-ed.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
Closing this issue as a result of re-organizing tasks for the "Initial Firefly web release" milestone.
