### ISSUE TITLE
[Task]: Allow user to dismiss selection view to dismiss it

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2042]
### Task description

This task addresses the enhancement requested in https://github.com/iotaledger/firefly/discussions/1784

### Requirements

- [x] Add functionality to dismiss selection view when user clicks outside

### Acceptance criteria

All selection components should close when the user clicks outside.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@jeeanribeiro has an open PR for this #2034

**Comment by nicole-obrien** [comment]
@begonaalvarezd I know, just moving over things from clickup 😄
