### ISSUE TITLE
[Task]: Design a single account view of the wallet and a new account switcher

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2043]
### Task description

We would like to simplify the user experience as well as simplifying the development complexity for existing and new features. To do this we would like the user to only have a view of a single account at any time. This means we will need a new top level account switcher once the user has logged in. And to adapt the current wallet view so that it is for a single account. i.e. the balance overview will only be for that account.

### Requirements

- [ ] Design account switcher
- [ ] Design adapt current profile and account view so that we only have 1 level
- [ ] Design account identifier component

### Acceptance criteria

We have designs of the above three requirements, so that a developer is able to pick up the implementation of these features.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
