### ISSUE TITLE
[Task]: Keep track of the last logged in profile

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2050]
### Task description

This task addresses the enhancement requested in https://github.com/iotaledger/firefly/discussions/1562

### Requirements

- [x] Track the last logged in profile
- [x] Default login page to the last logged in profile

### Acceptance criteria

When loading the application the previously logged in profile is displayed ready to input the pin.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
