### ISSUE TITLE
[Task]: Make dropdown selection component searchable

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2051]
### Task description

To make selecting options in dropdowns more accessible and easier especially in long list, we should make the drop downs searchable when the user enters characters using their keyboard.

This addresses the enhancement requested in https://github.com/iotaledger/firefly/discussions/1541

### Requirements

- [x] Make dropdown selection component searchable

### Acceptance criteria

Drop down component is searchable using key presses.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
