### ISSUE TITLE
[Task]: Improve account UI customisation

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2052]
### Task description

We should allow the user to select their own colours for each account, or choose from a group. They should also be able to add a pattern. This will allow users to customise each account and easily recognise which account they are using etc.

### Requirements

- [x] Allow users select colour on account creation
- [x] Allow users to enter custom hex code for colour
- [x] Allow users select pattern on account creation
- [x] Allow users to change colour or pattern for existing accounts

### Acceptance criteria

All of the above requirements have been implemented.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
