### ISSUE TITLE
[Task]: Integrate Sentry bug reporting

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2054]
### Task description
The Firefly architecture contains many segments, making handling errors / crashes appropriately is difficult while debugging them can be even harder. This task aims to add Sentry, which is a platform specifically for monitoring and reporting software performance, diagnostics, crashes, etc.

### Requirements
- [x] Add necessary dependencies for Sentry
- [x] Add Sentry reporting to backend actor context
- [x] Add Sentry reporting to Electron app context

### Acceptance criteria
Bugs, errors, and crashes are reported and viewable from the Sentry dashboard __only if__ user has opted to share diagnostic data.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
