### ISSUE TITLE
[Task]: Allow user to opt in or out of sending diagnostic data

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2055]
### Task description

Because we are adding sentry we should allow the user to opt in or out of the sentry reporting during setup of a profile or from the settings page.

### Requirements

- [x] profile settings option for opt in or out of reporting
- [x] setup option for opt in or out of reporting

### Acceptance criteria

User is able to opt in or out of reporting

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
