### ISSUE TITLE
[Task]: Show launch screen while app is loading on mobile

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2056]
### Task description

We need to add a launch screen for the mobile version of the application while it is loading.

### Requirements

- [x] Define launch screen based on alpha logo, put images on icons folder
- [x] Add Capacitor Launch screen plugin to hide it when app loads
- [x] Use the script made for icons
- [x] Test splash screen to iOS project
- [x] Test splash screen to android project

### Acceptance criteria

Splash screen is correctly displayed on both iOS and Android while the app is loading.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
Icons was made with this https://github.com/ionic-team/capacitor-assets that could be used to splashscreens

**Comment by amadeu2** [comment]
refs:
https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/launch-screen/
https://material.io/design/communication/launch-screen.html#usage

we should use this plugin https://capacitorjs.com/docs/apis/splash-screen
and call ` SplashScreen.hide()`

**Comment by amadeu2** [comment]
Since it's not possible to use light/dark launch screens with current Capacitor plugins, we'll need to create an specific one for this task.
I've added a new task to do this in the future. #2524
