### ISSUE TITLE
[Task]: Hide application display when mobile app is minimised

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2057]
### Task description

To improve privacy of the application, it would be good to hide the applications display when it is moved out of the foreground on mobile operating systems.

### Requirements

- [x] Hide display when app is not in foreground on iOS
- [x] Hide display when app is not in foreground on Android

### Acceptance criteria

App is hidden when in background and shown in foreground.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
