### ISSUE TITLE
[Task]: Mobile initial onboarding pages

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2075]
### Task description

TBD

### Requirements

- [ ] Landing page
- [ ] Language and theme selection
- [ ] Privacy policy
- [ ] Profile name selection
- [ ] Wallet setup page

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
