### ISSUE TITLE
[Task]: Add (secure) website permissions

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2089]
### Task description
To improve the security of Firefly web, it is recommended that we use a secure enclave (i.e. Stronghold) for handling the allowed website permissions on a per-account basis. 

### Requirements
- [ ] Design mechanisms / API for handling permissions (determine minimum functionality needed), considering both Ledger- and Stronghold-based profiles
- [ ] Implement secure website permissions into Firefly web and backend as necessary

### Acceptance criteria
The website permissions are stored within a stronghold and **cannot be retrieved or modified** unless done so by [browser-extensions] or Firefly.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
