### ISSUE TITLE
[Task]: Refine changing of unit on send form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2092]
### Task description

This task addresses the enhancement request in https://github.com/iotaledger/firefly/discussions/651. Basically, it is weird that the amount changes when the unit changes on the send transaction form, and it would be better for UX if the amount remained the same.

Q: Should this also be the case when we switch to a fiat unit? We should check existing apps like coinmarketcap etc to see what they do and follow the industry standard.

A: For now, we don't change anything when the fiat unit is switched. If there are UX recommendations to change it, we suggest two approaches:
- A) Add a separate field with a fiat amount (See Atomix/Exodus)
- B) Make the dollar amount above the input clickable. When clicked upon, the field will automatically change to fiat (See MetaMask)

### Requirements

- [x] Amount to remain the same when unit of IOTA changes in send form
- [x] Decide if we should do the same for Fiat units.

### Acceptance criteria

The PR meets the above requirements, and is bug free.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
I checked atomic and exodus. They both have a two input fields. One for crypto and one for fiat. 

![image](https://user-images.githubusercontent.com/45079109/149526626-9ff42119-6137-45d1-aca0-f2fd766208ad.png)
