### ISSUE TITLE
[Task]: Delete account on mobile

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2097]
### Task description

Delete Profile account on mobile. 

### Requirements

Use the Capacitor plugin SecureFilesystemAccess to delete profile folder.
- [x] Test on iOS
- [x] Test on Android

### Acceptance criteria

Profile folder must be deleted on device filesystem, could be tested within XCode in hardware debug.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
just tested it's working on develop

**Comment by amadeu2** [comment]
Getting errors on iOS, investigate with Pasquale.
```log
To Native ->  WalletPlugin destroy 44634080
thread '<unnamed>' panicked at 'storage adapter not set: StorageAdapterNotSet("/var/mobile/Containers/Data/Application/6B1BD8DF-0F09-4404-864D-1C843A3890EB/Documents/database/db")', /Users/runner/.cargo/git/checkouts/wallet.rs-aa79dfe38b7895d2/93b81f8/src/account/mod.rs:988:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'pool-thread-#3' panicked at 'called `Result::unwrap()` on an `Err` value: StdThreadJoinError', /Users/runner/.cargo/git/checkouts/wallet.rs-aa79dfe38b7895d2/93b81f8/src/account_manager.rs:396:37
```

**Comment by amadeu2** [comment]
Previous iOS error is fixed now
