### ISSUE TITLE
[Task]: Create top navigation for profile specific pages and actions

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2149]
### Task description

TBD

### Requirements

- [ ] Create top navigation component
- [ ] Add current wallet name to navigation
- [ ] Move profile menu / actions to top navigation
- [ ] Move network indicator to top navigation

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
