### ISSUE TITLE
[Task]: Document Firefly web architecture

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#2163]
### Task description

The Firefly browser extension needs documentation that walks through the architectural structure, its libraries, and important function signatures. This will be a useful resource for onboarding devs to the project and will make it easier for members of the IOTA ecosystem to understand the browser extension.

### Requirements

- [ ] Brief walkthrough of how a browser extension works
- [ ] Architectural documentation that follows extension's logic
- [ ] Summary of libraries
- [ ] Documentation of important function signatures

### Acceptance criteria

The documentation should allow members unfamiliar with the browser extension to understand the structure of the codebase and the important functions it contains. If after reading the documentation they are unable to understand how the extension works without minimal questions, then new requirements should be added before acceptance.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
