### ISSUE TITLE
[Task]: Add explorer link to address history and improve copy of address history

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2181]
### Task description

To match transaction history, we should add a link to the explorer on click of the address in address history. We should then add a copy button for each address. Additionally the copy all button needs optimizing so that there is a space between the address and the balance, it would probably be worth adding the index too.

### Requirements

- [ ] Add link to addresses to explorer
- [ ] Add copy icon button for each address
- [ ] Improve format of data used in the copy all button

### Acceptance criteria

- Link navigates to address in the explorer (M)
- If address is unused no link is shown (C)
- Address is copied to clipboard on click of icon (M)
- Address and balance are separated by a space/character in copy all (M)
- Address index is added to the copy all data (S)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
