### ISSUE TITLE
[Task]: Re-integrate extension actor into actor system

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2187]
### Task description

The Firefly backend is a Rust crate that houses the `firefly-actor-system`, which is responsible for making underlying calls to `wallet.rs` functions. This task is to bring the actor system up-to-date, namely accommodating for the new extension actor that facilitates communication with the browser extension. 

### Requirements

- [ ] Re-wire logic for `ExtensionActor` within the Firefly backend
- [ ] Change name of `wallet-actor-system` to `firefly-actor-system`
- [ ] Cleanup source code as needed (imports, file organization, etc.)

### Acceptance criteria

- [ ] `packages/backend` compiles
- [ ] Successful communication between Firefly desktop and web

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
