### ISSUE TITLE
[Task]: De-duplicate `noise_xx` crate

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#2188]
### Task description

De-duplicate noise_xx crate from glow.rs/src/noise_xx and frontend/wasm/src/noise_xx.

### Requirements

- [ ] Extract noise_xx from glow.rs/src/noise_xx
- [ ] Extract noise_xx from frontend/wasm/src/noise_xx
- [ ] Refactor noise_xx to support both libraries and move to own folder

### Acceptance criteria

Duplication is removed and project successfully compiles. 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
