### ISSUE TITLE
[Task]: Fix need to click in Electron tools console and refresh

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2208]
### Task description

You currently need to click in the console and refresh in order for Firefly Desktop to render during development. There appears to be a race condition between Webpack and Electron.

This is a significant friction point for community devs to set up their development environment. 

### Requirements

- [ ] Fix need to refresh Electron

### Creation checklist

- [X] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
