### ISSUE TITLE
[Task]: Update Electron

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#2213]
### Task description
Update Electron to major version >=12.

Issue: To expose the wallet API, we [create a Proxy object](https://github.com/iotaledger/firefly/blob/561f847abdc013435ce6469c6ea0c1bb4b13a5d7/packages/shared/lib/shell/walletApi.ts#L285), which allows us to intercept calls to the wallet API and store callbacks or override them. We then expose this object to the renderer process [here](https://github.com/iotaledger/firefly/blob/561f847abdc013435ce6469c6ea0c1bb4b13a5d7/packages/desktop/electron/preload.js#L370). Since these are two isolated JS contexts, the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) is used to copy objects between them. The catch is that functions and other complex properties will not be cloned, according to the spec. The reason we’re able to do this now seems to be because Electron 11 deviated from the spec.

### Requirements
- [x] Determine if it is worth considering a later Electron version than 12 (the more recent the better) i.e. with minimal breaking changes (see Snyk chart [here](https://snyk.io/vuln/npm:electron))
- [x] Test on all desktop platforms:
    - [x] Linux
    - [x] Windows
    - [x] MacOS 

### Acceptance criteria
- Electron PR merged and released in 1.4.0

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
I'm reopening this, since we the new bindings should be compatible with the new major versions of electron.
