### ISSUE TITLE
[Task]: Document shared library refactor

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#2214]
### Task description
@maxwellmattryan is working on the shared lib refactor. The new lib structure should be documented in the wiki.

### Requirements
- [x] Complete refactor proposal and share with team
- [x] Reach team consensus on proposed changes
- [ ] Move information to the GitHub wiki

### Acceptance criteria
Meets the above requirements.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
