### ISSUE TITLE
[Task]: Fix security settings title

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2221]
### Task description
There is a small inconsistency in the phrasing of the headers for the different settings sections (in English at least) that is worth fixing.

### Requirements
- [x] Change "Security" to "Security Settings" for consistency (alternatively, use "General", "Security", and "Advanced", omitting "Settings" from each of them)

### Acceptance criteria
- [x] Settings headers are consistent (at least the first three, preferably all)

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
