### ISSUE TITLE
[Task]: Add wallet logs when running in desktop build in dev environment

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2234]
### Task description

We should add the wallet logs to the desktop application to improve debugging, and saving the developer from adding these manually.

### Requirements

- [ ] Add wallet logs based on dev environment variable

### Acceptance criteria

- Wallet logs are added in dev build
- Wallet logs are omitted in production build

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
