### ISSUE TITLE
[Task]: Improve UI/UX of setting hints

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2237]
### Task description
There is room for improvement on the text hint that pops up when a user changes a setting that requires Firefly to be restarted (e.g. changing to system theme, toggling sharing diagnostic data)

### Requirements
- [ ] Change UI/UX to standout to the user (change to black, add `exclamation` icon; check dark theme)
- [ ] Ensure hint phrasing is consistent

### Acceptance criteria
- [ ] New requirements are implemented

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
