### ISSUE TITLE
[Task]: Add `extension` package

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2246]
### Task description

Because the initial development of Firefly web was community-driven, the code did not live inside the primary Firefly repository. This task aims to add the necessary packages to `firefly/packages/extension/`, which luckily isn't a disruptive or cumbersome change.

### Requirements

- [x] Move necessary folders into new directory in Firefly repository (`packages/extension/`)
    - `glow.rs` -> `server/`
    - `glow.js` -> `lib/`
    - `frontend` -> `web/`
- [x] Add necessary packages to yarn workspace
- [ ] Change names in metadata as necessary (e.g. packages, libraries)

### Acceptance criteria

Meets above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
