### ISSUE TITLE
[Task]: Fix theme colours so that they match the FF colour palette

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2247]
### Task description

I noticed some of the colours are off, and with closer inspection the hex codes defined in the tailwind theme have some errors in values and ordering.

### Requirements

- [ ] Update hex codes for each colour to match those defined in the FF colour palette.

### Acceptance criteria

All hex codes are correct in the tailwind config file, and match the ordering of the colour palette scale.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
