### ISSUE TITLE
[Task]: Remove PII from Sentry reports

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2254]
### Task description
Sensitive information __must__ be scrubbed to protect user privacy. 

### Requirements
- [x] Remove `server_name` tag from events sent from Sentry Rust client
- [x] Get machine ID with [`node-machine-id`](https://github.com/automation-stack/node-machine-id)
- [x] Pass machine ID to Sentry Rust and JS clients

### Acceptance criteria
Sensitive information __is NOT__ sent to Sentry within error or crash reports.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
Done in #2243
