### ISSUE TITLE
[Task]: Remove Sentry test errors before merge

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2255]
### Task description
There are a few test error cases scattered throughout the code to test the crash reporting mechanism. __They must be removed before merging the changes into `develop`__!

### Requirements
- [x] Remove the following test errors
    - [x] Call undefined function when clicking back in CreateAccount.svelte
    - [x] Throw error when displaying a toast notification
    - [x] Throw error (in shell/walletApi.ts) when receiving LockStrongholdResponse
    - [x] Panic when trying to log out (calls destroy in backend)

### Acceptance criteria
There are no (intentional) errors or crashes.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
