### ISSUE TITLE
[Task]: Prepare build workflows for Sentry

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2256]
### Task description
The GitHub workflows for building Firefly need to be adjusted in order to support Sentry.

### Requirements
- [x] Add repo support for the environment variables
    - `SENTRY_ENVIRONMENT` - either `prod`, `beta`, or `test`, indicating the specific release environment
    - `SENTRY_DSN` - the client keys used to connect and send crash reports to (specific per-project in Sentry dashboard)
    - `SENTRY_AUTH_TOKEN` - needed only for the webpack configuration
- [x] Adjust workflow(s) as necessary including env vars in relevant build steps for each part of the app (`backend`, `desktop`, `mobile`)

### Acceptance criteria
Firefly can be packaged via GitHub Actions _and_ appropriately sends or __does NOT__ send crash reports.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
