### ISSUE TITLE
[Task]: Convert popup modal to draw on mobile.

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2258]
### Task description

To fit in with the UX of mobile, the popups that are displayed as modals on desktop, should be displayed as slidable draw components on mobile. But there should be an option to force a popup ui if needed.

### Requirements

- [ ] Make popup component a draw on mobile
- [ ] Add parameter for forcing a pop up.

### Acceptance criteria

Popups now open as draws on mobile and as modals on desktop.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
