### ISSUE TITLE
[Task]: Update privacy policy

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2262]
### Task description

The privacy policy needs to be updated to include Sentry and Cloudflare

### Requirements

- [x] Update privacy policy in [Legal.svelte](https://github.com/iotaledger/firefly/blob/develop/packages/shared/routes/setup/Legal.svelte)
- [x] Update privacy policy on the Firefly website

### Acceptance criteria

All requirements completed

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
