### ISSUE TITLE
[Task]: Use versioning to determine whether to alert the user of privacy policy changes

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2263]
### Task description

We need to alert users when we update the privacy policy. As discussed on Discord, we should "version" the privacy policies so that we can easily tell what version the user last accepted. We can use the `appSettings` store for this, so existing users will have the following state:

```js
{
  ...
  lastAcceptedPrivacyPolicy: 1
}
```

Then, when the app is opened, we can check if `appSettings.lastAcceptedPrivacyPolicy < PRIVACY_POLICY_VERSION`

### Requirements

- [ ] Implement versioning for privacy policy
- [ ] Determine whether the user has accepted the latest privacy policy
- [ ] Alert the user if the privacy policy was updated
- [ ] Set `lastAcceptedPrivacyPolicy` to `1` for existing users

### Acceptance criteria

All requirements completed

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
