### ISSUE TITLE
[Task]: Add Sentry initialization conditions

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2266]
### Task description
Each time the Sentry JS module was being imported, initialization code was being run. By using a functional-style export, we can pass a parameter when importing that specifies whether or not to initialize Sentry.

### Requirements
- [x] Add functional-style export to `packages/desktop/sentry.js`, allowing to specify if Sentry needs to be initialized or not 

### Acceptance criteria
Sentry is initialized appropriately.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
