### ISSUE TITLE
[Task]: Separate alpha, beta and production builds

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2283]
### Task description

We want to be able to run a build script specifically for desktop alphas, betas, this way we can define an environment variable and use this to define pre-release specific features etc. This can then be used by GH actions to build beta versions.

### Requirements

- [x] Additional script for beta build
- [x] Beta is added to name of application when using this script
- [x] Beta logo is used
- [x] Application installs in new directory
- [x] Developer profile is auto selected
- [ ] Show warning when creating a non-dev profile on non `prod` versions
### Acceptance criteria

All of the above requirements have been met.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
