### ISSUE TITLE
[Task]: Beta build GitHub action

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2284]
### Task description

We want to be able to be able to build the beta builds through automatic GH action when we tag a commit with a beta flag. i.e. `desktop-1.4.0-beta-1`. It will need to call a separate build script that is yet to be merged into develop.

We don't want the normal desktop action to be ran for this tag.

### Requirements

- [x] Adjust existing build action so that the regular expression for tags is more specific.
- [x] Create new github action that builds beta version using `yarn build:beta` command or similar
- [x] Do not publish beta build to website or s3

### Acceptance criteria

GH action is able to complete, and beta builds are built. This is dependent on https://github.com/iotaledger/firefly/issues/2283 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
