### ISSUE TITLE
[Task]: Document more developer tips

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2285]
### Task description

There are quite a few helpful developer tips that we should add to the [wiki](https://github.com/iotaledger/firefly/wiki/Guide:-Developer-Tips).

### Requirements

- [x] Adding a new Svelte page
- [x] Adding a new setting (assigned to @Tuditi in #2215)
- [x] Adding or editing icons (needs SVG data + other places if settings or tab icon)
- [x] ~~Using `localize` and ICU message formatting (super useful resource [here](https://lokalise.com/blog/complete-guide-to-icu-message-format/))~~ This will go into the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions) wiki page.
- [x] Exposing a new wallet.rs endpoint (subject to change with upcoming `shared/lib` refactor)
- [x] Initializing backend logger
- [x] Common errors and their fixes (e.g. re-running `yarn`)
- [x] Properly refreshing the dev console
- [x] When to run re-build / re-compile / re-start with `yarn` in what directories (avoid unnecessary time waiting for compiling)
- [x] Workflow tips for managing one's own work and reviewing others' (second clone of Firefly useful for not messing with node packages)

### Acceptance criteria

The document is kept clean and updated.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
