### ISSUE TITLE
[Task]: Document coding conventions 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2287]
### Task description
The [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Code-Conventions) wiki currently contains no content. With the upcoming refactor it is a good time to document our rules.

### Requirements
- [x] Move coding conventions from [here](https://hackmd.io/RLoGOMc4S-KcSN8p0qp7Ng)
- [x] Determine if should stick with TSDoc or not (answer: **yes**)
- [x] Add rules `kebab-case` file naming
- [x] Add rules for import order (not necessary if enforced by linter... see if possible first)
- [x] :x: Populate the handbook with appended document (blocked until handbook is created)

### Acceptance criteria
The documentation completes the above requirements and strictly contains __only__ rules about coding.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
@maxwellmattryan keep the testing in testing wiki, and the linting in the developer tips (I just moved that there)
Let's keep the code conventions explicit rules.

I.e.
Arrow function over General function
Component structure script, components, style

**Comment by maxwellmattryan** [comment]
> Let's keep the code conventions explicit rules.

Yes, this sounds good. I do think writing tests falls somewhat under that category as they also have specific coding conventions, but I also think devs wanting to find that information would expect it to be in separate places.

**Comment by rajivshah3** [comment]
On Discord I proposed enforcing `===` and `!==` (https://eslint.org/docs/rules/eqeqeq). Using `==` can cause some unexpected bugs if the objects being compared are different types, so we probably want to avoid that unless it's necessary for some reason
