### ISSUE TITLE
[Bug]: Fix shortcut text for quitting application.

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#2303]
### Task description

The dropdown menu in Firefly (Windows and Linux) has the wrong shortcut for quitting the application. The specified text should be changed from Win+Q to Alt+F4 for Windows and from Q to Ctrl+Q for Linux. 

### Requirements

- [x] Change the shortcut text from Win+Q to Alt+F4  in the dropdown menu for Firefly (Windows).
- [x] Change the shortcut text from Q to Ctrl+Q  in the dropdown menu for Firefly (Linux).

### Acceptance criteria

- [x] The shortcut text for quitting on the Windows platform has been changed to Alt+F4.
- [x] The shortcut text for quitting on the Linux platform has been changed to Ctrl+Q.
- [x] The shortcut text for quitting on Mac remains Cmd+Q.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kraftjs** [comment]
The API mechanism that Electron uses to decide what shortcut string to use is described [here](https://www.electronjs.org/docs/latest/api/accelerator).

**Comment by kraftjs** [comment]
`git config --global core.autocrlf input`
Need to set the above on Windows; otherwise, git will convert all endlines in the repo from Line Feeds (LF) to Carriage Returns + Line Feeds (CRLF) because that is the format Windows prefers. This causes an issue when running the prettier linter before commit because the linter will want you to change all the endlines back to LF to pass linting, thus causing every file in the repo to appear in the working directory.
