### ISSUE TITLE
[Task]: Fix chunk loading error

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2304]
### Task description

There is an error as a result of trying to load a particular (unknown) module that is intended for __only__ mobile.

### Error
```
Error: {"type":"Render Context (Unhandled Rejection)","message":"Uncaught ChunkLoadError: Loading chunk 987 failed.\n(error: file:///tmp/.mount_fireflDdAZZZ/resources/app.asar/build/987.987.js)","stack":"Error: Uncaught ChunkLoadError: Loading chunk 987 fai...
File "./electron/main.js", line 318, col 12, in N 
  return windows[windowName]
Module "main", line 716, col 36, in null.<anonymous>
    
File "electron/js2c/browser_init.js", line 189, col 579, in null.<anonymous>
File "electron/js2c/browser_init.js", line 157, col 9339, in Object.<anonymous>
File "events.js", line 315, col 20, in Object.emit
File "domain.js", line 483, col 12, in Object.EventEmitter.emit
File "webpack://desktop/../node_modules/@sentry/electron/dist/main/integrations/onuncaughtexception.js", line 48, col 61, in Object.n.emit
  nodeClient.captureException(theError, { originalException: error }, core_1.getCurrentHub().getScope());
```

### Requirements

- [ ] Remove any and all unnecessary build artifacts for desktop
- [ ] Ensure that no `ChunkLoadError` occurs on startup

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
