### ISSUE TITLE
[Task]: Document more glossary terms

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2308]
### Task description

The glossary should contain all relevant terminology that a developer should know or at least be familiar with. It needs to contain more terms as our scope increases and as we onboard more new developers.

### Requirements

The following items __must__ have entries in the glossary:
- [ ] Account vs wallet
- [ ] Assembly
- [x] BIPs
    - [x] 32
    - [x] 39
    - [x] 44
- [ ] Coin vs token
- [ ] ERCs
    - [ ] 20
    - [ ] 721
    - [ ] 1155
- [ ] EVM
- [ ] Firefly desktop vs mobile vs web
- [ ] ISCP
- [ ] L1 vs L2
- [ ] Profile 
- [ ] Shimmer
- [ ] Smart contracts
- [x] Stronghold
- [x] Tangles (main, test, dev, private)
- [ ] TIPs
    - ...

### Acceptance criteria

Completes definitions / entries for all of the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
