### ISSUE TITLE
[Task]: Add path alias support for TypeScript `lib` modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2315]
### Task description
As part of the refactor, we need to add support for path aliases according to our [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions#path-aliases). There are multiple places where we could potentially support path aliases with a few of them being more important and commonly used than the others (i.e. `shared/lib` or `shared/components`).

It may also be worth checking out [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) :+1:. 

:information_source: __ONLY__ support will be added; actual changes to the import statements will be added at a later point. The reasoning is to be more efficient to modify the same pieces of code as least times as possible (i.e. the import paths will all soon change anyway so best to add the path aliases then).

### Requirements
- [x] Add aliases for the following paths*:
  - [x] `@common/*` --> `shared/lib/common/*`
  - [x] `@core/*` --> `shared/lib/core/*`
- [x] Add support for usage in the following places:
  - Desktop
    - [x] `App.svelte`
    - [x] `lib/*.ts`
  - Mobile
    - [x] `App.svelte`
    - [x] `capacitor/lib/*.ts`
  - Shared
    - [x] `components`
    - [x] `lib`
    - [x] `lib/shell`
    - [x] `lib/tests`
    - [x] `routes`

\* As this particular PR is adding support only, the paths will reflect the current structure of the library. They will be updated once the code has actually been re-organized.

### Acceptance criteria
Meets the above requirements and adheres to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions#path-aliases) for path aliases.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
