### ISSUE TITLE
[Task]: Improve pull request template

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2316]
### Task description

It would be worth listing and drafting a PR template that works for us. Additionally there's some spacing issues to fix with the most recent change.

### Requirements

- [x] Fix list item spacing (too tabbed over)
- [ ] Improve section for testing platforms
- [ ] Changelog (balance between user-facing and technical changes?)
- [ ] Bold all placeholder text (if it's kept in PRs then best to make it more distinct by bolding it)
- [ ] Add reminder for coding conventions (besides checklist)
- [ ] Change checklist items so that they can be checked regardless of applicability

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
