### ISSUE TITLE
[Task]: Tidy up UI on mobile

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2322]
### Task description

Group of various UI fixes

### Requirements

- [x] Onboarding fix layout shift with animations
- [x] find a way to fix height for the main window, when something is more large than height its get out of screen
- [x] Change css `user-select: none|text` on every tap action
- [x] adapt developer profile banner
- [x] fix scroll on onboarding mnemonics screen on ios
- [x] remove auto-focus on inputs onboarding
- [x] change popup location to top, it's hidden by the keyboard
- [x] z-index notifications, behind drawer shadow now
- [x] remove close button on send and receive drawers
- [x] on iOS when click on text mnemonic buttons the text get selected with double tap, disallow it
- [x] add shadow on top, overlaping status bar items. Add also on main menu.
- [x] fix Node config on main menu, adapt to mobile with.

### Acceptance criteria

must to be tested on real iOS/Android devices

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
> change popup location to top, it's hidden by the keyboard
About this one, if we move its position in the DOM to be more top we could have issues displaying the popups in settings mobile afair, might be worth testing that. I mean the nested popups like the ones that open to configure nodes.

**Comment by begonaalvarezd** [comment]
> remove focus on inputs onboarding

Do we really want to remove the focus on all inputs? Its true that without focus the page will look nicer but then you are making the user click on every view. But I havent tested onboarding mobile on a real device so idk 😅

**Comment by amadeu2** [comment]
> > remove focus on inputs onboarding
> 
> Do we really want to remove the focus on all inputs? Its true that without focus the page will look nicer but then you are making the user click on every view. But I havent tested onboarding mobile on a real device so idk sweat_smile

yeah it could be wrong 😅, imo when the keyboard is open on mobile there is small space to show more things than the input itself, and there is more information to read and undestand or to tap other options before write inside it, it's more notable on small mobile screens, but even in large screens is needed to scroll to know what's there hidden.
