### ISSUE TITLE
[Task]: Add Capacitor plugin for secure mobile OS filesystem access

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2331]
### Task description

Add new Capacitor plugin based on https://github.com/ourcodeworld/capacitor-native-filepicker
because specifically for iOS the OS gives the app permission to access that directory and all of its contents. 
The document picker returns a security-scoped URL for the directory. I'd added startAccessingSecurityScopedResource() and stopAccessingSecurityScopedResource() to access the files btw other things.
We need it for export/import Stronghold.

We also need a special implementation for Android, versions 10 and 11 have specific file managment and has conflict with Capacitor.

### Requirements

- [x] iOS Export/import stronghold file, secure delete profile folder, save pdf to external app path, add stronghold file extension
- [ ] Android Export/import stronghold file, secure delete profile folder, save pdf to external app path

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
