### ISSUE TITLE
[Task]: Investigate if we can move walletPluginApi to the backend

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2337]
### Task description

To match the pattern of the Node bindings, we should investigate if we can move the walletPluginApi bindings into the backend folder for capacitor.

### Requirements

- [ ] Investigate if we can move the walletPluginApi to backend
- [ ] Move the walletPluginApi to backend if possible

### Acceptance criteria

We have moved if possible the bindings, if not then we can close this issue without a PR.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
