### ISSUE TITLE
[Task]: Fix onboarding layouts mobile

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2339]
### Task description

It seems that some changes to desktop have broken the onboarding layouts that begona had updated. We need to fix the mobile layouts so that they include the correct format on mobile with the correct contents that has been updated on desktop.

### Requirements

Merge onboarding changes from develop and old mobile PR found here: https://github.com/iotaledger/firefly/pull/2112/files#diff-c1f48fd74a4f1320f2ba66a66eabb9eb332be56223a730ee7c1def709c14be9b

- [x] Specifically the legal page
- [x] The new crash reporting page
- [x] Check other pages

### Acceptance criteria

Onboarding layout looks correct on mobile
Correct legal information is displayed.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
