### ISSUE TITLE
[Task]: Add backend Capacitor bindings as workspace

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2344]
### Task description
The Capacitor bindings package (`packages/backend/bindings/capacitor/`) is not currently a part of the repository's Yarn workspaces. As a result there is more than one `yarn.lock` file within the repo.

### Requirements
- [x] Add `packages/backend/bindings/capacitor` to `workspaces` field in `firefly/package.json`
- [x] Fix `yarn.lock` discrepancies if any

### Acceptance criteria
Meets the above requirements.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
