### ISSUE TITLE
[Task]: Design navigation for single account view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2352]
### Task description

As we are moving towards a single account view, we need to update the navigation so that a user can navigate between accounts.

### Requirements

- [ ] Switch account from anywhere
- [ ] View security information from anywhere
- [ ] Add new account from anywhere

### Acceptance criteria

Design agreed by epic owner / product owner.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@jvegis would you consider this task done? Can we close it?
