### ISSUE TITLE
[Subtask]: Design claiming transaction flow for stardust

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2354]
### Task description
Now that we have asynchronous transaction flows in stardust based networks, we need a flow for users to be able to claim the transactions that they potentially own.

### Requirements
- [ ] User should be able to see how much byte cost that is required for the transaction to claim
- [ ] User must see when the claimable transaction has expired
- [ ] User must be able to claim the transaction

### Acceptance criteria
Design agreed by epic owner / product owner

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
