### ISSUE TITLE
[Subtask]: Modify activity panel and card design for stardust

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2355]
### Task description
Now that we have potentially more transaction types, additional details about a transaction and synchronous and asynchronous transactions, we need to modify the activity panel to make it useful and compatible with stardust.

### Requirements
- [ ] User can see if a transaction needs claiming
- [ ] User can see expiration time of a claimable transaction
- [ ] User can initiate claim or ignore claim of transaction
- [ ] User can see expired transactions
- [ ] User can dismiss expired transactions

### Acceptance criteria
Design agreed by epic owner / product owner

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
