### ISSUE TITLE
[Subtask]: Design overview of balance and storage deposit breakdown

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2356]
### Task description
Now that we have a potential storage deposit or multiple storage deposits associated to a wallet. We need a way to show the breakdown of the balance and storage deposit to the user.

### Requirements
- [ ] Show total balance
- [ ] Show pending balance (locked by pending transactions)
- [ ] Show total storage deposit
- [ ] Show breakdown of storage deposit.

### Acceptance criteria

Design agreed by epic owner / product owner

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Looks good, might change as we become aware what is technically feasible to display.
