### ISSUE TITLE
[Subtask]: Modify transaction details design for stardust

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2358]
### Task description
Now that we support feature blocks and have a byte cost in stardust, we should show these details in the transaction details pane.

### Requirements
- [ ] Feature block details are displayed in transaction details
- [ ] Byte cost is displayed in transaction details
- [ ] Ensure the correct and relevant information is present
- [ ] Ensure copy and visit explorer actions is present

### Acceptance criteria
Design approved by epic owner / product owner

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Looks good 👍 , just need to consider how this changes with claiming flow in other task and different assets in M5.
