### ISSUE TITLE
[Task]: Create empty `core` and `common` packages

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2364]
### Task description

The new file structure will house all module files inside either the `core` or `common` package. This task is simply creating and adding those directories to allow for simultaneous PRs more easily.

__This will NOT affect any currently open PRs__; this is strictly _adding_ new files and directories.

### Requirements

- [x] Create a `core` module directory
- [x] Create a `common` module directory

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
