### ISSUE TITLE
[Task]: Create `core` modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2367]
### Task description
`core` refers to a group of modules that are the more infrastructural, integral parts the Firefly stack. These are things like communicating via the bridge with the actor system, platform handling with Electron and Capacitor, routing logic for the application, and so on.

### Todo (check means WIP)
- [ ] `actor` (remaining: `walletActor.ts`)
    - [ ] Change `id` to `messageId` in `BridgeMessage`
    - [ ] Change `id` to either `messageId` or `actorId` in `BridgeResponse` (figure which is being used here)
- [ ] `api`
    - `validation` (base validation... different modules should contain their own validation logic grabbing from `core` validation module) 
- [ ] `app`
- [ ] `icons`
- [x] `i18n`
- [ ] `notification`
- [ ] `platform`
- [ ] `popup`
- [ ] `shell`
- [ ] `utils`
    - `convert`
    - `crypto`
    - `format`
    - `helpers`
    - `math`
    - `os`
    - `random`
    - `time`
    - `ui`
    - `units`

### Complete
- [x] `router` (#2505)

### Requirements
- [ ] All the above modules are created and organized according to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions#organization-1)
- [ ] Add or modify comments as necessary (+ coding conventions for writing)
- [ ] Unit tests are sensibly setup within new library structure

### Acceptance criteria
Meets the above requirements.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
