### ISSUE TITLE
[Task]: Create `common` modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2368]
### Task description
`common` refers to a group of modules that are intended to be consumed often and throughout the application (e.g. other library files and UI components). These are things like handling network clients, performing wallet operations, participating in events, interacting with Stronghold or Ledger, and so forth. __They are the domain-related business logic of the application__.

### Todo (check means WIP)
- [ ] `ledger`
- [ ] `market`
- [ ] `migration`
- [ ] `network`
- [ ] `participation`
- [ ] `profile`
- [ ] `storage`
- [ ] `stronghold`
- [ ] `wallet`

### Complete
- [x] `deep-links` (#2482)

### Acceptance criteria

All the above modules are created and organized according to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions#organization-1).

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
