### ISSUE TITLE
[Task]: Update bug report template and automation

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2373]
### Task description

Having reorganised and changed some of the labels, we need to amend the bug report form and automation to use the new label `bug report` instead of `type:bug`.

### Requirements

- [ ] Change label in bug report yml
- [ ] Change label used in assign bugs to project action

### Acceptance criteria

Correct label is used.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
