### ISSUE TITLE
[Task]: Add path alias support for `components` and `routes`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2376]
### Task description
There is a lot of configuration involved to get path aliases working particularly for Svelte components, and it will take some time to find the right one that works for our project.

:information_source: __It is likely that this can be accomplished simply by naming the `shared` package to `@lib` or something else__. This package is brought in as a dependency which is how it is resolved in components just by using `shared/components/*`.

### Requirements
- [ ] Add aliases for the following paths*:
  - [ ] `@components/*` --> `shared/lib/components/*` (Cannot resolve path aliases for Svelte components
  - [ ] `@routes/*` -> `shared/routes/*` (Cannot resolve path aliases for Svelte components)
- [ ] Add support for usage in the following places:
  - Desktop
    - [ ] `App.svelte`
  - Mobile
    - [ ] `App.svelte`
  - Shared
    - [ ] `components`
    - [ ] `routes`

### Acceptance criteria
Meets the above requirements and adheres to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions#path-aliases) for path aliases.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
