### ISSUE TITLE
[Task]: Add path alias support in `backend`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2377]
### Task description
There is some additional configuration involved to get paths resolving correctly for backend code. Although these are files that aren't changed that often, it would be nice to also be able to usage path aliases in this part of the codebase.

There are two separate `tsc`-related issues at hand (see [solution](https://stackoverflow.com/questions/44676944/how-to-compile-a-specific-file-with-tsc-using-the-paths-compiler-option)):
- Cannot resolve path aliases used by code in `shared/lib` (imported in `backend/bindings/node/index.ts`)
- Cannot resolve path aliases used directly in `backend/bindings/node/index.ts`

:x: **Until this is working, any compiled code in `backend/` including sub-dependencies WILL NOT work!**

### Requirements
- [x] Add path alias usage in the following places:
  - [x] `backend/bindings/capacitor/src/*.ts`
  - [x] `backend/bindings/node/index.ts` (Cannot resolve path aliases at compile-time, `module-alias`, `tsconfig-paths`, and `tsc-alias` have not worked so far)

### Acceptance criteria
Meets the above requirements and adheres to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions#path-aliases) for path aliases.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
