### ISSUE TITLE
[Task]: Differentiate actor system types

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2378]
### Task description
The types for interacting with the actor system could benefit from being a bit more explicitly typed with different names, mainly separating the idea between a `Message`, a `Response`, and an `Event`. As of now we use `Message` to mean both a message that is sent to the wallet actor _and_ the response from that message.

### Requirements
- [ ] Define types using names `Message`, `Response`, or `Event`
- [ ] Change function / method names as needed
- [ ] Separate `Response` into `Response` _and_ `Event` in shared library code

### Acceptance criteria
Meets the above requirements and adheres to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions).

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
