### ISSUE TITLE
[Task]: Remove side-effects from API wrapper functions

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2379]
### Task description

Per the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions), wrapper functions can contain __NO__ side-effects.

:warning: This is likely to be a volatile PR with potential for breaking changes as we have been relying on the side-effects within those functions.

### Requirements

- [ ] Remove _all_ side-effects from __all__ API wrapper functions

### Acceptance criteria

Meets the above requirements and adheres to the [coding conventions](https://github.com/iotaledger/firefly/wiki/Guide:-Coding-Conventions).

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
