### ISSUE TITLE
[Task]: Remove mobile-specific packages from `shared`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2380]
### Task description

Currently there is mobile-specific code being brought into the `shared` package, causing errors to occur.

### Requirements

- [ ] Determine method of exposing `CapacitorApi` such that mobile packages __are NOT__ brought in
- [ ] Implement chosen method

### Acceptance criteria

Meets the above requirements with __NO__ platform-package mismatching.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
