### ISSUE TITLE
[Task]: Remove keychain usage by removing the pincodemanager

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2383]
### Task description

We should investigate whether storing the PIN in the system keychain is necessary, and remove any keychain usage it if it's not required. This would resolve the following issues (and possibly others):
- Entries disappearing from Credential Manager on Windows
- Dependencies on `libsecret`, `gnome-keyring`, and the Secret Service API on Linux (and issues related to these dependencies)

### Requirements

- [x] Investigate whether storing the PIN in the keychain is necessary
- [ ] Remove keychain usage if not necessary

### Acceptance criteria

Above requirements are satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
This has already been investigated and wallet.rs team have made the necessary changes. We should now be able to remove the keychain, and make calls directly to the backend with setStoragePassword api. And if the the password is incorrect wallet.rs will return an error, which we can handle.

We also need to add an extra call on logout to clear the decrypted memory from storage. Wallet.rs team have added an api call for this too, so reach out to Thoralf for the details.

We will need to do thorough testing on existing profiles for login, logout and updating password.

@kraftjs if you need help just ping me.

**Comment by nicole-obrien** [comment]
The method on wallet.rs that needs to be added to bindings and called on logout is: `ClearStoragePassword`
