### ISSUE TITLE
[Task]: Cleanup package names

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2385]
### Task description
Our package names for all components of Firefly are inconsistent and could benefit from some common naming. It's best to use `firefly-*` as a prefix. Additionally, we will be adding the extension actor to the backend soon, making the name `wallet-actor-*` not technically correct.

### Requirements
- [x] Change backend to `firefly-actor-system`
- [x] Change backend Capacitor bindings to `firefly-actor-system-capacitor-bindings`
- [x] Change backend NodeJS bindings to `firefly-actor-system-nodejs-bindings`
- [x] Change desktop name to `firefly-desktop` and product name to "Firefly Desktop"
- [x] Change mobile name to `firefly-mobile` and product name to "Firefly Mobile"

### Acceptance criteria
Meets the above requirements.

### Creation checklist
- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
