### ISSUE TITLE
[Bug]: Firefly is installed in a folder called `desktop` on Windows

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2395]
### Task description

Firefly is getting installed in `C:/Users/<user>/AppData/Local/Programs/desktop/` on Windows. The `desktop` may be coming from the `package.json`:

https://github.com/iotaledger/firefly/blob/69d539858c4124b767107e4627d90479c36a278b/packages/desktop/package.json#L2

We should change this to `firefly-desktop`, but we need to check the following:
- [ ] How does this impact the auto-updater, which may use paths based on the name in the `package.json`?
- [ ] Does this affect user data?
- [ ] Does changing the name in the `package.json` have effects on other platforms?

In other words, we need to closely examine what happens when upgrading from Firefly 1.3.3 (where the `name` is `desktop`) to a version of Firefly where the `name` is `firefly-desktop`.

### Requirements

- [ ] Change `name` in `package.json`
- [ ] Test fully on all platforms
  - [ ] macOS
    - [ ] Auto-update works as expected
    - [ ] User data is not lost during an update
  - [ ] Linux
    - [ ] Auto-update works as expected
    - [ ] User data is not lost during an update
  - [ ] Windows
    - [ ] Original issue (installed in a folder called `desktop`) is resolved
    - [ ] Manual updates work as expected
    - [ ] User data is not lost after an update

### Acceptance criteria

Above requirements satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?
