### ISSUE TITLE
[Task]: Add workaround to fix Sentry on mobile

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2397]
### Task description

Since Sentry isn't implemented on mobile, we must to fix it to be able create account.

### Requirements

- [ ] Create account and use the app.

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
