### ISSUE TITLE
[Task]: Add Sentry support

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2403]
### Task description

There is currently no Sentry support for mobile, which we need.

The backend is already covered from the previous Sentry implementation, so it is strictly mobile where support needs to be added. 

### Requirements

- [ ] Consider any differences in the way desktop and mobile persist app settings (specifically for when initializing the backend; we __must__ have a file to tell us whether or not the backend needs to be initialized with Sentry)
- [ ] Determine what places Sentry needs to be added in the mobile stack
- [ ] Add Sentry SDK in ^ those places
- [ ] Test errors in mobile-specific area

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
Sentry's Rust SDK does not officially support iOS and Android, so error reports from iOS and Android may show as coming from macOS/Darwin and Linux. This might be easy to fix with a PR adding iOS and Android to this file https://github.com/getsentry/sentry-rust/blob/master/sentry-contexts/src/utils.rs
