### ISSUE TITLE
[Task]: Document IOTA deep links

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2404]
### Task description

We don't have __any__ documentation currently for how to use or handle IOTA-based deep links. While this will start out on the Firefly wiki, this touches the whole ecosystem and will need to be discussed potentially as a TIP. It will also need to be migrated to the official IOTA wiki.

### Requirements

- [ ] Write basic doc for deep links (what they are, how / where to use them, etc.)
- [ ] Add to Firefly wiki
- [ ] Add to IOTA wiki

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
