### ISSUE TITLE
[Task]: Implement doc system for TSDoc comments

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2405]
### Task description

Right now we have [TSDoc](https://tsdoc.org/) comments in _some_ places but not all.

### Requirements

- [ ] Create conventions for writing these comments (esp. for functions... also probs best not to write these until functions are finalized or task is nearly complete).
- [ ] Design automated system for keeping documentation up-to-date (or is documentation generated each commit, merge, PR, etc.)
- [ ] Write TSDoc comments for the necessary code components (e.g. functions, interfaces, types, constants, stores)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
Closing as task has been dissolved into other tasks.
