### ISSUE TITLE
[Task]: Remove C bindings package

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2414]
### Task description

This package is no longer necessary nor being used (since we're using Capacitor plugins), so it can and should be removed.

### Requirements

- [ ] Remove the `c/` bindings package

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
