### ISSUE TITLE
[Task]: Ensure proper hover states throughout app

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2420]
### Task description

Right now there are some items (at least in the dashboard view) that _do NOT__ have proper hover states implemented. 

### Requirements

- [ ] Implement hover states for...
    - [ ] Transaction history items
    - [ ] Dashboard security tiles

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
