### ISSUE TITLE
[Task]: Create app icon logos for each stage

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2425]
### Task description

For the alpha and beta version of the application we would like to have a application icon that distinguishes it from the production version of the app.

### Requirements

- [x] Alpha application icon
- [x] Beta application icon
- [x] Alpha firefly logo
- [x] Beta application logo

### Acceptance criteria

Logos are generated in correct format, and following the individual platform icon guidelines.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
