### ISSUE TITLE
[Task]: Fix account tile hover styles

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2435]
### Task description

Some of the hover styles for accounts have been overwrote, and now only use white text on hover, instead of using the brightness function to determine if the text should be light or dark based on the background colour.

### Requirements

- [ ] update the account styles so that the correct text colour is displayed on hover.

### Acceptance criteria

Account tiles show light text on dark backgrounds such as black, and dark text on light backgrounds such as white.

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
