### ISSUE TITLE
[Task]: Prevent auto-updater on alpha and beta versions

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2436]
### Task description

Now we are releasing several versions at the same time, we should prevent the auto-updater for non production versions:
i.e. alpha and beta

### Requirements

- [x] Prevent auto update on non `prod` stage application

### Acceptance criteria

App doesn't look for new version on `alpha` and `beta` builds

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
