### ISSUE TITLE
[Task]: Fix Windows build for capacitor bindings workspace

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#2450]
### Task description

The addition of `packages/backend/bindings/capacitor` to yarn workspaces has stopped Windows from successfully building. This is because of a preinstall script in `packages/backend/bindings/capacitor/package.json` trying to use `rimraf` before yarn has successfully setup the workspace. Deleting this preinstall script causes the mobile testing to break. The task is to create a node script that can replace this dependency on Windows and maintain the current functionality in mobile.

### Requirements

- [ ] Replace the `rimraf` dependency of the preinstall script in `packages/backend/bindings/capacitor/package.json` with a node script

### Acceptance criteria

- [ ] Yarn workspaces build on all operating systems
- [ ] Mobile functionality is unchanged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
