### ISSUE TITLE
[Task]: Update `neon` in Node.js backend bindings

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2456]
### Task description

In order to use Electron 13+ in Firefly Desktop, we need to update `neon`. The work for this will likely be similar to https://github.com/iotaledger/wallet.rs/pull/674. Ideally, we should be able to use the `napi-6` feature.

### Requirements

- [x] Update `neon` to the latest version possible
- [ ] See if we can use the `napi-6` feature

### Acceptance criteria

- [ ] Above requirements satisfied
- [ ] Tested on macOS
- [ ] Tested on Windows
- [ ] Tested on Linux

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
