### ISSUE TITLE
[Task]: Fix Mobile Android project folder

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2462]
### Task description

Android project folder having old configs and files producing errors and crashes, updated deps to latest version.

### Requirements

- [x] update project folder
- [x] update Capacitor dependencies

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
