### ISSUE TITLE
[Task]: Fix: Capacitor Bindings Wallet plugin

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2464]
### Task description

Android project as incorrect folder names as Java conventions.
On Desktop the name of Stronghold directory name is `__storage__`, we currently are using `database` on the plugin code, so will change it.
Also added error handling to avoid crashes on Java code and update Capcitor plugin dependencies to latest version.

### Requirements

- [x] change to use __storage__ folder as in desktop
- [x] handle exceptions on android
- [x] fix rename directory to new package name on android
- [x] update capacitor core deps to latest version

### Acceptance criteria

Android and iOS must run on real devices and emulators.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
