### ISSUE TITLE
[Task]: Move wallet binding proxies to one place

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2469]
### Task description

Right now we are using custom middleware proxies for the wallet bindings to both handle callbacks and also stack traces. The code could be a bit cleaner and also put in a singular place. 

### Requirements

- [ ] Create more consistent method of using `Proxy` for middleware

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
