### ISSUE TITLE
[Task]: Change phrasing of "IOTA links" to "deep links"

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2483]
### Task description

Despite initially using the term "IOTA link", it is likely that this will come to represent INS (IOTA Name Service) domains rather than deep links. To avoid confusion down the line, it is best to change this now. 

### Requirements

- [ ] Change all verbage of "IOTA links" to "deep links" (or "IOTA deep links")

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
