### ISSUE TITLE
[Task]: Choose tool / framework for generating static doc website

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2484]
### Task description

This is an important step in creating the Firefly handbook as what tool we choose now impacts everything about the documentation website aside from the content itself. An easy-to-use and easy-to-integrate 

The following are considerable options:
- [`retype`](https://github.com/retypeapp/retype)
- [Docusaurus](https://docusaurus.io/)*

\* It is worth noting that Docusaurus is used in most if not all projects within the IOTA Foundation. It is most likely that the majority of those are intended for external audiences, where the Firefly handbook is to be used by the development (and possibly design) team.

It is important to consider how this all will look in the future when we _do_ have external-facing documentation for developers wishing to integrate Firefly functionality into their software (esp. Firefly web).

### Requirements

- [x] Choose a tool or framework for generating the static documentation website
- [x] Ensure that the chosen technology can / will...
    - [x] Integrate nicely with GitHub actions to enable automated updates
    - [x] Allow developers to efficiently change and view documentation
    - [x] Allow expressive page styling and organization to cover our many needs and documents
    - [x] Allow the documentation to live inside or at least close to the repository
    - [x] **NOT** complicate things or confuse developers (aka easy to use and navigate) 

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
