### ISSUE TITLE
[Task]: Determine method of generating specifications from TSDoc comments

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2485]
### Task description

With our ever-increasing code library, it is becoming more and more important that we can easily display all of its available functionality. The most efficient way to do this while keeping the documentation up-to-date is to create some automated process where any new or changed code results in a re-generation of its corresponding specification.

It will be quite important for developers to hold themselves accountable for keeping these TSDoc comments updated, non-redundant, useful, etc.

### Requirements

- [ ] Determine mechanism of generating specifications from TSDoc comments
- [ ] Consider how specifications can be the most readable (e.g. keeping specs separated by domain, how to display / organize)
- [ ] Consider how to encourage or instill developer accountability for TSDoc comments' quality

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
