### ISSUE TITLE
[Task]: Setup integration with GitHub Pages

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2486]
### Task description

We will need to use some type of hosting service to actually provide access to the documentation for everyone. It will likely be easiest to use GitHub [Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages). 

How this hosting works will affect the process by which we update the documentation, so it's also important to establish a simple method to propose documentation changes.  

### Requirements

- [x] Ensure chosen hosting platform can accommodate our needs
- [ ] Establish process for updating documentation (loosely or otherwise) - document in the handbook itself!
- [x] Create automated process (like via GitHub [Actions](https://docs.github.com/en/actions)) for generating and serving the static content
- [x] Configure website as needed (e.g. domain, security) - minimal as is purely statically generated and hosted site via GH pages

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
