### ISSUE TITLE
[Task]: Organization placement for all documentation

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2487]
### Task description

There are a few different places where documentation will live, and it makes sense for specific pages to be in the wiki vs let's say the handbook. It's also worth noting that in the future when Firefly web is in a more finalized place, we will need to consider the IOTA wiki for external developers.

#### Organization
The following lists indicate what documentation will live in what location. The GitHub will be the primary source of truth, which is relevant for duplicated documentation like developer setup or the glossary. If possible it's better to just link and reference documentation rather than duplicating it.

An important question to be asking is what documentation is intended for internal devs vs external devs / users. 

##### Firefly (GH) Wiki
- Home (about, installation, building, contributing, discussing)
- Backlog (epics and milestones)
- Code of Conduct
- Glossary
- Guides
    - Installation
    - Building
    - Contributing (i.e. branching strategy, coding conventions... these will be in handbook but also contributing could mean filing issues)
    - Issues

##### Firefly Handbook
- Glossary
- Guides
    - Branching Strategy
    - Coding Conventions
    - Developer Setup (aka building guide + more?)
    - Developer Tips
    - Testing
- SOPs
    - Issue Management (Triaging?)
    - Release Management
    - Security Incident Response

##### IOTA (Docusaurus) Wiki
- Deep Links (this is a wider ecosystem thing though... start off in Firefly section?)

### Requirements

- [x] Determine pages for wiki and handbook
- [x] Link relevant docs to the handbook from the wiki (and vice versa?)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
