### ISSUE TITLE
[Task]: Document code organization

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2489]
### Task description

Currently all documentation regarding _how_ we should organize our code is inside the coding conventions, although this is not the ideal or even correct place for this information; it should live in its own place.

### Requirements

- [ ] Organize separate page for all code / module organization information, removing it from the coding conventions

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
