### ISSUE TITLE
[Task]: Read smart contract documentation

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2492]
### Task description

There is abundant documentation to read about smart contracts and important standards within the space. We must read!

### Requirements

- ERCs
    - [ ] [20](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/)
    - [ ] [721](https://ethereum.org/en/developers/docs/standards/tokens/erc-721/)
    - [ ] [777](https://ethereum.org/en/developers/docs/standards/tokens/erc-777/)
    - [ ] [1155](https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/)
- ISCP
    - [ ] [Whitepaper](https://files.iota.org/papers/ISC_WP_Nov_10_2021.pdf)
    - [ ] [Wiki](https://wiki.iota.org/smart-contracts/overview)

### Acceptance criteria

The above documentation has been read by...
- [ ] @kraftjs 
- [ ] @maxwellmattryan 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
