### ISSUE TITLE
[Task]: Rename account on mobile

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2511]
### Task description

The main menu has an option to rename Profile, where the folder is renamed. Will use the Capacitor plugin `SecureFilesystemAccess` for that feature.
Currently on the Capacitor Bindings plugin we haven't an option to get the profile folder name and create it, we must do this too.

### Requirements

- [x] Implement `renameProfileFolder` on `CapacitorApi.ts`
- [x] Implement create a specific folder for each profile on Capacitor Bindings plugin for both Android & iOS
- [x] Verify the folder was renamed on device filesystem on iOS
- [x] Verify the folder was renamed on device filesystem on Android

### Acceptance criteria

Upon the folder has renamed the profile will be changed, so we should assume it's done when the profile is successfully renamed in the UI.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
