### ISSUE TITLE
[Task]: Create more alignment across team development environments

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2528]
### Task description

The development environments vary across the team, which can cause questions and friction to arise when dealing with environment-specific stuff. This task aims to in general either create more alignment across these aspects or simply document them as a resource.

### Requirements

- [x] Document more information around node versioning
- [ ] Document more information about Electron / Capacitor
- [x] Document more info for setting up Ledger devices (e.g. Linux users have to [enable `udev` rules](https://support.ledger.com/hc/en-us/articles/115005165269-Fix-USB-connection-issues-with-Ledger-Live?support=true))

### Acceptance criteria

Meets the above (TBD) requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
