### ISSUE TITLE
[Task]: Migrate documentation to handbook

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2530]
### Task description

There's lot of documentation that needs to be moved over to the handbook.

### Requirements

Move the following documents over to the handbook:
- [x] Guide: Branching Strategy
- [x] Guide: Coding Conventions
- [x] Guide: Developer Setup
- [x] Guide: Developer Tips
- [x] Guide: Testing
- [x] SOP: Issue Management
- [x] SOP: Release Management
- [x] SOP: Security Incident Response

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
