### ISSUE TITLE
[Task]: Polish documentation

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2531]
### Task description

In addition to simpy migrating the documentation over, it is important to put effort in making sure that they're all up-to-date, easy-to-read, etc.

### Requirements

- [x] Remove redundant information from GH wiki
- [ ] Improve documentation in handbook
- [ ] Improve documentation in GH wiki
- [x] Ensure that necessary docs are also in GH wiki (the externally facing ones)
- [x] Change `NOTE` or `CAUTION` text to use emojis (consistent with rest of docs)
- [ ] Add more landing page fluff
- [x] Add section on quickly changing mnemonics for Ledger simulator (easier than resetting via device)
- [x] Use proper SVG icon for handbook logo
- [x] Make sure all relevant URLs use relative paths rather than full address

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
