### ISSUE TITLE
[Task]: Add markdown linting to repository

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2532]
### Task description

To increase maintainability of documentation, it will be quite nice to have a markdown linter that ensures consistent writing style and formatting.

### Requirements

- [x] Determine tool to lint markdown files (checkout [this](https://github.com/funbox/markdown-lint))
- [x] Determine how to use tool in editing process (install with Yarn, lint on commit, etc.)
- [ ] Integrate tool with actual process

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
