### ISSUE TITLE
[Task]: Add data / nonce signing for Ledger devices

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2537]
### Task description

One of Firefly web's functionalities is to sign data / nonces for things like gaining access to websites, posting content, etc. We will need to make sure that Ledger devices support this capability (as well as Stronghold).

### Requirements

- [ ] Consider user flow for signing data / nonces (what should the inputs and outputs of the functionality be? how is the data formed? etc.)
- [ ] Determine necessary technical changes needed for the app (can reference Stronghold)
- [ ] Organize and document changes then give to @pmaxuw

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
