### ISSUE TITLE
[Task]: Improve software profile UTXO Consolidation UX 

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#2539]
### Task description

When a user has > 100 UTXOs on an address, wallet-rs will automatically consolidate these funds by sending messages from the address to the address. However there is no prompt or indication of this happening for the user. Proof of Work happens in the background and the user may be left wondering why the app is using resources and "syncing".

Consolidation transactions are not marked either. They will appear in the activity log as a transfer to yourself, which again is confusing for the user.

### Requirements

- [ ]  Design new prompts and flows for when consolidation needs to occur
- [ ]  Change the activity log to mark consolidation transactions
- [ ]  Implement new UX

### Acceptance criteria

- [ ] Consolidation occurs in a predictable way. The user is informed of what is going on.
- [ ] Once consolidation is complete, the activity log shows a record of the activity.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Dr-Electron** [comment]
The UX could be improved easily in the Shimmer version by catching the error and giving a prompt of possibly doing a consolidation.
Most people won't find/know about the manual consolidate functionality
