### ISSUE TITLE
[Task]: Add UTXO consolidation for Ledger profiles

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#2540]
### Task description

UTXO consolidation happens automatically on software profiles, however Ledger profiles do not have this option. Wallet-rs can emit an event when consolidation is needed on Ledger. We can utilise this to create a simple manual flow for Ledger fund consolidation (in which the user needs to manually sign each consolidation on the Ledger device).

Bear in mind the max number of UTXOs for a Ledger Nano S is ~15 and Ledger Nano X is more (check with @shufps) so the consolidation function should be triggered when you surpass the max (ideally depending on which device is connected).

### Requirements

- [ ] Expose Ledger profile consolidation event from wallet-rs
- [ ] Use existing Ledger transaction confirmation popups
- [ ] Align the UX with #2539

### Acceptance criteria

- [ ] A user is prompted to consolidate their funds when they have surpassed the max number of UTXOs their device can handle in one message.
- [ ] The UX matches the same process for software profiles
- [ ] The activity log indicates that a consolidation has occurred

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
