### ISSUE TITLE
[Task]: E10.M2 - Product Design Specification

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2541]
### Task description

Create the product design specification for `E10.M2 - Shimmer profiles with single address`.

### Requirements

- [x] Purpose
- [x] Business Requirements
- [x] User Requirements
- [x] Product Requirements
- [x] User Flows
- [ ] Wireframes

### Acceptance criteria

Approval by product owner?

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
