### ISSUE TITLE
[Task]: E10.M4 - Product Design Specification

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2545]
### Task description

Create the product design specification for `E10.M4 - Support ledger profiles`.

### Requirements

- [ ]  Purpose
- [ ]  Business Requirements
- [ ]  User Requirements
- [ ]  Product Requirements
- [ ]  User Flows
- [ ]  Wireframes

### Acceptance criteria

Approval by product owner?

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
