### ISSUE TITLE
[Task]: Add path alias usage in `mobile`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2549]
### Task description

There is currently existing support for path aliases in `packages/mobile` but they're not being used yet (reason is that the alias will change once the majority of the code has been re-organized). 

### Requirements

- [ ] Use path aliases for any shared library code in `packages/mobile`

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
