### ISSUE TITLE
[Task]: Reduce Node.js bindings size on Linux when built with debug info

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2568]
### Task description

We need to build the Node.js bindings with debug information for better stacktraces in Sentry, but they are extremely large on Linux (over 580 MB). After some Googling, it seems like Rust may include debug info for dead code (https://github.com/rust-lang/rust/issues/56068) and the ability to [split the debug info to a separate file](https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo) is only available on the `nightly` toolchain. Since we can't do much about those, we can try other approaches in the meantime, such as limiting the amount of debug info emitted (see https://github.com/benesch/materialize/commit/02cc34cb7c7d9f1b775fe95e1697b797d8fa9b6d#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542 and [`rustc` docs](https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo))

### Requirements

- [ ] Reduce Linux binary size
- [ ] Ensure stacktraces in Sentry are still adequate

### Acceptance criteria

Above requirements are satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
Changing `debug` from `true` (full debug info) to `1` (line debug info) reduced size by 41% (from 579 MB to 340 MB), but let's see if we can get it to be smaller

**Comment by cvarley100** [comment]
Any more thoughts on this @rajivshah3?

**Comment by rajivshah3** [comment]
> the ability to split the debug info to a separate file is only available on the nightly toolchain

Not sure why I didn't think about doing it manually with the GNU binutils 😅  Let's see if Sentry will symbolicate errors if we do it that way
