### ISSUE TITLE
[Task]: E10.M6 - UX Design

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2581]
### Task description

Design the UX/UI for `E10.M6 - Support native NFTs` according to the Product Design Specification.

### Requirements

Documented in the Product Design Specification for this milestone.
- [x] #2605
- [x] #2606
- [x] #2607
- [x] #2608
- [x] #2609
- [x] #2610
- [x] #2611
- [x] #2612
- [x] #2613

### Acceptance criteria

Approved by Product Owner / Epic Owner / Firefly Lead.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by valeriegrappendorf** [comment]
Test
