### ISSUE TITLE
[Task]: NFT spec and planning 

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2582]
### Task description

This is an ongoing task for the NFT epic

### Requirements

- [ ] Plan milestones, features, and tasks
### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
We need to look at this as part of M3 to consider loading data and the security considerations for this.
