### ISSUE TITLE
[Task]: Document / polish Git guides

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2592]
### Task description

An important part of the developer workflow is being able to smoothly use Git and integrate into our existing flow. 

### Requirements

- [ ] Document branching strategy
- [ ] Document commit strategy
- [ ] Polish pull request strategy

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
