### ISSUE TITLE
[Task]: Document developer tools

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2593]
### Task description

We should try and optimize our environments whenever necessary, whether this includes various CLI tools, browser extensions, notification managers, etc. 

### Requirements

- [ ] Write section on Gitify
- [ ] Write section on better pull request extension (although GH file tree beta is :fire:)
- [ ] ...

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
