### ISSUE TITLE
Implement `wallet.rs` NodeJS bindings directly

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2594]
### Task description

We will have to have a hybrid implementation for a period of time while we are phasing out the original actor system bindings for IOTA functionality and beginning to use the NodeJS bindings directly for Shimmer functionality.

### Requirements

- [ ] Ensure that new system allows for older system to be migrated over cleanly / easily
- [ ] Ensure that new system is mirrored between mobile and desktop
- [ ] Ensure Ledger functionality is maintained with new bindings

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
This sounds like it could involve significant changes, so maybe we should do it at the same time as the Neon update (#2456)

**Comment by Tuditi** [comment]
Due to the change of approach (having 2 apps), the requirements above are not  necessary anymore. The new functionality will be introduced in a different app than the system relying on actors.
