### ISSUE TITLE
Design abstraction layer for library (IOTA vs. Shimmer)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2595]
### Task description

To cleanly bring Shimmer into Firefly, we need to create a layer of abstraction between the bindings and the business logic.

Ideally this separation should be kept lower-level as any higher level business logic or app functionality should NOT have to be aware of the fact this separation exists.

### Requirements

- [ ] Design interfaces for new `wallet.rs` APIs
- [ ] Determine exact point / layer where API interfaces should be implemented
- [ ] Determine clean way of handling existing functionality for Shimmer that is non-existent for IOTA profiles

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
