### ISSUE TITLE
[Task Tracker] Update all existing settings to work with stardust / new api

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2597]
We need to make sure all existing settings work and if not update them with new app logic and UI.

**General**
- [x] Theme
- [x] Language
- [x] Currency
- [x] Notifications
- [x] Network Status
- [x] Change profile name

**Security**
- [x] #3426
- [x] Automatic lock
- [x] #3413
- [x] #3411
- [ ] Moved as this will not be complete in the milestone as its not provided by wallet.rs -> #3412
- [x] #3318

**Advanced**
- [x] #3319
- [x] #3393
- [x] #3287
- [x] Hidden wallets
- [x] Error log
- [x] Crash reports
- [x] Diagnostics

**Help & Information**
- [x] Documentation
- [x] FAQ
- [x] Discord
- [x] Report an issue

**Comment by maxwellmattryan** [comment]
I think while we're adjusting the settings, we could potentially break it into five:
- General - the app-wide settings, i.e. theme, language, notifications (alt. these could be per-profile), etc.
- Profile - per-profile settings like currency (alt. could be general setting since that is more in line with language), network config, lock screen timeout, network statistics, delete profile (alt. could be security setting), hidden wallets
- Security - export backup, automatic lock, change pincode / password
- Advanced - Network config, deep links, crash reports, error log, balance finder
- Help / Info - docs, faq, discord, report an issue
