### ISSUE TITLE
[Task]: Design new profile data structure

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2598]
### Task description

With another layer added to profile data, it is worth looking at how we structure our profile data, especially when it comes to restoring them from a Stronghold backup.

### Thoughts

- Needs to include `role` (i.e. `Basic`, `Developer`)
- Needs to include `security???` from `type` (i.e. `Stronghold`, `Ledger`)
- Needs to include `protocol` (i.e. `IOTA`, `Shimmer`)
- Reduce unnecessary fields / bloat from data structure

### Requirements

- [ ] Design ideal profile data structure
- [ ] Consider migration implications of older profile data (another involved migration process? just a simple function call?)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
