### ISSUE TITLE
[Task]: Document Sentry error reporting guide

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2599]
### Task description

There is no documentation for how to quickly test that Sentry functionality works. This can come in handy later when someone might need to test specific functionality, etc.

### Requirements

- [ ] Document quick process for locally enabling and testing Sentry

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
