### ISSUE TITLE
[Task]: Update bug report form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2630]
### Task description

We should update the bug report form to make gathering information from bugs easier, and in a standard way. We should also add a field to distinguish between mobile and desktop bugs.

### Requirements

- [ ] Update bug report form

### Acceptance criteria

Form is merged and used for the bug report form in the firefly repos.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
