### ISSUE TITLE
[Task]: Add linting and formatting to native code for mobile

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2635]
### Task description

- Use tool like [`google-java-format`](https://github.com/google/google-java-format) for formatting Java code
- Use tool like [SwiftLint](https://github.com/realm/SwiftLint) for formatting and linting Swift code
- Use tool for linting Java code
- Enforce with CI

### Requirements

- [ ] Java and Swift code formatted and linted
- [ ] Enforced with CI

### Acceptance criteria

All above requirements satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@rajivshah3 now that the native code is not in firefly anymore, I would suggest to open this issue to https://github.com/iotaledger/iota-sdk 🙏🏼
