### ISSUE TITLE
[Task]: Automate changes to package.json for alpha and beta releases

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2636]
### Task description

#2296 introduced alpha and beta releases, but one pain point is that a script needs to be manually run in order to change the `productName` in the package.json. This `productName` is used for multiple purposes, namely for determining where app data is stored. Failing to change the `productName` results in an alpha or beta version reading from the app data used for prod. This change needs to be made before bundling the JS code (`yarn build:<stage>`), remain for compiling the packaged app (`yarn compile:<stage>:<os>`), and preferably be reverted back afterwards so it is not checked into Git.

### Requirements

- [ ] Automate changes to package.json

### Acceptance criteria

Above requirements satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
