### ISSUE TITLE
[Task]: Test ledger

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2639]
### Task description

- Transaction
- Staking

### Requirements

TBD

### Acceptance criteria

- [ ] Transaction working
- [ ] Staking working

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
