### ISSUE TITLE
[Task]: Modify export success toast to open folder on click

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2649]
### Task description

When exporting a file, whether that is transaction history or a backup, it would be useful if the user could open the files location from inside firefly. We should add a mechanism to the success toast to do this.

### Requirements

- [ ] Add button to toast
- [ ] Add open button to export success toasts
- [ ] Open correct folder when open button is clicked

### Acceptance criteria

PR approved and merged.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
For desktop, the appropriate API is [`shell.showItemInFolder`](https://www.electronjs.org/docs/latest/api/shell#shellshowiteminfolderfullpath)
