### ISSUE TITLE
[Task]: Upload debug files from Windows to Sentry

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2650]
### Task description

Stacktraces for crashes from the Rust backend occurring on Windows cannot be symbolicated since the debug information is located in a PDB file, separate from the library itself (the path to it may be `D:\a\firefly\firefly\packages\backend\bindings\node\native\target\x86_64-pc-windows-msvc\release\deps\node_neon.pdb`). We need to upload this file to Sentry when building the bindings for a release so that stacktraces can be symbolicated.

### Requirements

- [x] Determine the location of the PDB file
- [ ] Use the [Sentry CLI to upload it to Sentry](https://docs.sentry.io/product/cli/dif/)
- [ ] Add this to GitHub Actions

### Acceptance criteria

Above requirements are completed

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
