### ISSUE TITLE
[Task]: Adjust icons used for developer instance

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2655]
### Task description

Currently the icons we use (particularly in the developer instance of Firefly) are not consistent. We should be using the alpha icon here.

### Requirements

- [ ] Ensure the alpha version icon is used in the following places:
    - Taskbar icon
    - Top of dashboard sidebar
    - About window
    - App update window 
    - App updater icon in dashboard security pane (supposedly irrelevant as it will be removed soon anyway due to the single account refactor)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
