### ISSUE TITLE
[Task]: Change URL for reporting an issue 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2656]
### Task description

Currently the URL to "Report an issue" within Firefly leads users to the open list of issues, whereas it would be more helpful to lead directly to either the [issue options](https://github.com/iotaledger/firefly/issues/new/choose) or the [bug report form](https://github.com/iotaledger/firefly/issues/new?assignees=&labels=bug+report&template=bug_report.yml&title=%5BBug+report%5D%3A+).

### Requirements

- [x] Change link for any relevant areas in the app

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
