### ISSUE TITLE
[Task]: Design popup on staking tab for notifying users about end of Shimmer and new periods for ASMB

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2664]
### Task description

We need to notify the user when a new staking period is starting. For this I suggest that we keep the badge to bring the users attention to the staking tab; and then we can display an informational popup.

This will explain to the user that the Shimmer staking has ended and the Assembly is continuing for another period.

### Requirements

- [x] Popup on the staking tab
- [x] Popup explains that another staking period is / has started for assembly

### Acceptance criteria

Approved by milestone product lead.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
