### ISSUE TITLE
[Task]: Modify design of Shimmer tile on staking tab to show end result only

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2665]
### Task description

We should keep the existing format for the staking tab, but we should modify the shimmer tile to show that this staking period has ended and the total rewards earned.

### Requirements

- [ ] Show end state
- [ ] Show total rewards

### Acceptance criteria

Approved by milestone product lead.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
