### ISSUE TITLE
[Task]: Fetching and caching SMR/ASMB staking period JSON files

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2666]
### Task description

We need a system / mechanism to download the JSON files containing the end results of the staking periods for Shimmer and Assembly (i.e. [Assembly](https://raw.githubusercontent.com/iotaledger/participation-events/b6d04e17de570aa5b633ee18b1087b2f9bd48601/results/staking/assembly_01.json), [Shimmer](https://raw.githubusercontent.com/iotaledger/participation-events/886597c7372c406ef6a8bc4df165619da0d82af4/results/staking/shimmer.json)).

### Requirements

- [x] Add logic to fetch JSON files from GitHub
- [x] Add logic to cache results locally (cache only relevant output addresses, avoiding caching the entire file)
- [x] Add logic to fetch correct files based on current period (i.e. if period 3 then fetch files for 1 and 2)
- [ ] Ensure that freshly created profiles are fully loaded before querying / caching staking results

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
