### ISSUE TITLE
[Task]: Modify design of Assembly tile on staking tab to show previous and current reward information

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2667]
### Task description

We should keep the overall format of the staking tab the same as before. But we need to modify the designs of the Assembly tile to show the total previous rewards earned for the previous periods and the rewards for the current period.

### Requirements

- [ ] Show period number?
- [ ] Show time remaining
- [ ] Show previous rewards
- [ ] Show rewards for current period

### Acceptance criteria

Approved by product lead for milestone.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
