### ISSUE TITLE
[Task]: Modify design of staking manager flow to only allow Assembly

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2668]
### Task description

Now that the first period of staking has ended, in future staking periods on IOTA the user is only going to be able to stake assembly. So we need to modify the staking manager flow to only show assembly staking.

### Requirements

- [ ] Remove shimmer staking from staking manager.

### Acceptance criteria

Approved by product lead for milestone.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
