### ISSUE TITLE
[Task]: Modify staking rewards calculation for multiple periods

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2669]
### Task description

We need to adjust the logic for calculating how many airdrop rewards have been accumulated.

### Requirements

- [x] Use staking result JSON files to make this calculation (the node will not have the information for previous periods)
- [x] Add logic to count rewards in a single period
- [x] Add logic to count total accumulated rewards across all periods

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
