### ISSUE TITLE
[Task]: Modify logic around minimum rewards

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2670]
### Task description

We need to adjust logic around minimum rewards, making sure it's per-period and per-token.

### Requirements

- [x] Ensure minimum reward logic is per-period and not across all periods (if results from previous periods are in JSON file then they're confirmed to be airdropped those funds)
- [x] Ensure minimum reward logic is per-token and not across both tokens (only one Shimmer period, so use JSON file)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
