### ISSUE TITLE
[Task]: Ensure smooth staking period transitions

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2671]
### Task description

We need to make sure that transitions to new staking periods (for Assembly) will go smoothly and users have a nice experience.

### Requirements

- [x] Fetch and cache JSON file for recently ended staking period and increment period count
- [x] Figure out best way of notifying users that a new staking period has started and they must re-stake their funds

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
