### ISSUE TITLE
[Task]: Fix rename account issues for 1.4.0

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2674]
### Task description

We have several issues reported after renaming accounts in the 1.4.0-beta, so we should aim to fix these before release.

### Requirements

Fix:
- [ ] #2643 
- [ ] #2644 
- [ ] #2655 

### Acceptance criteria

All issues resolved and merged into release/1.4.0

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
