### ISSUE TITLE
[Task]: Fix Ledger staking issues in single account view

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2678]
### Task description

Staking for Ledger profiles is currently hanging forever once a staking transaction has been signed.

### Requirements

- [x] Fix transaction cancelling toast notifications
- [x] Fix hanging / infinite spinner problem

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
