### ISSUE TITLE
[Task]: Fix popup warning for unstaking via regular transaction

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2679]
### Task description

Despite having the staking events ended, trying to send a regular transaction results in the popup warning for unstaking funds showing up.

### Requirements

- [x] Ensure that if staking events have ended that this transaction popup **does NOT** show up

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
