### ISSUE TITLE
[Task]: Disallow account switching while certain actions are ongoing

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2688]
### Task description

Currently, it is possible to switch accounts during some actions which while this doesn't break the UI it does cause inaccurate information to be displayed.

### Requirements

- [x] Disallow account switching while syncing account (not entirely necessary?)
- [ ] Disallow account switching while staking / unstaking
- [x] Disallow account switching while sending transaction

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
