### ISSUE TITLE
[Task]: Fix UI state / reactivity when cancelling participation transactions (w/ Ledger)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2689]
### Task description

Currently when unstaking and cancelling the transaction, the zen guy animation on the staking dashboard has already changed to the "not staking" animation. Then afterwards if you actually sign and broadcast the transaction to unstake then the staking manager state doesn't update correctly.

### Requirements

- [x] Fix logic so that zen guy only changes animation if unstaking / staking transaction is signed and broadcasted
- [x] Fix logic so that staking manager UI updates accordingly even if transaction was cancelled once before 

### Acceptance criteria

Meets the above the requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
