### ISSUE TITLE
[Task]: Fix dashboard tile when no address has been generated yet (Ledger)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2690]
### Task description

Currently there is weird spacing whenever the user hasn't generated a receive address with a Ledger device.

![Screenshot from 2022-03-30 18-57-33](https://user-images.githubusercontent.com/44885822/160949833-a41cf360-4d6b-44d3-9db9-7749e9fb9c53.png)

### Requirements

- [x] Fix the awkward amount of whitespace between the top of the tile and the "Generate address" button

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
> how do you think it should look like?

I think it should be at the bottom, which is how it was before. The screenshot below is from 1.3.3.

![Screenshot from 2022-03-31 08-47-39](https://user-images.githubusercontent.com/44885822/161070796-b219e6f3-cebb-48a6-bc72-c06d665faca4.png)
