### ISSUE TITLE
[Task]: Create notification popup for new staking period

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2704]
### Task description

We should notify the user on the staking tab that there is a new staking even starting or has started. We can do this by adding adding a badge to the staking tab navigation.

### Requirements

- [ ] Create notification popup.
- [ ] Add red badge to staking tab icon if the user opens the app and a new period has been added.
- [ ] Add logic to open the popup when the user first opens staking tab after new period is added.

### Acceptance criteria

PR approved and merged into develop.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
