### ISSUE TITLE
[Task]: Refactor `participation` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2707]
### Task description

The current state of the `participation` is close to the coding conventions, but not quite fully there. 

### Requirements

- [ ] Adjust current `participation` module to coding conventions
- [ ] Add necessary constants for staking periods

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
