### ISSUE TITLE
[Task]: Add staking caching logic to balance finder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2708]
### Task description

We need to be sure that if new addresses / funds are found with the balance finder that staking results are also force updated.

### Requirements

- [ ] Add behind-the-scenes logic to balance finder for forcing cache update of staking results (only if new addresses / funds are found)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
