### ISSUE TITLE
[Task]: Polish for E10.M1 Single account view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2713]
### Task description

Now that single account functionality has been implemented we should polish this as much as possible before it is released.

### Requirements

List of issues to be resolved
- [x] #2732
- [x] #2734
- [x] #2735
- [x] #2736
- [x] #2737
- [x] #2738
- [x] #2739
- [x] #2740
- [x] #2741
- [x] #2742
- [x] #2743
- [x] #2744
- [x] #2745
- [x] #2746
- [x] https://github.com/iotaledger/firefly/issues/2757
- [x] #2774
- [x] #2775
- [x] #2805
- [x] #2806
- [x] #2807
- [x] #2808
- [x] #2809
- [x] #2810
- [x] #2823
- [x] #2824
- [x] #2841
- [x] #2842
- [x] #2843
- [x] #2853

### Acceptance criteria

All above issues resolved and merged into develop.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
