### ISSUE TITLE
[Task]: Improve Sentry error reports

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2718]
### Task description

We should add more metadata to Sentry reports from the backend, such as:
- Whether the account is using Stronghold or a Ledger

### Requirements

- [ ] Above metadata is added to backend reports

### Acceptance criteria

Above requirements are satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
