### ISSUE TITLE
[Task]: Report backend errors to respective app in Sentry

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#2719]
### Task description

Currently, errors from the backend are being reported to a `firefly-backend` project in Sentry. This makes issues harder to debug since they are separate from the issues reported on the JS side in `firefly-desktop` and `firefly-mobile`. Furthermore, Sentry uses the `Cargo.toml` version (0.1.0) for all errors when it should be using the version of the desktop/mobile app.

### Requirements

- [ ] See if desktop and mobile projects will process both JS and Rust errors
- [ ] Send errors to the desktop or mobile project instead of backend
- [ ] Use the desktop or mobile version instead of the `Cargo.toml` version

### Acceptance criteria

Above requirements satisfied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
