### ISSUE TITLE
[Task]: Add complete and new event banners to staking airdrop panels

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2729]
### Task description

We need to add a banner to each of the airdrop staking panel. They will have three states:

- No banner
- Complete banner
- New event banner

### Requirements

- [ ] Add banner and variants to airdrop panel - @begonaalvarezd 
- [ ] Add conditional logic to show banner - @nicole-obrien 

### Acceptance criteria

PRs approved and merged for the above requirements

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
