### ISSUE TITLE
[Task]: Adjust `StakingManager` popup to inform about single account refactor

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2757]
### Task description

With the single account refactor, it may be confusing for users trying to manage their stakes.

### Requirements

- [x] Add info section about single account change
- [ ] ~~Add "More info" link~~
- [x] Ensure dark mode styling is alright
- [x] Create re-usable component for new addition (see `NewStakingPeriodNotification.svelte`)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
