### ISSUE TITLE
[Task]: Adjust `StakingInfo` tile per new designs

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2758]
### Task description

The designs have changed for the `StakingInfo` tile.

### Requirements

- [x] Change tile background to white
- [ ] :x: Update zen guy animations for different states
- [x] Add explanatory text from previous `StakingIndicator` lozenge (handle all edge cases)
- [x] Remove unneeded locale entries
- [x] Ensure dark mode styling is alright
- [ ] :x: Update "read more" URL for new blog post (?)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
