### ISSUE TITLE
[Task]: Modify design of `StakingAirdrop` component for multiple periods

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2759]
### Task description

Now that we have multiple periods we need to match the implementation to the new designs, so that we can show the total rewards for all periods and the new rewards for current period.

### Requirements

- [ ] Add total airdrop reward to tile
- [ ] Only show the current rewards and duration if there is a period on going
- [ ] Only show staking indicator if the event is in commencing or holding

### Acceptance criteria

PR approved and merge that achieves above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
