### ISSUE TITLE
[Task]: Adjust `StakingConfirmation` popup per new designs

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2760]
### Task description

The designs for the `StakingConfirmation` needs to be adjusted per the new design changes.

### Requirements

- [ ] Remove Shimmer staking choice
- [ ] Remove notion of checkboxes; Assembly tile should already be "checked"
- [ ] Action button should say "Next"

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
