### ISSUE TITLE
[Task]: Polish for E6.M2 Continued staking IOTA for ASMB

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2769]
### Task description

There are some things within the new staking changes that require polishing.

### Requirements

- [x] #2729 
- [x] #2804
- [x] #2830
- [x] #2831
- [x] #2825
- [x] https://github.com/iotaledger/firefly/issues/2836
- [x] #2876
- [x] #2871 
- [x] #2870
- [x] #2900
- [x] #2906
- [x] #2931 

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
🏁
