### ISSUE TITLE
[Task]: Add popup and arrow to explain new single account view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2779]
### Task description

As we have moved from single account the first time a user logs in to each profile after this update we should show a modal to explain this to the user. And a big arrow pointing to the account switcher.

### Requirements

- [x] Add modal on first login to each profile after update
- [ ] Add animation to modal
- [x] Add big arrow point to the account switcher

![Wallet](https://user-images.githubusercontent.com/89913787/162186043-4dc806f8-15f2-44d0-89b8-e13d70eddc2e.png)

### Acceptance criteria

Implemented the design and PR approved and merged.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
