### ISSUE TITLE
[Task]: Don't close profile menu when entering password for unlocking stronghold

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2781]
### Task description

Now that the stronghold unlock toggle has moved to the profile menu, we need to keep the profile menu open when the user is inputting their password to unlock stronghold after clicking the toggle. Otherwise it feels odd when the you can not see the results of entering the password.

### Requirements

- [ ] prevent profile menu closing when entering password popup is on the screen

### Acceptance criteria

PR approved and merged, given menu doesn't close when the password popup is still open.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
