### ISSUE TITLE
Add new zen guy staking animations

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2802]
### Task description

We need to update and add the zen guy animations.

### Requirements

- [ ] Modify file number enum with new animations and states
- [ ] Replace old / add new zen guy animations as necessary

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Closing because we have another one tracked in the polish task 🤦‍♀️
