### ISSUE TITLE
[Task]: Fix missing duration arguments for `StakingInfo` locale

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2815]
### Task description

Sometimes the duration arguments aren't being supplied / determined correctly causing the text to appear `{duration} of staking left`.

### Requirements

- [x] Fix the conditional that determines if user is staking (so that arguments are constructed correctly)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
