### ISSUE TITLE
[Task]: Add a popup to view profile ids and folders to settings / OS menu

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2826]
### Task description

Now that we have renamed the folders for profiles, from the profile name to the profile id. We should provide a way for the user to view the profile ids for all the profiles. We can also provide a link to open the __storage__ folder directly.

### Requirements

- [ ] Add popup to show profile ids for each profile
- [ ] Add link to open __storage__ folder
- [ ] Add link to open popup to settings page
- [ ] Add link to open popup from the OS menu

### Acceptance criteria

Above requirements approved and merged in a PR

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
