### ISSUE TITLE
[Task]: Gather and merge in translations for 1.5.0

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2828]
### Task description

We should re-enable translations on the dev branch and merge these in for 1.5.0.

### Requirements

- [x] Enable translations
- [x] Gather translations via posting in translation thread in discord
- [ ] Merge into develop

### Acceptance criteria

Core translations are at 100% and merged into develop.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
@rajivshah3 Reopened as we still need to merge translations back in when ready.
