### ISSUE TITLE
[Sub Task]: Update `wallet.rs` revision and event IDs for next staking period

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2829]
### Task description

We need to add the event IDs for the next staking period and update the `wallet.rs` revision accordingly.

### Requirements

- [ ] Update to correct `wallet.rs` revision
- [ ] Add Assembly event ID to constants file
- [ ] Set Shimmer event ID to empty string in constants file
- [ ] Update constants for previous and current period numbers
- [ ] Update constants for Assembly staking start date (should be April 22nd, not 19th)

### Acceptance criteria

PR achieving requirements is approved and merged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
