### ISSUE TITLE
[Task]: Warn users not to use unlock conditions when sending to an exchange

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#2834]
### Task description

Exchanges shouldn't need to support fancy unlock conditions or NFTs or dust. It will take them more time to implement Shimmer and IOTA Stardust. We should therefore warn users not to send to an exchange address if they have any of these things selected during send.

### Requirements

- [ ] Warn users when they have certain conditions selected not to send to an exchange address

### Acceptance criteria

Ensure the warning covers all relevant cases

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Should discuss with UX. We are going to have a million things to warn the use about. i.e. unstaking, not reaching minimum rewards, unvoting, and now the potential of sending to an exchange. Seems like an issue for the exchange to warn about. As ultimately it's up to the exchange what they support.
