### ISSUE TITLE
[Sub Task]: Modify design of staking asset tiles per new designs

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2836]
### Task description

The warning icon displayed in the `StakingAssetTile` component is too small and will not get the user's attention.

### Requirements

- [ ] Remove yellow / orange border when the icon is displayed
- [ ] Move warning icon to left of token holdings rather than right
- [ ] Add placeholders for fiat price and holdings in fiat value
- [ ] Change opacity back to 100%

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
