### ISSUE TITLE
[Task]: Single wallet popup shows up on login page

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2837]
### Task description

> I have created a new profile. After this I only accepted the popup and immediately deleted the profile. After this the popup appears on the login page.

### Requirements

- [ ] Make sure the login popup shows up at the right time and under right conditions

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
