### ISSUE TITLE
[Task]: Change monospace font across entire app

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2838]
### Task description

The monospace font we currently use is hard to read for some users.

### Requirements

- [ ] Change the font to [Fira Mono](https://fonts.google.com/specimen/Fira+Mono)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
