### ISSUE TITLE
[Sub Task] Rename `account n` to `wallet n` on account discovery

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2841]
### Task description

There is a lack of consistency in account names when the alias is set automatically (by Firefly and `wallet.rs`).

### Requirements

- [ ] Change locale entry of `general.account` to be "Account" and not "Wallet"
- [ ] Ensure this works for the following scenarios:
    - Creating a new profile 
    - Restoring an old profile (Stronghold- _and_ mnemonic-based methods)
    - Creating a new account
    - Finding a new account

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
