### ISSUE TITLE
[Task]: Run full staking flow with alpha testers

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2848]
### Task description

We need to run through all the staking flows with the alpha testing team prior to release.

### Requirements

- [ ] Create test event
- [ ] Create alpha release
- [ ] Run through all staking flows
- [ ] Confirm remaining issues / lack of issues

### Acceptance criteria

1 full staking flow has been completed with alpha testers, and no issues remain.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
