### ISSUE TITLE
[Task]: Fix back button in onboarding flows

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2851]
### Task description

Currently when restoring from a ledger backup, after you enter a new pin, when you press back it goes back to the ledger migration explanation video. i.e. in a different flow.

### Requirements

- [ ] Ensure the back button in all onboarding flows works as expected
- [ ] Fix any issues with the backbutton

### Acceptance criteria

Back button works as expected

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
