### ISSUE TITLE
[Task]: Pass participation event IDs to `wallet.rs`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2856]
### Task description

Rather than `wallet.rs` hard-coding the official event IDs, they should be passed in by the consumer of the library.

### Requirements

- [ ] Update `wallet.rs` revision
- [ ] Change `getParticipationOverview` such that the event IDs are manually passed in
- [ ] Update `ParticipationOverview` data structure as needed (?)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
