### ISSUE TITLE
[Task]: Use dynamic date for new staking periods rather than placeholder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2860]
### Task description

Currently we are hard-coding the date in the locale files in which the staking period starts. This needs to be dynamic.

### Requirements

- [ ] Change hard-coded date string to be dynamically passed in

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
