### ISSUE TITLE
[Task]: Fix translation strings for ledger device status

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2867]
### Task description

Ledger device status locales use Capital letters at the start of every word we should change this to match design and stay consistent throughout app.

### Requirements

- [ ] Modify locales in en.json for ledger device status.

### Acceptance criteria

No capital letters at the start of every word.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
