### ISSUE TITLE
[Task]: Add new animations for next staking period

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2870]
### Task description

The animations have been updated slightly to reflect that previous airdrops might have contained rewards.

### Requirements

- [ ] Update animations
- [ ] Confirm or update logic for displaying animations

### Acceptance criteria

Correct animations display, PR for this task is approved and merged.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
