### ISSUE TITLE
[Sub Task]: Update text on new staking notification

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2871]
### Task description

We need to update the text on the new staking notification to ensure it makes sense and to keep change the length from 30 to 90 days.

### Requirements

- [x] Confirm the correct text
- [x] Update text in en.json

### Acceptance criteria

Text matches that of which was confirmed, PR approved and merged

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
