### ISSUE TITLE
[Task]: Polish Voting

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2874]
### Task description

- [x] #2699 --> @begonaalvarezd 
- [x] #2879 --> @begonaalvarezd 
- [x] #2880 --> @begonaalvarezd 
- [x] #2881 --> @begonaalvarezd 
- [x] #2996 --> @begonaalvarezd 
- [x] #2997 --> @cvarley100 
- [x] #3004 --> @cvarley100 
- [x] #2411 --> @begonaalvarezd 
- [x] #3009 --> @cvarley100 
- [x] #3014 --> @begonaalvarezd 
- [x] #2882 --> @begonaalvarezd 
- [x] #2998
- [x] #3019 --> @begonaalvarezd 
- [x] #3020 --> @begonaalvarezd 
- [x] #3022 --> @begonaalvarezd 
- [x] #3090
- [x] Reset governance router on governance tab click
- [x] Display indicator on voting tab icon when there is a partial vote (like we do in staking)
- [x] If you vote, close the popup, hover over a tooltip and wait for the vote to complete the tooltip gets stuck open
- [x] Close the vote popup on successful vote/unvote
- [x] #3170
- [x] #3171
- [x] #3173
- [x] #3174
- [x] #3085 --> @begonaalvarezd 
- [x] #3169 --> @begonaalvarezd 
- [x] #3172 --> @cvarley100 
- [x] #3291

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
