### ISSUE TITLE
[Task]: Implement create new stronghold profile flow with new bindings 

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2878]
### Task description

Use the new bindings to mimic the onboarding flow of Firefly. Initially, it should work for Stronghold wallets only.

### Requirements

- [x] Create a new profile with the new bindings

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
