### ISSUE TITLE
[Task]: Implement create new profile with ledger flow with new bindings

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2883]
### Task description

Ensure that the onboarding flow with the new bindings is also possible with ledger and update the code if required.

### Requirements

- [ ] Create a ledger profile with the new bindings.

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
