### ISSUE TITLE
[Sub Task]: Update staking result file URLs

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2911]
### Task description

There are a number of changes we need to make in order to prepare Firefly for release with a new staking period.

### Requirements

- [ ] Change URLs in the Content Security Policy HTML metadata
- [ ] Change participation constants 

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
