### ISSUE TITLE
[Sub Task]: Update old external URLs (i.e. blog post)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2913]
### Task description

We need to update some of the old URLs that are relevant to staking.

### Requirements

- [ ] Change link for new staking blog post

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
