### ISSUE TITLE
[Task]: Fix slow loading of staking page

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2920]
### Task description

We are currently waiting until the accounts are loaded or the user visits the staking tab before we make a request to get the staking events. Additionally we are not updating the assembly or shimmer event state store unless the networkStatus store has been updated.

The network status is polled every 10 seconds, this means we could have a maximum of 10 seconds between updating the event state, making the UI sluggish.

To fix this we need to update this eventState when the participationEvents are changed as well as network status, and we should load the events before or during the initial account sync.

### Requirements

- [ ] Make event state stores derive from updates to participation events store and network status
- [ ] get participation events as soon as dashboard is mounted.

### Acceptance criteria

Staking page loads quickly without change in stakingInfo tab.
PR approved and merged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
