### ISSUE TITLE
[Task]: Sidebar layout and network indicator

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#2928]
### Task description

Update the sidebar layout with the latest design in [figma](https://www.figma.com/file/11KNK4W3RchhHKT4Io4xfx/Shimmer-profile-%5BWIP%5D?node-id=0%3A1)

### Requirements
Design:
- https://github.com/iotaledger/firefly/issues/2577

Development
- [x] Add network logo to sidebar
- [x] Add network indicator popup to network logo
- [x] Remove old network indicator from from sidebar
- [x] Organise layout of sidebar
- [x] Add error badge to network logo if network issues
- [x] Add notification if network issues
- [ ] Set primary and secondary colours based on network

### Acceptance criteria

- [ ] Looks like figma design
- [ ] Network indicator displays the correct info

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
