### ISSUE TITLE
[Task]: Make sure to use `pointer` mouse cursor when hovering on account switcher

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2929]
### Task description

At least on MacOS, the mouse cursor does not change to a pointer when hovering over the icon to open the account switcher dropdown menu.

### Requirements

- [ ] Use `cursor: pointer` on hover state for the account switcher dropdown

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Perhaps this is an issue with Electron. I noticed slack also has this problem. And we have told the code to use pointers, but it just doesn't work.

**Comment by nicole-obrien** [comment]
Think this is fixed now in 1.5. by removing the drag area from content switcher and back button

**Comment by nicole-obrien** [comment]
Nope it wasn't fixed, still think this might be a limitation on Mac. Will move to accessibility milestone.
