### ISSUE TITLE
[Sub Task]: Fix account switcher / top navigation bar on Windows

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2930]
### Task description

There is an issue (specifically on Windows) where the top navigation bar is causing problems for the UI in a few ways:
- The account switcher is not overlaid on the title bar (see [design](https://www.figma.com/file/rrTiOHqpjQ54UGhT38nKy0/Wallet-tab-%5BWIP%5D?node-id=189%3A129876))
- The wallet and staking dashboard have an inconsistency where the tiles are not starting at the same Y position (in the wallet dashboard there is a margin between the account switcher bar and the dashboard tiles whereas the staking dashboard has the tiles right up against the account switcher bar) 
- The profile and network indicator in the sidebar are not pushed against the bottom of the screen, i.e. there's an odd section of whitespace

### Requirements

- [ ] Overlay account switcher on top of the app title bar (see [Electron docs](https://www.electronjs.org/docs/latest/tutorial/window-customization))
- [ ] Make all dashboard views' tiles start at the same Y position
- [ ] Remove odd whitespace between profile button and the bottom of the app screen

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
So some updates on this, is that it isnt anything to do with electron. But we have a custom title bar for windows only and the slot for the rest of the contents is below it.

We should change this so that we have a title bar with styles on all platforms and pages. and We overlay the top nav onto a fixed position.

We would therefore remove the styling from the top nav and it just contain the wallet switcher and backbutton.

cc: @begonaalvarezd @rajivshah3

**Comment by begonaalvarezd** [comment]
This should be fixed by #2947 ?
