### ISSUE TITLE
[Sub Task]: Remove staking animation when staking not detected

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2931]
### Task description

There should be no animation for whenever the participation feature is not detected on a node.

### Requirements

- [ ] Remove the animation when no participation feature exists on node

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
