### ISSUE TITLE
[Task]: Improve the transaction activity tiles 

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2933]
### Task description

Now that we only have one wallet view, we should improve these tiles to give them some context, that was previously there on the profile dashboard view. 

### Requirements

- [ ] Use extended wording for activity tiles
- [ ] use transfer to and transfer from for internal transactions
- [ ] show address truncated with full hrp on external transactions

### Acceptance criteria

PR approved and merged

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
