### ISSUE TITLE
[Task]: Improve wallet switcher by showing balance

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2976]
### Task description

Now that we have moved to a wallet switcher and there is only a single wallet view at anyone time, to make it easier to identify the wallets, we should add the balance to the wallet switcher.

### Requirements

- [x] Design improvements to wallet switcher @jvegis 
- [x] Implement improvements to wallet switcher @nicole-obrien 

### Acceptance criteria

PR approved and merged into develop

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by AdamCroply** [comment]
Yes please <3
![Untitled-1](https://user-images.githubusercontent.com/61834907/164422041-555f0cd9-385e-4ee7-a61f-3cb59bc4ebb8.png)
!
