### ISSUE TITLE
[Task]: Implement bindings for onboarding flows

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2980]
### Task description

TBD

### Requirements

List of api/bindings needed for onboarding:
- [ ] setStoragePassword (Will be handled later, since db encryption is not needed atm)
- [x] setStrongholdPassword
- [x] generateMnemonic
- [x] storeMnemonic
- [x] verifyMnemonic
- [x] backup
- [ ] restoreBackup
- [x] createAccount

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
`restoreBackup` is currently named `importAccounts` on the AccountManager object.
