### ISSUE TITLE
[Task]: Use s3 as backup for retrieving previous airdrop rewards

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2981]
### Task description

We should store a backup of the rewards in S3 incase GH is down when a user tries to cache the rewards

### Requirements

- [x] Store rewards in s3
- [ ] Retry caching of rewards with s3 url if error from GH request

### Acceptance criteria

PR approved and merged

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
