### ISSUE TITLE
[Task]: Allow the user to select IOTA or Shimmer network during onboarding

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2983]
### Task description

As we now have two different network types IOTA and shimmer the user need to select which network they are creating a profile for when creating a profile.

### Requirements

- [x] Modify the profile object interface with network details
- [x] Create UI for selecting network
- [x] Add mainnet / devnet node selection if developer profile
- [x] Add custom node selection if developer profile
- [x] Add functionality to update profile object when network is selected
- [ ] Refactor app logic out of form component into `network` module
- [x] Move confirmation buttons from form component to the popup component where the form is used

### Acceptance criteria

PR approved and merged into `stardust-develop`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Task blocked because needs this PR to be merged https://github.com/iotaledger/firefly/pull/3059
