### ISSUE TITLE
[Task]: Update profile selection and login screens for M2

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2984]
### Task description

Now in stardust version of Firefly the user can create a profile for various networks we should show the user some context around the profile selection and login screen so that they can login to the correct profile.

### Requirements

- [x] Add network icon to profile icon on profile selection and login screen
- [x] Add tooltip for network name on the network icon
- [x] update switch profile arrow to new designs

### Acceptance criteria

PR approved and merged into `stardust-develop`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
