### ISSUE TITLE
[Task]: Make styles of balance panel on wallet and staking tab consistent

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2986]
### Task description

We have some feedback from UX that the balance panels on wallet tab and the staking tab do not have consistent layout or styles. We need to then update these to make them consistent, and UX have provided a design to follwo.

### Requirements

- [ ] Update balance panel styles on wallet tab
- [ ] Update balance panel styles on staking tab

### Acceptance criteria

PR approved and merged

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
