### ISSUE TITLE
[Task]: Change to syncing on a per-account basis

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2987]
### Task description

Currently the application is syncing all accounts at once when a user logs in, which in some cases can take a frustratingly long time if a user has many accounts, many addresses, or both.

#### Technical

- Sync all of the accounts sequentially on login
    - If user switches to account C while A hasn't finished syncing, wait until A is done then begin syncing C (A -> C -> B). 
    - If user switches to account C then switches again to B (while A is still syncing and before C has started), then make sure B syncs before C. 
    - Only sync an account if it isn't already synced or is currently syncing
- Rely on MQTT-based syncing
    - If connection fails, start background syncing
    - If the connection is re-tried and successfully connects later, stop background syncing

The main motivation here is to avoid any situation where the syncing process is held because it's waiting for all accounts to finish syncing; **it should be broken up per account**.

#### Task

- [x] Remove check disallowing users to switch accounts while syncing
- [x] Cleanup existing logic for syncing by...
    - [x] Add `AccountMetadata` type
    - [x] Refactor `updateAccounts` into single function `updateAccount` applied over all of the accounts
    - [x] Rename: `addMessagesPair`, `asyncSyncAccount`, `asyncSyncAccounts`, `getAccountMeta`, `prepareAccountInfo`
    - [x] Breakdown syncing logic into smaller functions in `Wallet.svelte`
- [x] Add logic for only showing sync spinner if current account is syncing (or all accounts)
- [x] Add logic to sync accounts sequentially (plus edge cases) in a basic priority queue
- [ ] :x: Add logic to begin background syncing if MQTT fails
- [ ] Make it so "syncing" is a sub process of staking, voting, etc. and not an explicit part of the flow

### Acceptance criteria

Meets the above (task) requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Duplicate of https://github.com/iotaledger/firefly/issues/2548, we should close 2548 as it has more info here
