### ISSUE TITLE
[Task]: Change logic for persistent profile on logout

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2992]
### Task description

From feedback we should improve the logic around persistent profiles on logout.

### Requirements

- [ ] if the user clicks logout then they are taken to profile selection screen
- [ ] if the system auto logs out, then you are taken to the login screen for that profile
- [ ] if you close the app while logged in, or while on the login screen you are taken to the login screen for that profile on next app start
- [ ] if you close the app on the profile selection you are taken to the profile selection screen on next app start

### Acceptance criteria

Logic meets above requirements, PR approved and merged into 1.5.2 branch

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
