### ISSUE TITLE
[Subtask]: Update voting info tooltips to appear on mouse over

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2996]
### Task description

Currently the voting info tooltips appear on click, they should appear on mouse over

### Requirements

- [ ] Make tooltips show on mouse over
- [ ] Fix anchor dom elements: some tooltips appear in the wrong place

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
