### ISSUE TITLE
[Task]: Make the reward asset tiles reactive to cached reward changes

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3018]
### Task description

Currently the asset tiles are not reactive to changes in the cached reward themselves, meaning that the user has to switch tabs or be actively staking for these to update if they use the balance finder or recover an account.

This is because the asset store is reactive to the `totalRewards` for each airdrop, but these stores are not reactive to changes to the rewards stored in the profile store.

### Requirements

- [x] Make asset tiles reactive to changes in cached rewards

### Acceptance criteria

PR approved and merged into release branch.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
