### ISSUE TITLE
[Task]: E10.M2b - UX Design

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3027]
### Task description
This is the overarching task for UX design on` E10.M2b - Claim Shimmer rewards`. This is to design the flows for users claiming Shimmer rewards when the network launches.

### Requirements
List of discrete design tasks:
- [x] #3029
- [x] #3241

### Acceptance criteria
All design tasks have been complete, and then reviewed and approved by product owner / epic owner.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
- [ ] Test Subtask
