### ISSUE TITLE
[Task]: E10.M2b - Product Design Specification

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3028]
### Task description

This task is to document the requirements for `E10.2b - Claim Shimmer rewards`.

### Requirements

List of discrete requirement tasks:
- [ ] Purpose and scope
- [ ] Business requirements
- [ ] User requirements
- [ ] Product requirements
- [ ] User flows

### Acceptance criteria

All requirements documented and approved by product owner / Firefly owner.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
