### ISSUE TITLE
[Task]: Account switcher temporarily shows `undefined` when switching networks 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3031]
### Task description

When switching networks (i.e. mainnet, devnet) the account switcher temporarily shows "undefined" for a small amount of time.

This is occurring because it is required to delete the profile's account data before restoring under the new network, causing the values to become `undefined`.

### Requirements

- [ ] Use better placeholder for when the value is `undefined`

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
