### ISSUE TITLE
[Task]: Modify developer profile onboarding for Stardust

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3034]
### Task description

We would like to change how the developer makes a profile in the stardust compatible Firefly version, instead of in the onboarding flow where we already click a checkbox for developer profile. The user should only be able to select this flow from the electron menu. So you won't see the option on the name input page.

For alpha or beta builds we just need dev build by default.

### Requirements

- [x] Remove developer profile selection from name page
- [x] Add entry point for developer profile onboarding
- [x] Default to developer profile onboarding if alpha/beta

### Acceptance criteria

PR approved and merged into `stardust-develop`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
