### ISSUE TITLE
[Task]: Implement receive popup for Stardust profiles

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3035]
### Task description

We are moving to popups for most of the user input flows etc. So this is a task to implement the new receive popup as per the designs.

### Requirements

- [x] New receive popup
- [x] Open popup on button click
- [x] Remove old code

### Acceptance criteria

PR approved and merged into `stardust-develop`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
