### ISSUE TITLE
[Task]: Implement basic transaction details popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3037]
### Task description

We are going to be replacing the existing inline transaction details panel with a simplified popup. This will display just the core information as well as some new details such as the new feature blocks. However we initially need to create a component that will display the bare minimum transaction details and then we can add features as they are implemented.

### Requirements

- [x] Move transaction details to new popup
- [x] Remove old code
- [x] Open popup when clicking on a transaction
- [x] Show relevant details as per design

### Acceptance criteria

PR approved and merged into `stardust-develop`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
