### ISSUE TITLE
[Task]: Refactor `Text` component

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3040]
### Task description

With the new stardust designs there is a need for more customisation of the Text and font, we need to modify the text component so that it is more customisable and aligned with the styles in the UX designs; while maintaining backwards compatability.

### Requirements

- [ ] Modify the Text component to increase customisation
- [ ] Align default styles with UX design definitions
- [ ] Add additional font weights

### Acceptance criteria

PR approved and merged into develop

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
