### ISSUE TITLE
[Task]: Enable wallet logging for any and all test builds

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3043]
### Task description

It would be extremely helpful to have wallet logging automatically enabled for alpha and beta builds. This could potentially help quite a lot in finding elusive bugs and errors that don't give a lot of information.

### Requirements

- [ ] Enable wallet logging for `alpha` and `beta` builds
- [ ] Ensure that the log files themselves are reasonably sized (not append-only), well-organized, and well-named

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by marc2332** [comment]
Closing because this is already implemented, both `alpha` and `beta` enable the SDK logs.
