### ISSUE TITLE
[Task]: Change store behaviour for balance overview of accounts

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3047]
### Task description

Currently we have the writable `balanceOverview` store nested in the `wallet` store. The nature of this store implies it should just be derived from the `accounts` store rather being manually updated, especially now that we've changed to a single account view rather than an account overview view. 

### Requirements

- [ ] Remove nested, writable `balanceOverview` store
- [ ] Create new `AccountMetadata` type 
- [ ] Create new `profileBalanceOverview` derived store (name TBD) from the `accounts` store
- [ ] Adjust logic where `balanceOverview` was used (balance finder, account switcher, ...)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
