### ISSUE TITLE
[Task]: Design introductory guide

### ISSUE THREAD

**Issue by valeriegrappendorf** [iotaledger/firefly#3058]
### Task description

- [ ] Create an introductory guide on how voting works when you first open the tab. Easily explain the concepts behind voting weight and votes accumulating over an extended period.

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
