### ISSUE TITLE
[Task]: Implement basic send confirmation popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3073]
### Task description

To align with new designs we should change the transaction popup to a send confirmation popup. Although we don't have the full details yet so we can implement a basic version and enhance it in the future.

### Requirements

- [x] Add send confirmation popup
- [x] Refactor transaction details popup to reuse components
- [x] Remove old code

### Acceptance criteria

PR approved and merged into `stardust-develop`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
