### ISSUE TITLE
[Task]: Disable horizontal rotation of the device

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3096]
### Task description

Implement screen orientation lock on Android and iOS.

### Requirements

- [] Implement lock on Android
- [] Implement lock on iOS

### Acceptance criteria

The screen orientation must be locked so that it doesn't change when you rotate the device.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
