### ISSUE TITLE
[Task]: Disable accessibility text size changes

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3097]
### Task description

Implement a solution to disable device font-size change for Android and iOS app WebView fonts.

### Requirements

- [] Implement on Android webview
- [] Implement on iOS webview

### Acceptance criteria

When the user change the system device font-size to large then WebView fonts remains the same.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Why do we need to disable an accessibility feature? Shouldn't this feature help users with visual imparity?

**Comment by paul-boegelsack** [comment]
> Why do we need to disable an accessibility feature? Shouldn't this feature help users with visual imparity?

I asked myself the same question. In the end, everyone can decide for themselves whether they want to use this function or not. The problem right now is that it doesn't help people with vision impairment much, because it hurts the user experience. For example, through texts that overlap buttons. I don't know if it's possible to set a max font size, so the feature can effect the texts just to a certain degree. @amadeu2 Do you know that?

**Comment by amadeu2** [comment]
Set the max font size would be a good solution. Right now we haven't the UI ready to scale fonts, but we could take this in account to future mobile refactors.
