### ISSUE TITLE
[Task]: Implement the use native biometrics to confirm device owner.

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3099]
### Task description

Search and implement a Capacitor plugin to use native biometrics on pincode login screen.

Possible design ref: https://www.figma.com/file/wdUzuntB3BR6cbUufPmCks/Firefly-Mobile-App?node-id=543%3A12969

### Requirements

- [] Implement on Android
- [] Implement on iOS

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
