### ISSUE TITLE
[Task]: Update UI with darkmode specifications

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3108]
### Task description

TBD

### Requirements

- [x] #3722

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
