### ISSUE TITLE
[Task]: E10.M2b - Technical Design Specification

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3117]
### Task description

We need to figure out the functionality needed around finding and claiming Shimmer rewards based on a user's IOTA address. The final specification will be documented [here](https://hackmd.io/@cheerful-nicole/Bkvv_joe5/%2FQEqVxR5_RLKKg5efyXwg7A).

### Requirements

- [x] Determine required functionality from `wallet.rs` needed to find Shimmer rewards
- [x] Determine required functionality from `wallet.rs` needed to claim Shimmer rewards
- [ ] `wallet.rs` team (Thoralf) has seen and approved the technical specification

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
