### ISSUE TITLE
[Task]: Update UI and app logic for charts for stardust M3

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3121]
### Task description

TBD

### Requirements

- [x] #3137
- [x] #3138

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
