### ISSUE TITLE
[Task]: Complete bindings for AccountManager

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3124]
### Task description

We need to match the bindings with the methods for the AccountManager.

### Requirements

Fields:
- [ ] accounts
- [ ] background_syncing_status
- [ ] client_options
- [ ] secret_manager
- [ ] event_emitter
- [ ] storage_options
- [ ] storage_manager 

Methods:
- [ ] backup
- [ ] balance
- [ ] builder
- [ ] create_account
- [ ] delete_storage
- [ ] emit_test_event
- [ ] generate_mnemonic
- [ ] get_account
- [ ] get_accounts
- [ ] get_client_options
- [ ] get_node_info
- [ ] get_secret_manager
- [ ] listen
- [ ] recover_accounts
- [ ] set_client_options
- [ ] set_stronghold_password
- [ ] start_background_syncing
- [ ] stop_background_syncing
- [ ] store_mnemonic
- [ ] sync
- [ ] verify_integrity
- [ ] verify_mnemonic

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
