### ISSUE TITLE
[Task]: Temp remove / comment out participation code

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3125]
### Task description

Until we have time to refactor participation from wallet tab etc, we should comment out the code so that it doesn't affect the stardust based application, but we might need the code in the future.

### Requirements

- [ ] Move participation code inside Dashboard next to each other
- [ ] Wrap code in a region so it is easily collapsible
- [ ] Comment out code
- [ ] Remove staking tab from sidebar

### Acceptance criteria

Code is commented out and no errors dues to participation are shown. PR approved and merged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
