### ISSUE TITLE
[Task]: Clean up typings to use typings from bindings

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3126]
### Task description

The types are generated by the bindings for the api requests and responses. We should use these types in the app so we have minimal duplicate types to maintain.

### Requirements

- [ ] Use types from wallet.
- [ ] Fix typing for each component in wallet.tab

### Acceptance criteria

PRs approves and merge and we are using the types from the bindings.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
