### ISSUE TITLE
[Task]: Update app logic and typings for each wallet tab component

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3128]
### Task description

We need to update the app logic and typings for each component in the wallet tab.

### Requirements

 - [ ] [Subtask] Update balance app logic for stardust
 - [ ] [Subtask] Update assets app logic for stardust
 - [ ] [Subtask] Update receive app logic for stardust
 - [ ] [Subtask] Update send form app logic for stardust
 - [ ] [Subtask] Update send confirmation app logic for stardust
 - [ ] [Subtask] Update send app logic for stardust
 - [ ] [Subtask] Update activity history app logic for stardust
 - [ ] [Subtask] Update activity details app logic for stardust
 - [ ] [Subtask] Update charts 1 app logic for stardust
 - [ ] [Subtask] Update charts 2 app logic for stardust

### Acceptance criteria

All components have updated logic and tpings

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
