### ISSUE TITLE
[Task]: Update send confirmation UI and app logic for stardust M3

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3133]
### Task description

TBD

### Requirements

- [x] #3073 
- [x] #3134 
- [x] #3104
- [x] #3110 
- [x] #3109 
- [x] #3421
- [x] #3422
- [x] https://github.com/iotaledger/firefly/issues/3526

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
