### ISSUE TITLE
[Task]: Update activity history UI and app logic for stardust M3

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3135]
### Task description

We need to update the activity history to align with the new designs and the new objects that are returned from wallet.rs.

### Requirements

- [x] #3277
- [x] #3276
- [x] #3278
- [x] #3136 
- [x] #3290
- [x] #3112
- [x] #3313
- [x] #3396
- [x] #3594
- [x] #3595
- [x] #3596
- [x] #3597
- [x] #3609
- [x] #3637
- [x] #3639
- [x] #3640
- [x] #3670 

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
