### ISSUE TITLE
[Task]: match bindings for Account

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3140]
### Task description

We need to match the bindings with the methods for Account. The exposed bindings can be found here: https://thoralf-m.github.io/wallet.rs/iota_wallet/message_interface/account_method/enum.AccountMethod.html#variant.SyncAccount
### Requirements

- [x] collectOutputs 〰️ 
- [x] generateAddresses ✔️ 
- [x] getBalance ✔️ 
- [x] getOutputsWithAdditionalUnlockConditions ✔️ 
- [x] listAddresses ✔️
- [x] listAddressesWithUnspentOutputs ✔️
- [x] listOutputs ✔️ 
- [x] listPendingTransactions ✔️ 
- [x] listTransactions ✔️ 
- [x] listUnspentOutputs ✔️ 
- [x] mintNativeToken   :x:
- [x] mintNfts  :x:
- [x] sendAmount ✔️
- [x] sendMicroTransaction  :x:
- [x] sendNativeTokens  :x:
- [x] sendNft  :x: 
- [x] sendTransfer ✔️
- [x] syncAccount ✔️
- [x] tryCollectOutputs ✔️

### Acceptance criteria

All heavy checked items in requirements are in the node.js bindings

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
The unchecked boxes are left behind for now, since we don't need them urgently. I'll revisit them once they become relevant again.
