### ISSUE TITLE
[Task]: Implement mnemonic-based flow for claiming Shimmer rewards

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3146]
### Task description

This is one of three flows that needs to be implemented to claim Shimmer rewards.

### Requirements

- [x] Create page for selecting reward claim method (i.e. mnemonic, Stronghold, and Ledger)
- [x] Adjust logic for the application router
- [x] Adjust content of profile creation page as needed (change title)
- [x] Adjust content of import IOTA profile success page (change info text)
- [x] Create page for finding Shimmer rewards and initiating claim process
- [x] Create page for successfully claiming Shimmer rewards
- [x] Update UI correctly once finished claiming (change to continue button, update claimed/unclaimed rewards in tile)
- [x] Add logic to complete onboarding flow wrt to `shimmerClaimingAccounts`
- [x] Add base claiming logic
- [x] Add logic to compute new balances and state after a claiming transaction (for each account)
- [x] Add / combine regular accounts with `IShimmerClaimingAccount` (the regular accounts need to stick around so we can just grab them and easily initialise wallet dashboard state)
- [x] Add better error handling
    - [x] Update `ShimmerClaimingAccountTile` UI when `state === ShimmerAccountState.Failed` (add icon with tooltip with reason)
    - [x] Do **NOT** leave any straggling `console.error(...)` statements
- [x] Fix error when going backwards from `ClaimRewardsView` (technically not part of simplest "happy" flow)
- [x] Fix total rewards claimed calculation in claim success view
- [x] Fix claiming state derivation when already fully claimed 
- [x] Ensure sub-components in `ClaimRewardsView` have **ONLY** presentation logic 
- [ ] (Opt.) Add handbook page for reward claiming (add general info + sequence diagram)
- [ ] (Opt.) Remove twin account syncing and enable `transactionSyncing` on the Shimmer claiming accounts (has UX implications about what is considered "unclaimed" - no syncing means we won't know about any previously claimed funds, however we also don't technically know what funds are "claimed" vs "unclaimed"...) 
- [ ] (Opt.) Refactor `SetupClaimedView` and `SetupRecoveredView` since they're similar
- [ ] (Opt.) Parallelize asynchronous operations where possible (e.g. creating an account, then getting its bounded object)
- [ ] (Opt.) Debounce buttons that cause profile manager initialisation (or just add `if` checks?)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
