### ISSUE TITLE
[Task]: Implement Stronghold-based flow for claiming Shimmer rewards

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3147]
### Task description

This is one of three flows that needs to be implemented to claim Shimmer rewards.

### Requirements

- [x] Adjust profile manager configuration during onboarding flow 
- [x] Adjust onboarding routing logic as needed (no Stronghold backup nor password views)
- [x] Test simple case of rewards on account 0 address 0
- [x] Test going backwards and between flows (and with different Strongholds)
- [x] Test claiming via mnemonic then via Stronghold (same _and_ different seeds)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
