### ISSUE TITLE
[Task]: Add Shimmer claiming support for Ledger profiles

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3148]
### Task description

This is one of three flows that needs to be implemented to claim Shimmer rewards.

### Requirements

- [x] Hook up existing pages for Ledger-based profile restoration
- [x] Hook up page for claiming Shimmer rewards
- [x] Add prompt popup when user is making the claiming transaction
- [x] Subscribe / unsubscribe to `transactionProgress` event in `ClaimRewardsView.svelte`
- [x] Ensure unhappy flows are okay:
    - [x] Cancelling transactions
    - [x] Disconnecting the device (before and after connection confirmation prompt) 
- [x] Fix this error:
    ```
    {type: "Block", error: "input count and unlock count mismatch: 8 != 2"}
    ```
- [x] Disable back button in success view

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
