### ISSUE TITLE
[Task]: Deep links logic does not account for different decimal separators

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3153]
### Task description

> Hello, some users have reported an odd issue with the pay with firefly buttons in soonaverse and zentangle auctions depending if firefly is using dot or coma for the numbers (default system configuration). 
When the link from the websites sends a dot in the value of IOTA (e.i. 4.32 Mi) and firefly is working with comas, sometimes the dot is removed multiplying the value for the number of digits after the coma. 
This has made users bidding 10x the amount they were willing to spend. 
Is it possible to check into this? To replicate the conditions considering automatically sending tokens using a site URI with several consecutive transactions as if it were an auction.

Currently, the deep links functionality does take into account other decimal separators.

It would be worth taking at look at the EIPs around URI scheming and formatting to align more closely with what the broader industry is doing _then_ implementing it in a similar way.

### Requirements

- [ ] Research EIPs around URI scheming and formatting to see what other, if any, decimal separators are accepted 
- [x] Ensure that users whose locale uses another decimal separator other than `.` is displayed properly

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
