### ISSUE TITLE
[Task]: Refactor deep link for stardust sending in M3

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3158]
### Task description

Deep links need to be updated per new Stardust changes.

### Requirements

- [ ] Move `deep-link` module from `common` to `auxiliary` (and delete `common` folder)
- [ ] Design new context operations for Stardust functionality
- [ ] Implement changes as necessary
- [ ] Change setting name from "IOTA links" to "Deep links"

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
