### ISSUE TITLE
[Task]: Sidebar and back button are not reactive to changing locales

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3166]
### Task description

Currently, neither the back button nor sidebar tabs does not change accordingly when switching between locales. To be specific, the text changes appropriately when changing from English to another locale, however when switching back to English or another locale it does NOT.

:heavy_check_mark: English -> Non-English
:x: Non-English -> English
:x: Non-English -> Non-English 

### Requirements

- [x] Ensure that back button text changes accordingly when switching locales
- [x] Ensure that the sidebar tab tooltip text changes accordingly when switching locales

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
