### ISSUE TITLE
[Task]: Make checkbox settings' text change styling after becoming re-enabled  

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3167]
### Task description

Currently the checkbox settings' text styling does not change after becoming `disabled` - it just stays greyed out until the user re-navigates back to the page.

### Requirements

- [x] Make sure styling of checkbox text changes accordingly when disabling / enabling the setting

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
