### ISSUE TITLE
[Task]: Re-align types and logic around node info

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3176]
### Task description

We need to start using the updated node info type.

### Requirements

- [x] Change the API wrapper function to use new bindings
- [x] Change function signatures as needed
- [x] Use the updated node info type

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
