### ISSUE TITLE
[Task]: Split up network types 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3186]
### Task description

There should be smaller, more defined types within the overall `NodeInfo` type.

### Requirements

- [ ] Split up the `NodeInfo` type

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
