### ISSUE TITLE
[Task]: Refactor `router` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3187]
### Task description

Currently there is a lot of logic contained within the application routers, keeping strictly routing logic.

### Requirements

- [x] #3221
- [x] Remove profile migration out of `login-router.ts` (15min)
- [x] Move app logic out of `backup-router.ts` (15min)
- [x] Move app logic out of `protect-router.ts` (15min)
- [x] Move app logic out of `app-router.ts` (30min)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
