### ISSUE TITLE
[Task]: Update general layout for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3192]
### Task description

The pre stardust UI update makes it necessary to change some of the more generic and reusable UI components regarding their look and functionality. 

### Requirements

- [ ] [Subtask]: Adapt the new layout and color theme to all general elements
- [ ] [Subtask]: Mobile header update
- [ ] [Subtask]: Implement a bottom tab navigation for mobile
- [ ] [Subtask]: Implement the appearance of native UI elements for mobile

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
