### ISSUE TITLE
[Subtask]: Mobile header update

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3194]
The current header is supposed to be changed to a more dynamic one.

- [x] Right menu button is no longer visible
- [x] Scrolling the asset list triggers if the balance is visible inside the header or not
- [ ] Added loading spinner for user feedback
