### ISSUE TITLE
[Task]: Implement the appearance of native UI elements for mobile

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3196]
### Task description

Common UI elements should be rendered differently depending on the platform. That is necessary to create a more familiar user experience.

### Requirements

- [x] Exact implementation is determined (E.g. use of plugins, native elements or js components)
  
List alle elements that have to be updated here:
- [x] Action Sheet
- [x] Share Dialog

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
