### ISSUE TITLE
[Task]: Update send transactions flow for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3198]
### Task description

TBD

### Requirements

- [ ] # [Subtask]: Adapt the layout of the UI overhaul for send transactions flow
- [ ] # [Subtask]: Change wallet selection for internal sendings

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
