### ISSUE TITLE
[Task]: Update receive funds flow for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3201]
### Task description

TBD

### Requirements

- [x] #3202
- [ ] #3203

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
inside the PR is the TODO list, just some changes on Drawer component
