### ISSUE TITLE
[Task]: Update transaction view for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3204]
### Task description

This view is intended to present detailed information about a transaction. The presentation should be adaptive to the respective asset (IOTA, Shimmer, Assembly, Native Token, etc.)

### Requirements

- [ ] #3205
- [x] #3206

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
