### ISSUE TITLE
[Task]: Update wallet overview for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3207]
### Task description

TBD

### Requirements

- [x] #3208
- [x] #3209
- [x] #3210
- [x] #3211

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
