### ISSUE TITLE
[ Subtask]: Edit wallet entries through the overview

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3211]
In the current version of the UI it’s not possible to edit a wallet through the wallet overview. This is supposed to be changed:

- [ ] Edit button is displayed inside the overview
- [ ] Instead of the balance information a button for each wallet entry appears after clicking on edit
- [ ] Text of the edit button changes to done after it was clicked
- [ ] Clicking on done shows the balance information again
- [ ] Interaction with a wallet button opens a menu to customize or delete the wallet
