### ISSUE TITLE
[Task]: Update settings and profile view for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3213]
### Task description

TBD

### Requirements

- [x] #3214
- [x] #3215

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
