### ISSUE TITLE
[Task]: Update onboarding for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3216]
### Task description

TBD

### Requirements

- [ ] #3217
- [x] #3218

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
