### ISSUE TITLE
[Task]: Refactor core `app` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3221]
### Task description

The `app*.ts` files need to be refactored into a dedicate `app` module. 

### Requirements

- [x] Move constants, enums, interfaces, stores, utils, etc. over to `app`
- [x] Improve settings and updater types
- [ ] ~~Change notion of "Platform" to "app"~~

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
