### ISSUE TITLE
[Task]: Create necessary views for finding, claiming, and migrating Shimmer rewards

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3229]
### Task description

We need to create the view for finding, claiming, and migrating Shimmer rewards. 

This task deals specifically with creating the UI needed for these views - **it will NOT be hooked up to the API or correctly placed in the onboarding flows** (yet).

### Requirements

- [x] Create view for finding, claiming, and migrating Shimmer rewards
- [x] Create view for successfully migrating Shimmer rewards
- [x] Refactor UI as necessary for cleanliness and re-usability / composability
- [x] Put all text into the locale dictionary

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
