### ISSUE TITLE
[Task]: Refactor `notification` module / create `alert` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3240]
### Task description

With some new design changes it is a good time to refactor the existing code around notifications into a dedicate auxiliary `notification` and `alert` modules.

### Requirements

- [ ] Change previous `notification`-based code to `alert`-based
- [ ] Create new `notification` module and components
- [ ] Cleanly share common code between modules as necessary

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
