### ISSUE TITLE
[Task]: Define toast notification design

### ISSUE THREAD

**Issue by jvegis** [iotaledger/firefly#3241]
### Task description

We need to define a new set of toast notifications to better communicate system status to the users.

### Requirements

- [x] Deliver a set of different toast notifications for different use cases

### Acceptance criteria

All design tasks have been complete, and then reviewed and approved by product owner / epic owner.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
