### ISSUE TITLE
[Task]: Refactor unit tests into specific modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3243]
### Task description

Our current setup has all unit tests for all modules in one folder, whereas they should be as close to their respective source code files as possible. 

### Requirements

- [x] Move unit tests from `shared/lib/tests` to their respective module directories (under `<module>/tests`)
- [x] Determine best method for sharing the different unit test mocks (globally setup all mocks?)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
