### ISSUE TITLE
[Subtask] Refactor account switcher UI, app logic and add balance

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3245]
- [x] We we should compentise the ui components for the account switcher.
- [x] Move viewable account stores to account module
- [x] Add balance to the account switcher to match v1.6.0

**Comment by MarkNerdi** [comment]
hello there
