### ISSUE TITLE
[Task]: Refactor `icon` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3261]
### Task description

It will be convenient for the icon-related logic to be refactored into a module.

### Requirements

- [ ] Create `icon` module in `lib/auxiliary`
- [ ] Create `Icon` enum for all icons to use in components
- [ ] Move `SettingsIcons` to new module and rename to `SettingsIcon`
- [ ] Separate SVG code `icons.js` into separate files in `auxiliary/icon/icons/` (use `kebab-case` for filenames) 
- [ ] Delete icon component folder and create `Icon.svelte` component
- [ ] Check for floating icon logic / code around the library and move to new module as needed
- [ ] Add TSDoc annotation comments to all exported code from new module

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
