### ISSUE TITLE
[Task]: Document coding conventions in the handbook

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3264]
### Task description

We need to keep the documentation up to date with the changes we are making for Stardust. There is a backlog of tasks for different coding conventions to be updated in the handbook.

### Requirements

- [x] #3265
- [x] #3266
- [x] #3267
- [x] #3268
- [x] #3269
- [x] #3270
- [x] #3272
- [x] #3273
- [x] #3274
- [x] #3275
- [x] #3484
- [x] #4523

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
