### ISSUE TITLE
[Task] Update manage account UI and app logic for stardust M3

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3285]
### Task description

We need to update the manage account UX to align with the current create account popup. As well as refactoring out and updating any app logic.

### Requirements

- [x] #3244 
- [x] #3419

### Acceptance criteria

Above subtasks are all complete

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
