### ISSUE TITLE
[Task]: Replace balance finder with wallet finder in stardust M2

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3287]
### Task description
Now that we only have one address and the accounts should be synced as much as possible, we should replace the balance finder with a wallet/account finder.

### Requirements

- [x] Modify design of balance finder to match new wallet finder
- [x] Refactor app logic out of wallet finder
- [x] Replace api call with new one

### Acceptance criteria

Above requirements met and the new popup matches the new design

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
