### ISSUE TITLE
[Task]: Fix typo for `customizeAccount` field in `en.json`

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3304]
### Task description

The `customizeAccount` field in `shared/locales` is misspelled as `customizeAcount`. Rename the field and update instances in Firefly where `locale` function is called with the misspelled argument.

### Requirements

- [ ] Correct misspelled field name
- [ ] Update calls to locale that use the misspelled field name

### Acceptance criteria

Submit PR with change to `en.json` and `AccountActionsMenu.svelte`.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
