### ISSUE TITLE
[Task]: Expose wallet api methods

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3312]
### Task description

Expose the following methods:

- [x] setStrongholdPasswordClearInterval
- [ ] claimShimmerRewards
- [x] setAlias

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
