### ISSUE TITLE
[Task]: Update delete profile app logic for stardust api

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3318]
### Task description

The APIs for `delete/removeStorage` have changed and need to be updated, including the settings.

### Requirements

- [x] Adjust new APIs accordingly
- [x] Hook up logic in the delete profile setting
- [x] Replace the delete profile settings icon with a trash can

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
