### ISSUE TITLE
[Task]: Update network config settings for stardust

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3319]
### Task description

We need to update all the network config settings to ensure that they work with the new stardust api and network module. 
For now I think we can ignore the concept of a primary node. And the user can no longer switch an account so we can clean that up.

### Tech Specs

1. [x] Allow one client per profile (i.e. only one set of `IClientOptions`)
2. [x] Allow client configuration in the network config settings 
4. [x] Allow view node info in network config settings
5. [x] Refactor `NodeInfoPopup` component, change to individual copyable boxes
6. [x] Disallow network switching for a profile
8. [x] Replace concept / code of `networkConfig` to be `clientOptions`
7. [ ] (Opt.) Refactor existing network logic (potentially create `client` module)
3. [ ] ~~(Opt.) Allow client configuration during onboarding (node settings)~~

### Requirements

- [x] Hide "Node configuration" when automatic node selection is selected
- [x] Fix "Node configuration" list for all cases
- [x] Fix "Add node" click

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
