### ISSUE TITLE
[Task]: Add event listeners to wallet

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3339]
### Task description

The following event listeners `(typescriptFunction() -> WalletEventType)` should be updated:

- onStrongholdStatusChange() -> still missing
- onNewTransaction() -> NewOutput
- onConfirmationStateChange() -> TransactionInclusion
- onBalanceChange() -> still missing
- onReattachment() -> ?
- onTransactionProgress() -> TransactionProgress
- onLedgerAddressGeneration() -> LedgerAddressGeneration

Additional events that are thrown from wallet.rs:
- ConsolidationRequired
- SpentOutput

### Requirements

- [x] https://github.com/iotaledger/firefly/issues/3368
- [x] https://github.com/iotaledger/firefly/issues/3369
- [x] https://github.com/iotaledger/firefly/issues/3370
- [x] https://github.com/iotaledger/firefly/issues/3371
- [x] https://github.com/iotaledger/firefly/issues/3373
- [x] https://github.com/iotaledger/firefly/issues/3374

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
