### ISSUE TITLE
[Subtask]: Remove old event handlers

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3374]
### Task description

Remove the old event handlers, since we don't need them anymore

### Requirements

- [x] Create a design pattern to handle events (https://github.com/iotaledger/firefly/issues/3368)
- [x] Create a handler for `NewOutput()` (https://github.com/iotaledger/firefly/issues/3369)
- [x] Create a handler for `TransactionInclusion` (https://github.com/iotaledger/firefly/issues/3370)
- [ ] Create a handler for `TransferProgress` (https://github.com/iotaledger/firefly/issues/3371)
- [ ] Create a handler for `ConsolidationRequired` (https://github.com/iotaledger/firefly/issues/3372)
- [x] Create a handler for `SpentOutput` (https://github.com/iotaledger/firefly/issues/3373)

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
