### ISSUE TITLE
[Task]: Prepare handbook for Stardust changes

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3387]
### Task description

There are a few things to do before we can start editing the handbook according to the code.

### Requirements

- [x] Change workflow to deploy new changes only for `stardust-develop` branch (on `develop` branch) 
- [x] Merge handbook commit(s) into the `stardust-develop` branch
- [ ] (Opt.) Edit PR template to be more specific on checklist (make sure docs / comments are updated)
- [ ] (Opt.) Figure out versioning system for maintaining older docs

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
