### ISSUE TITLE
[Task]: Implement library spec generation

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3392]
### Task description

It will be handy to have specs so that devs can know what is within each module.

### Requirements

- [x] Determine tool to generate docs with (see [`typedoc`](https://typedoc.org/))
- [ ] Implement auto-generation in GH workflow for building and deploying site

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
