### ISSUE TITLE
[Task]: Update deep link settings functionality

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3393]
### Task description

Deep links need to be updated for the app to work as intended.

### Requirements

- [ ] ...
- [ ] Change "IOTA links" to "IOTA deep links" or just "deep links"

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
