### ISSUE TITLE
[Task]: Search for additional wallets when user recovers account

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3398]
### Task description

With creation of `recoverAndLoad` function, we can now search for additional wallets when recovering accounts. To improve user experience we should add this function to the restore profile flow.

### Requirements

- [x] Restoring a profile calls the recoverAndLoad function
- [x] Accounts with multiple wallets will display them (up to a threshold of say 5) when recovering

### Acceptance criteria

Above requirements met

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
