### ISSUE TITLE
[Task]: Adjust account notification badge to match new Stardust design

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3408]
### Task description

The account notification badge has changed in the Figma design files for Stardust. Adjust the notification badge to reflect these changes.

### Requirements

- [x] Move the account notification badge so that it sits on the edge of the account profile picture.

### Acceptance criteria

The above criteria is met and the PR is merged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
