### ISSUE TITLE
[Task]: Add background sync on login

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3410]
### Task description

We need to add / replace the background sync call when the user logs in to a profile and remove the direct call to sync accounts from the loadAccount function.

### Requirements

- [x] Add background sync
- [x] Remove sync from load account

### Acceptance criteria

PR Approved and merged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
