### ISSUE TITLE
[Task]: Implement change stronghold password setting with new api

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3411]
### Task description

The APIs for change stronghold password have/will be changed and need to be updated, including the settings.

### Requirements

- [x] Adjust new APIs accordingly
- [x] Refactor app logic out of component

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
