### ISSUE TITLE
[Task]: Fix and enable change pin setting

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3412]
### Task description

We no longer use the pin in wallet rs so we can fix the change pin code so that it only updates the pin stored on the os key store and then enable this setting.

### Requirements

- [ ] Refactor app logic out of component

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
