### ISSUE TITLE
[Task]: Track stronghold lock status on the frontend

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3413]
### Task description

We no longer have a listener for when the stronghold status is changed, i.e. unlocked -> locked.
We should track this time locally and update the svelte stores respectively.

### Requirements

- [x] Track the stronghold lock interval locally
- [x] Update svelte stores when interval is exceeded

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
