### ISSUE TITLE
[Task]: Polish stardust M2 for alpha 1

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3414]
### Task description

We should polish the onboarding flow ready for an alpha builld.

### Requirements

- [x] #3479
- [x] #3480
- [x] #3441 
- [x] #3447
- [x] #3453
- [x] #3548
- [x] #3496
- [x] #3500
- [x] #3507
- [x] #3527
- [x] #3583
- [x] #3584
- [x] #3553
- [x] #3560

### Acceptance criteria

PRs for above requirements merged into stardust-develop.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
