### ISSUE TITLE
[Subtask]: Validate the expiration date and time before sending

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3421]
### Task description

We should validate the expiration date and time before we send to ensure that the user is not selected a time in the past by time the go to confirm the send.

### Requirements

- [x] Add date/time validation when user selects expiration time for transaction
- [x] Add date/time validation when user sends transaction with expiration time

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
