### ISSUE TITLE
[Task]: E10.M6 - Init collectibles tab

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3435]
### Task description

Init collectibles tab

### Requirements

- [x] Add collectibles router
- [x] Add collectibles tab with empty view

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
