### ISSUE TITLE
[Subtask]: E12.M3 - handle new nft with media

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3438]
### Task description

When a new NFT is detected by firefly, we need to:
- Update the corresponding stores (eg `collectibles`)
- Because the nature of the NFT is likely media, we should fetch the media and extract a thumbnail out of it (low-res) to be later displayed in the gallery overview, the transaction history...
- The extracted thumbnail should be cached to avoid downloading the media file each time for the gallery overview and the transaction history

**Technical questions:**
- How to generate a thumbnail?
- Where do we store thumbnails?
- Should we cache the whole media or only thumbnail?
- How do we securely load the media assets?

### Requirements

- [ ] Add entry to stores
- [ ] Generate thumbnail
- [ ] Cache thumbnail

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kraftjs** [comment]
Closing issue as stale
