### ISSUE TITLE
[Subtask]: Match buttons in onboarding flow to Figma design

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3441]
### Task description

Match buttons in onboarding flow to Figma design.

### Requirements

- [ ] Align protocol and network selection buttons at bottom
- [ ] Add ">" to buttons in onboarding flow to match Figma design

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
