### ISSUE TITLE
[Subtask]: E12.M2 - UI: non empty collectibles gallery

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3442]
### Task description

General UI with its components for the collectibles gallery, when the gallery is not empty

### Requirements

- [x] collectibles card (static thumbnail loaded & skeleton)
- [x] collectibles grid
- [x] load media and display skeleton while not loaded

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
