### ISSUE TITLE
[Subtask]: E12.M2 - UI: empty collectibles gallery

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3443]
### Task description

Empty collectibles gallery

### Requirements

- [x] Empty gallery
- [x] Button to open receive address popup

### Acceptance criteria

Meets the above requirements 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
