### ISSUE TITLE
[Subtask]: E12.M2 - Feature: search bar

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3444]
### Task description

Add searchbar component with the filtering feature to the collectibles gallery.
Search by name.

### Requirements

- [ ] search bar component
- [ ] search bar functionality

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
