### ISSUE TITLE
[Task]: E12.M2 - Initial collectibles general view

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3445]
### Task description

Collectibles general view, grid gallery

### Requirements

- [x] #3442
- [x] #3443
- [x] #3444

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
