### ISSUE TITLE
[Subtask]:  E10.M6 -  Initial selected collectible UI

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3446]
### Task description

Prepare the UI for the detailed view of an NFT. 
In this task we will only prepare the UI with unimplemented actions, the actions will be detailed in a different task

### Requirements

- [x] Empty Media panel
- [x] Empty Details panel
- [x] Collectible actions menu
- [x] Action buttons in details panel

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
