### ISSUE TITLE
[Subtask]: Disable IOTA routes and Shimmer mainnet route

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3447]
### Task description

Disable IOTA routes and Shimmer mainnet route in onboarding flow with feature flags from #3431

### Requirements

- [x] Disable IOTA onboarding routes
- [x] Enable only Shimmer devnet onboarding route

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
