### ISSUE TITLE
[Task]: E12.M3 - Selected collectible media viewer / player

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3448]
### Task description

In the selected NFT view, we have to implement the real media viewer/player. In the gallery we only display a generated thumbnail of the NFT, but in the detailed view we have to load and display the real media asset. 

### Requirements

- [ ] Load asset
- [ ] Image
- [ ] Gif
- [ ] Video

### Acceptance criteria

Meets to above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kraftjs** [comment]
Partially implement already and further split into tasks

**Comment by kraftjs** [comment]
Stale task
