### ISSUE TITLE
[Task]: E12.M2 - Collectible details panel

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3449]
### Task description

UI for for selected collectible/NFT details panel has been implemented, but the data is not connected.

### Requirements

- [ ] Name
- [ ] Metadata
- [ ] Storage deposit
- [ ] Attributes

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
