### ISSUE TITLE
[Task]: Implement downloading for NFT media

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3451]
### Task description

Instead of using the default HTML behaviour for the `<img>` and `<video>` tag by passing in the NFT Media URL, we want to serve the images from our local file system.
On login, we want to check all NFTs if the corresponding media is already stored, and if not (and if all security checks pass) download them.

### Requirements

- [ ] Check if NFT Media meets our security check
- [ ] Download NFT Media on Login
- [ ] Download NFT Media on Receive / Mint
- [ ] The destination folder should be `USER_PATH/__storage__/PROFILE_ID/nfts/NFT_ID/original`

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
