### ISSUE TITLE
[Task]: E12.M2 - Peripheral action - view nft in explorer

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3452]
### Task description

Open browser to view the NFT in the Explorer

### Requirements

- [ ] Open browser to view the NFT in the Explorer

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
