### ISSUE TITLE
[Subtask]: Hide migration flows on Shimmer routes

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3453]
### Task description

Hide migration flows on Shimmer routes and adjust text descriptions to remove references to migration.

### Requirements

- [ ] Hide migration flows on Shimmer routes
- [ ] Remove references to "migrating" in descriptions of Shimmer routes

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
