### ISSUE TITLE
[Task]: E12.M2 - Peripheral action - view nft in IPFS

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3455]
### Task description

Open browser windows to view the NFT in IPFS.

**Technical questions:**
- Does the specification allow the storage of the asset somewhere that is not IPFS?

### Requirements

- [ ] Open browser windows to view the NFT in IPFS

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
