### ISSUE TITLE
[Subtask]: Adjust onboarding routes to match Figma design

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3457]
### Task description

Onboarding routes don't quite match the Figma design:
- Our current flow has Profile.svelte (naming your profile) in a different position of the onboarding flow than in the Figma design docs.  
- Action descriptions are different depending on whether the protocol is Shimmer or Iota
Change the onboarding flow to match the design.

### Requirements

- [ ] Move `Profile.svelte` route to match Figma design

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
