### ISSUE TITLE
[Task]:  E12.M1 - Receive collectible

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3468]
### Task description

Implement UI and logic around "receiving a new NFT"

### Requirements

- [x] #3464
- [x] #3465
- [x] #3466
- [x] #3467

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
