### ISSUE TITLE
[Task]: E12.M1 - Send collectible

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3472]
### Task description

From the selected NFT view you can send it

### Requirements

- [x] #3469
- [x] #3470
- [x] #3471

### Acceptance criteria

meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
