### ISSUE TITLE
[Subask]: E12.M2 - Burn nft app logic

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3474]
### Task description

[IOTA Wiki - Burning an nft](https://wiki.iota.org/next/introduction/explanations/ledger/nft#burning-an-nft)

### Requirements

- [ ] Burn NFT and free storage deposit
- [ ] Before burning an NFT, always check whether its NFT Address owns something in the ledger. Otherwise, you may lose those funds forever!

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
