### ISSUE TITLE
[Task]: Polish stardust M3 for alpha 1

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3477]
### Task description

We should polish the UI for stardust compatible alpha 1 release

### Requirements

- [x] #3480
- [x] #3482
- [x] #3487
- [x] #3582
- [x] #3558
- [x] #3567
- [x] #3555
- [x] #3550
- [x] #3603
- [x] #3604

### Acceptance criteria

The above polishing tasks have been completed and merged into stardust-develop

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
