### ISSUE TITLE
[Task]: Modify developer setup for Firefly V2

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3483]
### Task description

Mainly because of the fact that we no longer need to explicitly build the `wallet.rs` library, we can change the handbook page accordingly.

### Requirements

- [ ] Modify [this](https://iotaledger.github.io/firefly/guides/environment-setup/desktop) handbook page with new build and development steps

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
