### ISSUE TITLE
[Task]: Add team page to handbook

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3485]
### Task description

With a larger team and some added hierarchy, it'll be important to document everyone's specific role alongside a short description of themselves and what they work on for Firefly.

### Requirements

- [x] Create new page for "Team"
- [ ] Document everyone's position, skills, interests, hobbies, socials, etc.

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
