### ISSUE TITLE
[Task]: Cleanup the GitHub wiki

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3486]
### Task description

The wiki needs to be updated and cleaned up slightly now.

### Requirements

- [ ] Consider adding keywords / tags to the repository
- [ ] Consider removing the usage of "new" since Firefly has been released for a while
- [ ] Update "[Backlog: Epics & Milestones](https://github.com/iotaledger/firefly/wiki/Backlog:-Epics-&-Milestones)"
- [ ] Add concrete info to "[Developer Setup](https://github.com/iotaledger/firefly/wiki/Developer-Setup)" (rather than just linking to handbook)
- [ ] Polish other externally facing pages like "[Issues](https://github.com/iotaledger/firefly/wiki/Issues)" and "[Pull Requests](https://github.com/iotaledger/firefly/wiki/Pull-Requests)"

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
