### ISSUE TITLE
[Task]: Fix add/custom node flow/popup and enable add node and custom network buttons

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#3495]
### Task description

The non-official node flows need to be implemented back, and the code needs some fixes

### Requirements

- [x] Custom network onboarding flow working
- [x] Adding node through settings flow working

### Acceptance criteria

Fulfills all the requirements above

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
