### ISSUE TITLE
[subtask]: align onboarding buttons to bottom and update icons

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3498]
### Task description
align onboarding buttons to bottom and update icons

### Requirements
- [x] Bottom align onboarding buttons
- [x] Update icons

### Acceptance criteria
Meets the above requirements.

### Creation checklist
- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
