### ISSUE TITLE
[Task]: Improve drawer usability for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3510]
### Task description

- [ ] Drawer component needs to be closed from any place.
- [ ] Drawer background should be blurred, and fix marker position.

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
@paul-boegelsack  I've made this task, we talked about this last week

**Comment by paul-boegelsack** [comment]
@amadeu2 Alright, maybe you can assign any task which is completed but not in develop yet to yourself. Otherwise we will have this confusion again, I guess.
