### ISSUE TITLE
[Subtask]: Hide migration flows and adjust onboarding text

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3511]
### Task description

Adjust descriptions in onboarding routes to remove references to "migrating" and to match descriptions provided by Figma

### Requirements

- [x] Hide migration buttons on shimmer routes
- [x] Update text in OnboardingRoutes to match Figma design or hide migration descriptions

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
