### ISSUE TITLE
[Subtask]: Adjust animations

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3513]
### Task description

Update animations in other onboarding routes to match Figma design and add animations to OnboardingProtocol and OnboardingNetwork files.

### Requirements

- [x] Add animations to OnboardingProtocol and OnboardingNetwork
- [x] Update animations in other onboarding routes to match Figma design

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
