### ISSUE TITLE
[Task]: Release wallet.rs version

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3519]
### Task description

TODO:

- [x] Fix collectOutputs
- [x] Release new wallet.rs version
- [x] Update FF interfaces + dependencies

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
