### ISSUE TITLE
[Subtask]: alter Ledger import routes depending on protocol

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3529]
### Task description
The `Input.svelte` file currently links the user to a Ledger route that has a button for importing a Ledger profile and migrating an old legacy Ledger profile. Shimmer doesn't handle migration so the functionality needs to change if the protocol is set to Shimmer. Instead, have `Input.svelte` link directly to the import a Ledger profile option when Shimmer is set as the protocol.

### Requirements

- [x] Change Ledger route logic on Shimmer

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
