### ISSUE TITLE
[Task]: fix language issues for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3533]
### Task description

TBD

### Requirements

- [ ] All texts on main view are translated after changing language
- [ ] All texts during onboarding are translated after changing language
- [ ] All texts in settings view are translated after changing language

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
closes as duplicated with #[#3630](https://github.com/iotaledger/firefly/issues/3630)
