### ISSUE TITLE
[Task]: Fix transaction history export

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3547]
### Task description

Exporting the history takes forever and it's not clear where files are saved.

### Requirements

- [ ] An export folder can be selected
- [ ] CSV file is saved in the selected folder 

### Acceptance criteria

Can be closed when all above requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
@amadeu2 Do we have a fix for that?

**Comment by amadeu2** [comment]
> @amadeu2 Do we have a fix for that?

It's not implemented yet on `CapacitorApi.ts` we could use also the share native dialog for this. 
It's not priority now.

**Comment by begonaalvarezd** [comment]
Blocked by #2473
