### ISSUE TITLE
[Subtask]: Add OnboardingButton component

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#3563]
### Task description
Create `OnboardingButton.svelte` file that matches Figma design for onboarding flow

### Requirements
- [x] New `OnboardingButton.svelte` component that matches Figma onboarding designs

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
