### ISSUE TITLE
[Task]: Improve the UX of adding an account

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3601]
### Task description

Currently when you add an account we don't wait on the asynchronous action and therefor it doesn't look like the account was added or switch to the account. We should show a busy state until the account is created and then switch to it.

### Requirements

- [x] Show busy state when adding an account
- [x] Switch to account when it is created
- [x] Handle any errors

### Acceptance criteria

Above requirements have been met.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
I realised this is the case when we have stronghold unlocked, but when we need to provide a password we open the password popup but never return to the add account popup after successfully unlocking.

**Comment by jeeanribeiro** [comment]
> I realised this is the case when we have stronghold unlocked, but when we need to provide a password we open the password popup but never return to the add account popup after successfully unlocking.

I think that [this commit](https://github.com/iotaledger/firefly/pull/3684/commits/c9b0da58177dbd78e81763f82c4de25b8c758915) can handle it
