### ISSUE TITLE
[Task]: Only attempt to restore accounts when restoring a profile and not when creating a new one

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3602]
### Task description

Currently when creating a profile, no matter what the first time we load accounts we attempt to restore them. We should change this so that we only restore the accounts when we are on a restore flow.

### Requirements

- [ ] Change login flag from firstLogin to attemptRestore
- [ ] Only set flag in login of restore flows

### Acceptance criteria

PR approved and merged

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
