### ISSUE TITLE
[Task]: Fix network configuration for custom networks

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3607]
### Task description

Currently network configuration is not working on custom networks. We should only show the manual configuration details, and the list of nodes that have been added. No needed for the automatic selection. But right now it has a choice and clicking on manual does not show the list of nodes.

### Requirements

- [ ] Fix network configuration on custom networks

### Acceptance criteria

PR approved and merged into stardust-develop

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
I was thinking for the settings around manual / automatic node selection, we can just disable / grey them out. On custom networks that setting would always be manual anyways
