### ISSUE TITLE
[Subtask]: Adjust routing of all onboarding flows

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3621]
### Task description

The onboarding flows' routing has changed and must be updated accordingly.

### Requirements

- [x] Ensure no application logic exists in `router` module
- [x] Organize / cleanup view component files in `routes/setup` directory 
- [ ] ~~Move mnemonic-based recovery kit~~ 
- [x] Adjust flows accordingly
- [x] Make sure that no app logic is in any router file (see `recovery-router.ts`)
- [x] Make sure all `Subrouter`s use `parentRouter` at end of flows and for other things
- [x] Make sure all `parentRouter`s are not Svelte stores
- [x] Change routers to be regular variables rather than Svelte stores
- [x] Fix merge mistakes with node configuration form component (see [here](https://github.com/iotaledger/firefly/blob/stardust-develop/packages/shared/routes/onboarding/OnboardingCustomNetworkView.svelte#L19))
- [x] Add onboarding specification to handbook
- [x] Add back button to "Congratulations" view
- [x] Use `OnboardingButton` rather than `Button`
- [x] Add Chrysalis animation back
- [x] Fix Stronghold -> mnemonic restoration bug
- [x] Fix Stronghold restoration flow
- [x] Fix client options bug with existing profiles
- [x] Fix add new profile -> onboarding flow routing (showing app setup flow when profiles already exist)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
