### ISSUE TITLE
[Subtask]: Combine the two storage PIN views into one

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3622]
### Task description

The two PIN views need to be combined into one to cleanup the general flow.

### Requirements

- [x] Remove PIN confirmation view
- [x] Add PIN confirmation input to first PIN view
- [x] Adjust form / validation logic as necessary within the one view component

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
