### ISSUE TITLE
[Subtask]: Ensure all views contain correct locales

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3623]
### Task description

With more general re-usability of UI components, we need to ensure that the onboarding views can still accommodate for all the different content that they're used for (e.g. success view for restoring a profile vs claiming Shimmer rewards)

### Requirements

- [x] Polish text in the `LanguageAndAppearance` view
- [x] Polish text in `Welcome` screen depending on supported protocols
- [x] Add sub-label to buttons in `ChooseProtocol`
- [x] Ensure that text makes sense when creating new profile vs restoring vs claiming rewards, etc.
- [x] Ensure that all onboarding locales are named consistently
- [x] Ensure that all onboarding locales are punctuated consistently
- [x] Ensure that all onboarding action buttons have consistent styling

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
