### ISSUE TITLE
[Subtask]: Ensure all views are user accessible

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3627]
### Task description

With the changes to some of the forms within the onboarding flow, it is important that the user accessibility is maintained across the different views.

### Requirements

- [x] Ensure reasonable tab-key functionality for each view
- [x] Change autofocus properties on PIN form
    - [x] Autofocus on first input
    - [x] Autofocus on second input when first input is filled
    - [x] Autofocus on submit button when second input is filled
- [x] Change autofocus on Stronghold password form
    - [x] Ensure sensible tab-key accessibility

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
