### ISSUE TITLE
[Task]: Rename name desktop app

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3633]
### Task description

We have now agreed the temporary name for V2 to be `Firefly (Stardust)` until IOTA is migrated with the stardust protocol and at that point we can change the name of `Firefly (Stardust)` to `Firefly` and deprecate V1.

### Requirements

- [ ] Rename product in package.json
- [ ] Rename app name in build scripts
- [ ] Rename app in the fix name script

### Acceptance criteria

PR approved and merged with above requirements met

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
