### ISSUE TITLE
[Task]: Document stardust activity flows

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3635]
### Task description

We now have very complex logic for building and maintaining the activity history. We need to document this as is so that we can understand it and see where there are improvements needed.

### Requirements

- [ ] Document all activity logic and flows

### Acceptance criteria

Documentation is approved by Nicole

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
