### ISSUE TITLE
[Task]: Produce missing illustrations for onboarding flows

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3636]
### Task description

We have new or changed onboarding pages and we don't have an illustration or the current one doesn't match. We need to produce an illustration in the same style as previous, for both light and dark mode.

### Requirements

Illustrations we need:
- [ ] Shimmer vs IOTA selection used on normal and dev profiles
- [ ] Network selection for devnet profiles, dev user decides on mainnet vs devnet vs custom network
- [ ] Custom network input on dev profiles
- [ ] Profile name input screen

### Acceptance criteria

Illustrations approved by Andrew

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by digital-zen** [comment]
@nicole-obrien 

After discussion between the design team and Aleksa, we proposed the following:

The first three screens can use the same illustration to speed up delivery.

The profile name input screen can re-use the existing IOTA illustration (chest holding monster).

**Comment by nicole-obrien** [comment]
Thanks for the update, will close and @kraftjs can use this info for his PR
