### ISSUE TITLE
[Task]: Modify logo for Firefly (Stardust)

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3638]
### Task description

We need to modify the logo for Firefly (Stardust) so that we can easily distinguish between the two apps. We don't want something drastically different as we are not changing the whole branding and eventually the app will be named back to Firefly when we deprecate V1.

### Requirements

- [ ] Modify the logo for Firefly (Stardust) so that we can distinguish between the two apps
- [ ] Provide logo for alpha, beta and prod apps
- [ ] Provide logo in all formats needed

### Acceptance criteria

Logo approved by Andrew / Charlie
All versions supplied

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
