### ISSUE TITLE
[Task]: Design reject confirmation popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3641]
### Task description

We we would like a confirmation popup before a user rejects a transaction as it is a destructive operation. We may also use this popup to allow the user to select the rejection type, being hiding the activity locally or returning the transaction.

### Requirements

- [ ] Confirmation popup
- [ ] Confirmation with togglable choice

### Acceptance criteria

Reviewed and approved by Nicole

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
