### ISSUE TITLE
[Task]: Design activity filter button and menu

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3642]
### Task description

We would like to be able to filter the activity list in various ways. We need a generic design for a filter button and menu, which will contain some initial filters.

Initial filters can be:
- Direction
  - In
  - Out
- Hidden
 - True
 - False
- Status
  - Pending
  - Included
  - Failed
- Async status
  - Expired
  - Claimed
  - Unclaimed
- Type
  - Internal
  - External

### Requirements

- [ ] Filter Button
- [ ] Filter menu
- [ ] Example of filters for various types of data

### Acceptance criteria

Approved by Nicole

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
