### ISSUE TITLE
[Task]: fix account color update

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3669]
### Task description

Account color inside the top navigation doesn't change when updated through the wallet customisation:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/6748220/175247682-d9d017a5-e29b-4542-b051-62e26b8c6d01.png">

### Requirements

- [ ] Account color in the top navigation is updated when changed by wallet customisation

### Acceptance criteria

Can be closed when the requirement is complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
fyi this also happens in desktop
