### ISSUE TITLE
[Task]: Remove milestoneIndex from expiration times

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3672]
### Task description

Remove the use of milestoneIndex from expiration times where ever it is used.

### Requirements

- [x] Locate any use of milestoneIndex from expiration time of an output
- [x] Remove any uses

### Acceptance criteria

PR merged and approved

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
https://github.com/iotaledger/wallet.rs/pull/1205
