### ISSUE TITLE
[Task]: Fix settings view for mobile beta

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3699]
### Task description

TBD

### Requirements

- [ ] Last Element in the list is always clickable
- [ ] Elements should only be highlighted when clicked

### Acceptance criteria

Can be closed when all requirements are completed.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
