### ISSUE TITLE
[Task]: Align profile menu design as figma

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3700]
### Task description

![image](https://user-images.githubusercontent.com/6748220/175545085-ab5f221b-61d7-453b-90e9-31bfa4e0bae7.png)

### Requirements

- [x] Background color adjusted 
- [x] Font colors adjusted
- [x] Works on Android
- [ ] Works on iOS

**Comment by begonaalvarezd** [comment]
Discuss about the backgound color, the current mobile implement doesnt make this update very easy

**Comment by begonaalvarezd** [comment]
@jeeanribeiro we should only add the borders to the buttons, other UI changes should be ignored 🙏🏼
