### ISSUE TITLE
[Task]: Align drawers to the mobile beta design

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3701]
### Task description

TBD

### Requirements

- [ ] Keyboard is always open (send and receive)
- [ ] Drawers are full-size (send, receive and add wallet)
- [ ] Drawer headers are centered

### Acceptance criteria

Can be closed when all requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
closed as duplicated
