### ISSUE TITLE
[Task]: Adjust content lift

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3703]
### Task description

TBD

### Requirements

- [ ] Background fade is still visible when the content is lifted up
- [ ] Buttons do not scale 

### Acceptance criteria

Can be closed when all requirements are complete

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
