### ISSUE TITLE
[Task]: Release @iota/wallet npm package

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3708]
### Task description

Release the @iota/wallet package under the IF

- [x] #3723

### Requirements

- https://github.com/iotaledger/wallet.rs/pull/1213
- https://github.com/iotaledger/wallet.rs/pull/1204

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
