### ISSUE TITLE
[Task]: Polish send transaction flow

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3713]
### Task description

Fix and polish the send flow:

### Requirements

- [x] Content can not be swiped
- [ ] Add illustrations/animations (also for dark mode)
- [x] Move progress bar to confirmation
- [x] Add back buttons
- [x] Align confirmation to figma design
- [x] Displays each step in the same drawer (Send, confirmation, password)
- [x] Closes the send flow drawer after transaction is sent
- [x] Displays the activity tab after transaction is sent
- [x] Works on iOS
- [x] Works on Android

### Acceptance criteria

All requirements are complet.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
the drawer changes are in my currnet task

**Comment by paul-boegelsack** [comment]
> the drawer changes are in my currnet task

Alright, removed the Drawer stuff.
