### ISSUE TITLE
[Task]: Set profile circle color always to blue

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3714]
### Task description

Currently the profile initial circle is set to change color based on the selected wallet, but the profile color is not dependent on the wallet color, but rather on the profile color which perhaps can change in the future (or have an profile image with NFTs)

Components that need update:
- ![image](https://user-images.githubusercontent.com/3624944/175982198-8f1d6ebc-aae6-4ec6-a8c1-aa16fed8619f.png)
- ![image](https://user-images.githubusercontent.com/3624944/175982244-ac26a40f-2ca2-44a8-884c-ed13c36b20ae.png)

### Requirements

- [ ] Update top left profile
- [ ] Update profile drawer

### Acceptance criteria

Meets the above requirements

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
