### ISSUE TITLE
[Task]: Make changes to Snyk CI

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3744]
### Task description

Removing Snyk dependency checks from pull requests.

### Requirements

- [x] Remove workflow from pull requests
- [x] Add for on `push` to branches: `develop`, `stardust-develop`

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
