### ISSUE TITLE
[Task]: fix trying to set the pin without profile id

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#3761]
### Task description

We need to fix the `Error: Error invoking remote method 'keychain-set': Error: Account is required.`
The error is happening when the user is creating the first profile but the profile id was never being set and it is used as a param for the keychain key

### Requirements

TBD

### Acceptance criteria

- [x] create the first new profile successfully

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
