### ISSUE TITLE
[Task]: New wallet tab layout without charts

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3807]
### Task description

Because we currently have no reliable data to produce any charts, we are going to rearrange the dashboard layout so that we don't have too much white space.

### Requirements

- [ ] Move activity to right panel
- [ ] Move assets to middle panel
- [ ] Move recieve form to panel below balance

### Acceptance criteria

PR approved and merged into stardust-develop

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
