### ISSUE TITLE
[Task]: Fix ux of delete account flow

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3810]
### Task description

Currently the delete account flow needs some polishing

### Requirements

- [ ] Re-open popup when password has been input
- [x] Show busy state until delete has occurred
- [x] Only allow delete account, if its the last account and it has 0 balance
- [x] Show errors in popup
- [x] Fix button width and overall style on popup if needed

### Acceptance criteria

PR approved and merged

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
"Re-open popup when password has been input"
 It isn't necessary because the password input is already inside the delete account popup
