### ISSUE TITLE
[Task]: Replace vote ID with shimmer supply one

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3820]
### Task description

Before building and releasing the official 1.6.3 release candidate, we need to change the hard-coded voting event ID.

### Requirements

- [ ] Change the `TREASURY_VOTE_EVENT_ID` constant in `shared/lib/participation/constants.ts`
- [ ] Try to test with actual mainnet profile (see when nodes will be updated)

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
