### ISSUE TITLE
[Task]: Fix activity logic for determining internal transaction

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3837]
### Task description

Currently the logic to determine if an activity is internal is only based off checking the recipient address, so all incoming transactions are marked internal and shown as internal. We need to update the logic.

### Requirements

- [ ] If the activity is incoming, mark as internal only if the sender address is known to be one of our accounts.
- [ ] If the activity is outgoing, mark as internal only if the recipient address is known to be one of out accounts.
- [ ] In all other cases the activity should not be marked as internal.

### Acceptance criteria

PR approved and merged into stardust develop.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
