### ISSUE TITLE
[Task]: Fix password not being asked for before claiming a transaction

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3838]
### Task description

We have a bug where the password is not being checked if stronghold is unlocked before attempting to claim a transaction.

### Requirements

- [x] Ensure we are checking the password before claiming a transaction.

### Acceptance criteria

PR approved and merged.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
