### ISSUE TITLE
[Task]: Implement Shimmer claiming profile manager 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3841]
### Task description

We need to figure out a clean way to expose an IOTA-based profile manager whenever the user wanting to claim Shimmer rewards to create a new profile.

### Requirements

- [x] Determine best way to instantiate the profile manager and how / what to expose for it (in `preload.js`)
- [x] Determine best way to update the IOTA profile manager's state with the Shimmer one used throughout the onboarding
- [x] Test by generating address with IOTA profile manager

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
