### ISSUE TITLE
[Task]: Implement `findShimmerRewards`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3842]
### Task description

The functionality to find the Shimmer rewards will be required in order to claim tokens, so it should be implemented first.

### Requirements

- [x] Implement main functionality
- [x] Implement necessary logic for...
    - [x] Simple non-zero account / address indices
    - [x] Non-zero indices with already claimed funds (although **ONLY** unclaimed funds really matter)
    - [x] ~~High-index accounts and addresses with unclaimed rewards~~ (will be handled in #4297)
- [x] Split `Unclaimed` state into `UnclaimedWithRewards` and `UnclaimedWithoutRewards` (else scenario no. 5 can't continue, or any other scenario with an account gap)
- [x] Fix calculation logic for rewards found (can repro with scenario no. 5, only wrong the first time because if unclaimed rewards are found during the initial search then the next found balance with think those funds are also new)
- [x] Fix claimed rewards state for all accounts (not just first one)
- [x] Fix account aliases when finding rewards
- [x] Add notification after each successfully claimed wallet, also make sure it occurs after sync
- [x] Add notification for if funds are found on initial search on view load
- [x] Ensure syncing is only for basic outputs
- [x] Add locale entries as necessary
- [x] Add logic to complete onboarding flow 
- [x] Ensure correct error handling for single wallet failures (continue claiming other wallets, let user re-try after)
- [x] Ensure that profile is created with correct number of wallets
- [x] Ensure that subsequent Stronghold backup properly restores all claimed wallets

#### Unclaimed

1. Unclaimed Shimmer tokens on one account (index `0`) and one or more addresses (index `0`)
2. Unclaimed Shimmer tokens on one account (index `0`) and one or more addresses (index `1+`)
3. Unclaimed Shimmer tokens on one account (index `1+`) and one or more addresses (index `0`)
4. Unclaimed Shimmer tokens on one account (index `1+`) and one or more addresses (index `1+`)
5. Unclaimed Shimmer tokens on many accounts (index `0-n`) and one or more addresses (index `0`) for each account
6. Unclaimed Shimmer tokens on many accounts (index `0-n`) and one or more addresses (index `1+`) for each account
7. Unclaimed Shimmer tokens on many accounts (index `1-n`) and one or more addresses (index `0`) for each account
8. Unclaimed Shimmer tokens on many accounts (index `1-n`) and one or more addresses (index `1+`) for each account

#### Partially Claimed

1. Above scenarios 1-8 except some Shimmer tokens have already been claimed on only one account (random index)
2. Above scenarios 1-8 except some Shimmer tokens have already been claimed on more than one account
3. Above scenarios 1-8 except all Shimmer tokens have already been claimed on only one account (random index)
4. Above scenarios 1-8 except all Shimmer tokens have already been claimed on all accounts
5. Any of the above with a Ledger device where there are too many outputs

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
