### ISSUE TITLE
[Task]: Downgrade Electron version 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3849]
### Task description

Due to issues with the development environment, we want to try downgrading Electron versions. 

### Requirements

- [x] Determine what version to downgrade to (previous version or in-between previous and current version?)
- [x] Make changes as necessary to downgrade versions
- [x] Ensure general app functionality is working
- [x] Ensure development environment isn't in a broken state

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
