### ISSUE TITLE
[Task]: Fix login crash when changing profile

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3855]
### Task description

The app crashes on iOS after sign out through settings and then sign in with a different profile.

### Requirements

- [x] Works on iOS

### Acceptance criteria

TBD

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
Xcode log:
![Image](https://user-images.githubusercontent.com/6748220/178470382-ab52f0ef-fe6f-43ce-bd77-441e68fb0868.png)

Maybe a problem with the bindings?

**Comment by amadeu2** [comment]
Exactly was the bindings again 😆 I think I've just solved it, will push the PR 💪

**Comment by amadeu2** [comment]
I'll upload a new internal release to apple store so we can test it well.

**Comment by paul-boegelsack** [comment]
Tested with my SE the account creation and profile change after login. Works now as intended. Really nice job! 💯 🥇 @amadeu2
