### ISSUE TITLE
[Task]: Assembly staking event no. 3 release

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3878]
### Task description

There are a few things that need to be changed for the new staking event to run smoothly in Firefly.

### Requirements

- [x] Update `ASSEMBLY_EVENT_ID` constant with new event ID
- [x] Update `ASSEMBLY_EVENT_START_DATE` with new starting date (e.g. "April 22, 2022")
- [x] Add JSON file url to `ASSEMBLY_STAKING_RESULT_URLS` array
- [x] Update `CURRENT_ASSEMBLY_STAKING_PERIOD` and `LAST_ASSEMBLY_STAKING_PERIOD`
- [x] Update `ASSEMBLY_REWARD_MULTIPLIER` to `1.0` 
- [x] Update external URLs (e.g. blog posts, tutorials) as necessary
- [x] Increment the Firefly Desktop version to `1.6.4`

### Subtasks

- #3959 
- #3961 

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
