### ISSUE TITLE
[Task]: Add reactivity to Popup component

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#3894]
### Task description

Currently popups don't update if the store variable updates. 
A tester reported that after claiming a transaction and keeping the popup open, the transaction in the background changed to `claimed` but the popup didn't.
Another example would be the `isClaiming` logic. Instead of using the `isClaiming`property of the `activity`, we need to calculate it in the `ActivityDetailsPopup` to add reactivity.

### Requirements

-

### Acceptance criteria

- [ ] add reactivity to Popups
- [ ] simplify each current workaround for reactivity

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
