### ISSUE TITLE
[Task]: Receiver address not updated after selection

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#3895]
### Task description

On SendForm, if i select an internal wallet, and then change it to some bech32 address, the next step still contains the previously selected wallet

### Requirements

-

### Acceptance criteria

- [ ] after changing the receiver address, the receiver should also be changed in SendConfirmation 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
