### ISSUE TITLE
[Task]: Analyse issue with wallet creation

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#3897]
### Task description

On new wallet creation, a tester reported the following error: https://media.discordapp.net/attachments/998627792717627443/998826676928659456/unknown.png?width=857&height=617

https://discord.com/channels/397872799483428865/998627792717627443/998874273454239774

I tried to find where we call the `split` function on a string, but could not find anything. A deeper analysis is needed

### Requirements

-

### Acceptance criteria

- [x] Find the potential point of failure
- [x] Either fix the error, or show a better errormessage

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
I see that the main problem is about the different error types that we have across the code, and some are not localized, I have found a quick solution for displaying the error message but I think that we could have an error handler helper function to reduce some boilerplate code and reduce the incompatibility of error types
