### ISSUE TITLE
[Task]: Remove crash reporting setup from onboarding

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3913]
### Task description

It's more commonplace to have crash reporting turned on by default, which allows us to remove the crash reporting view from onboarding.

### Requirements

- [ ] Remove the view from the onboarding flow
- [ ] Make the default setting for this `true`
- [ ] Update the Privacy Policy to reflect this change

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
