### ISSUE TITLE
[Task]: Improve `error` module and general error handling

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3916]
### Task description

The error handling could be improved a little bit further.

### Requirements

- [x] Separate console logging and storing error in `errorLog` store
- [x] Add new parameters: `localizeMessage`
- [x] Move `errorLog` to `error` module
- [x] Move `Error` type to `error` module and rename to `IError`
- [x] Cleanup existing code in `error` module
- [x] Add annotation comments
- [x] Move non-specific errors to corresponding module

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
