### ISSUE TITLE
[Task]: Update specification and coding conventions in handbook

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3917]
### Task description

The handbook has fallen slightly out of date with the recent changes we've made.

### Requirements

- [x] Update page names in coding conventions guide to "Components" and "Modules"
- [x] Consider adding page specifically for code components (e.g. functions, enums, etc.) - would be able to display more info in a more organized way rather than having "Modules" be a huge list
- [x] Polish "Modules" coding conventions page and add more information
- [x] Add specification page for "Modules" (name TBD)
    - [x] Include info about difference between `core`, `contexts`, and `auxiliary`
    - [x] Add descriptions for each module within each category
- [x] Update version to `v2.0.0-beta`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
