### ISSUE TITLE
[Task]: Create `wordlists` auxiliary module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3920]
### Task description

This will help cleanup the shared library's root directory.

### Requirements

- [x] Create `wordlists` module inside of `shared/lib/auxiliary/`
- [x] Move all wordlists inside newly created module

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
