### ISSUE TITLE
[Task]: Move `deep-link` module to `shared/lib/auxiliary/` directory

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3921]
### Task description

This is necessary since `shared/lib/common/` will no longer be a directory of modules.

### Requirements

- [x] Move `deep-link` module to `shared/lib/auxiliary/`
- [x] Delete `shared/lib/common/` directory
- [x] Remove path alias for `@common`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
