### ISSUE TITLE
[Task]: Update shimmer and firefly websites to include stardust releases

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3942]
### Task description

We need to update both shimmer and firefly websites to include firefly stardust versions. 
Additionally, we need to update the YML file to include desktop stardust versions along with desktop stardust versions

### Requirements

- [x] #3943
- [ ] Add download firefly banner to shimmer website (automate with fetched YML)
- [ ] Update firefly website to distinguish between desktop chrysalis & stardust (automate with fetched YML)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
