### ISSUE TITLE
[Task]: Add metadata to native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3945]
### Task description

We need to support metadata for native tokens that follow TIP30 Native token metadata standard.

### Requirements

TBD

- [x] #3953
- [x] #3957
- [x] #3955
- [x] #3982

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
