### ISSUE TITLE
[Task]: Modify transaction details UI for native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3946]
### Task description

We need to modify transaction details to work with native tokens

### Requirements

- [x] Add asset icon to transaction details
- [x] Polish sizing and spacing of components

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
