### ISSUE TITLE
[Task]: Modify activity tile UI for native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3947]
### Task description

We need to update the activity tile to show native tokens information.

### Requirements

- [x] Ensure unit and display properties are used
- [x] Show asset icon instead of direction icon

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
