### ISSUE TITLE
[Task]: Update Shimmer Reward display to correct denomination

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#3959]
### Task description

In the current Firefly production version we use the old SMR denominations for SMR rewards.

### Requirements

- [x] Denominations should match the Stardust Beta app, according to [TIP-0032](https://github.com/iotaledger/tips/blob/shimmer-params/tips/TIP-0032/tip-0032.md#shimmer-units)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
