### ISSUE TITLE
[Task]: Cleanup repository `README`s

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3960]
### Task description

README could be updated / polished.

### Requirements

- [x] Add link to handbook in main README

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
