### ISSUE TITLE
[Task]: Fix display of ASMB / SMR staking rewards

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3961]
### Task description

Most of the recent and current help requests are related to SMR / ASMB balances not being shown correctly.

### Requirements

- [x] Reproduce bug or find reliable steps that cause it

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
