### ISSUE TITLE
[Task]: Refactor `utils` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3964]
### Task description

The `utils` module needs to be cleaned up and refactored with submodules. 

Currently all of the functionality is contained within `shared/lib/utils.ts`, but it could be broken up according to the following requirements.

### Requirements

- [x] #3965
- [x] #3966
- [x] #3967
- [x] #3968
- [x] #3969
- [x] #3970
- [x] #3971
- [x] #3972
- [ ] ~~#3973~~

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
