### ISSUE TITLE
[Task]: Refactor `popup` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#3974]
### Task description

The existing logic for popups needs to be moved to a new `popup` module in `lib/auxiliary/popup`.

### Requirements

- [x] Create `popup` module in `lib/auxiliary/popup`
- [ ] ~~Consider changing popup `type` to `name` since "type" could also refer to something else (also leaves it open for us to make distinct types of popups`)~~
- [ ] ~~Add `PopupType` (if `type` wasn't renamed, otherwise `Popup`) enum so we don't use hard-coded strings everywhere~~
- [x] Add logic and stores from old popup file (`lib/popup.ts`) to new module
- [x] Add types (`lib/typings/popup.ts`) from old popup file to new module
- [x] Update [handbook specification](https://iotaledger.github.io/firefly/specifications/modules/#auxiliary) as necessary
- [ ] ~~(Opt.) Create a specification page in the handbook detailing popups and how they work / how they're used~~

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
