### ISSUE TITLE
[Task]: Add mint native token feature

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3995]
### Task description

We would like to be able to mint native tokens in the firefly app for the beta app when in developer mode. This would also require creating the initial developer tools tab.

### Requirements

- [x] Create developer tools tab
- [x] Add button to mint native tokens
- [x] Add form to to set native token options following irc30 standard
- [x] Add action mint token
- [x] Add error handling to minting tokens
- [ ] Add success notification when mint transaction issued
- [x] Auto verify tokens you minted

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
