### ISSUE TITLE
[Task]: Add faucet button in firefly developer tools

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3996]
### Task description

To make it super easy to use the developer network, specifically during the beta we can add a button to directly request funds from the testnet faucet.

### Requirements

- [x] Add button to request funds from developer tools tab
- [x] Add popup to confirm request
- [x] Add action to request funds
- [x] Whitelist url
- [x] Add error handling
- [x] Add success notification
- [x] Update notification style
- [x] Add url to network constant

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
