### ISSUE TITLE
[Task]: Add token minting to the activity list

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3997]
### Task description

We want to show in the activity if you minted tokens, we can do this when you mint through firefly or attempt to determine it from a transaction contents.

### Requirements

- [x] Add minting token activity when issuing minting transaction.
- [x] Determine minting token activity given a transaction

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
