### ISSUE TITLE
[Task]: Use initials for token icon if logo is not available

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3999]
### Task description

We need should use the initials or the symbol to create an icon for tokens where the logo is not available or not displayable.
We will limit this to 5 characters.

### Requirements

- [ ] If logo not available add initials or symbol as the icon
- [ ] Change text size depending on length
- [ ] Give a token a random colour when we persist the metadata

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
