### ISSUE TITLE
[Task]: Update `@iota/wallet` to alpha.10

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4004]
### Task description

New version of `@iota/wallet` is out we need to update

### Requirements

- [ ] Update @iota/wallet version
- [ ] Fix any breaking changes

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
