### ISSUE TITLE
[Task]: Fix profile corruption after deleting a wallet

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4006]
### Task description

Profile was corrupted after I deleted a wallet and logged out and in.

### Requirements

- [x] Find cause
- [ ] Fix issue

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Waiting on fix in wallet.rs https://github.com/iotaledger/wallet.rs/pull/1369

**Comment by nicole-obrien** [comment]
Retested and now fixed
