### ISSUE TITLE
[Task]: Hide activity based on native tokens that don't follow IRC30

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4007]
### Task description

We should hide the activity or show it as unknown token if the activity is regarding a token that doesn't follow the supported standards. i.e. IRC30

### Requirements

- [ ] Hide activity based if native token metadata does not exist.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
