### ISSUE TITLE
[Task]: Cleanup funds spreader and move to `stardust-tools`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4012]
### Task description

:warning: This task is no longer relevant for this repository. It will be in [`stardust-tools`](https://github.com/maxwellmattryan/stardust-tools) instead.

There is currently no way to comprehensively test all scenarios for claiming Shimmer rewards. We need a tool that can easily and reliably create the account and address spaces that we need to test.

### Requirements

- [x] Create new `tools` directory in main repository
- [x] Write simple TS script for setting up a single test scenario 
- [x] Extend script for multiple test scenarios (detailed below)
- [x] Change `FAUCET_URL` to `SHIMMER_FAUCET_URL` and `NODE_URL` to `SHIMMER_NODE_URL`
- [x] Use proper path resolution
- [ ] Add handbook page for tool
- [ ] Make sure accounts are at the correct index

### Test scenarios

1. Unclaimed Shimmer tokens on one account (index `0`) and one or more addresses (index `0`)
2. Unclaimed Shimmer tokens on one account (index `0`) and one or more addresses (index `1+`)
3. Unclaimed Shimmer tokens on one account (index `1+`) and one or more addresses (index `0`)
4. Unclaimed Shimmer tokens on one account (index `1+`) and one or more addresses (index `1+`)
5. Unclaimed Shimmer tokens on many accounts (index `0-n`) and one or more addresses (index `0`) for each account
6. Unclaimed Shimmer tokens on many accounts (index `0-n`) and one or more addresses (index `1+`) for each account
7. Unclaimed Shimmer tokens on many accounts (index `1-n`) and one or more addresses (index `0`) for each account
8. Unclaimed Shimmer tokens on many accounts (index `1-n`) and one or more addresses (index `1+`) for each account
9. Scenarios 1-8 except some Shimmer tokens have already been claimed on only one account (random index)
10. Scenarios 1-8 except some Shimmer tokens have already been claimed on more than one account
11. Scenarios 1-8 except all Shimmer tokens have already been claimed on only one account (random index)
12. Scenarios 1-8 except all Shimmer tokens have already been claimed on all accounts
13. Any of the above with a Ledger device where there are too many outputs

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
