### ISSUE TITLE
[Task]: Update wallet dependency with breaking changes for beta.2

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4015]
### Task description

There is going to breaking changes in the api deployed to the beta network shortly so we need to update to the latest wallet dependency when it is available.

### Requirements

- [ ] Update to latest wallet dependency

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
