### ISSUE TITLE
[Task]: Error handling when there is no synced node available

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4019]
### Task description

Currently the app blocks when trying to login with no synced node available. We should need to allow login and show an error message.

### Requirements

- [ ] Show notification when node is not synced or online
- [ ] Dont prevent login when node is unavailable.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Close because duplicate of general error handling in login
