### ISSUE TITLE
[Task]: Add explanatory tooltip about SMR formatting

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4025]
### Task description

With changes to the SMR denomination and formatting, we need an explanatory tooltip to help clear any confusion for users.

### Requirements

- [x] Add tooltip to SMR asset tile in wallet dashboard
- [x] Add new locale text

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
