### ISSUE TITLE
[Task]: Change mechanism to access staking result JSON files

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4029]
### Task description

We need to store the files locally, as to help reduce the amount of network requests being made to GitHub, S3, etc.

### Requirements

- [ ] ~~Link files from other repository~~
- [x] Add files into library (`shared/lib/participation/results/staking/`) for easy accessibility
- [x] Replace code to query the URLs with code that fetches the local files

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
