### ISSUE TITLE
[Task]: Add feature flags for developer tools

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4031]
### Task description

Now we have the developer tools tab, we should add feature flags for it.

### Requirements

- [x] Add feature flags for dev tools
- [x] Move context feature flags to there own file

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
