### ISSUE TITLE
[Task]: Add token metadata load and verification in the receive and claim flow.

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4032]
### Task description

We need to get the token metadata and start the verification process when we receive tokens that need to be claimed.

### Requirements

- [ ] When output received add asset for token
- [ ] When verification status of transaction is new then display the asset popup with verify button instead of activity details popup
- [ ] If on asset popup after clicking activity popup, clicking skip or verify should route you to the activity popup.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
