### ISSUE TITLE
[Task]: Fix asset dropdown is squished when asset name has multiple words

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4033]
### Task description

When on the send form, when you select an asset if it has multiple words as part of its name it will change the height of the asset dropdown and squish the icon.

### Requirements

- [ ] Truncate asset names with multiple words so that it doesn't look squished in the dropdown when selected.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
