### ISSUE TITLE
[Task]: Enhance the asset information popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4034]
### Task description

We should make it easier for people to copy the token information such as the asset id and the url.

### Requirements

- [x] Make url copyable on asset info popup
- [x] Make asset if copyable on asset info popup
- [x] Add the standard to the asset info popup
- [x] Add the url for the shimmer token
- [x] Align the actions menu in the correct place

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
