### ISSUE TITLE
[Task]: Fix scroll bar style for assets panel

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4035]
### Task description

We should match the scroll bar style to that of the activity panel where it takes up less space and doesn't jolt when it is added.

### Requirements

- [ ] Copy scroll bar styles from activity panel to asset panel

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
