### ISSUE TITLE
[Task]: Update styles for text hint

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4039]
### Task description

WE now have updated styles for text hints to make the consistent across the app.

### Requirements

- [ ] Update text hint styles

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
