### ISSUE TITLE
[Task]: Only show unverified badge when verification status is new

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4048]
### Task description

We should only show the question mark badge if the token is new and the user has not skipped or verified the token.

### Requirements

- [ ] Remove verification badge from token when status is unverfiied.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
