### ISSUE TITLE
[Task]: Fix minting validation in minting

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4054]
### Task description

Some of the validation functions aren't working because the number is somehow in a string format.

### Requirements

- [ ] Fix validation by casting to number

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
