### ISSUE TITLE
[Task]: Use Asset Icon in Asset dropdown

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4063]
### Task description

Still using the old icon in the asset dropdown, we should replace with the AssetIcon component.

### Requirements

- [ ] Use asset icon in asset dropdown
- [ ] Fix dark mode colours

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
