### ISSUE TITLE
[Task]: Add search to asset dropdown on send form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4100]
### Task description

It would be easier to find your tokens if the user could type them in.

### Requirements

- [ ] Add search to the asset dropdown

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Added to the new sendflow in https://github.com/iotaledger/firefly/pull/6705
