### ISSUE TITLE
[Task]: Improve ui of asset dropdown

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4101]
### Task description

It would be good to increase the height of the asset dropdown so that you can see more tokens at once? May the tiles here are too big? Do we need to see the second row with the translations on here? Can we replace the tile with a menu item?

### Requirements

- [x] Increase max height
- [x] Remove conversions
- [ ] Use menu item same as other dropdowns etc? Such as the recipient input?
- [x] Don't reset amount when asset is selected from dropdown

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
