### ISSUE TITLE
[Task]: Fix login issue `ClientError(MissingParameter("Node"))`

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4110]
### Task description

Some profiles are no longer able to login because they don't have any nodes in the persisted client options. The client options where passed into the initialise profile manager every-time because wallet.rs corrupted them after a breaking change. But somehow the node is being deleted from the persisted storage.

### Requirements

- [x] Prevent profile crashing
- [x] Fix already crashed profiles that don't have a node

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by ericvrp** [comment]
This also happens sometimes to newly added profiles after app restarts.
