### ISSUE TITLE
[Task]: Add gift storage deposit option when sending native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4115]
### Task description

Some systems such as soonaverse do not have the means to manage outputs with additional unlock conditions such as SDRUC. Therefore, to help them out we can add gift storage deposit feature so that users can send transactions without this unlock.

### Requirements

- [x] Add gift storage deposit checkbox to send confirmation page
- [x] Add logic to gift storage deposit

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
