### ISSUE TITLE
[Task]: Add confirmation popup and error handling for minting native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4117]
### Task description

We should copy the flow of sending considering we are technically sending a when minting we should add  a confirmation page with error handling.

### Requirements

- [x] Confirmation page for minting flow
- [x] Error handling

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
