### ISSUE TITLE
[Task]: Refactor loading screen into a view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4120]
### Task description

Right now the loading screen is a popup that displays in certain situations depending on some stores. This is hard to debug and leads to some behaviour where it can close or not open when we want it to.

### Requirements

- [x] Make loading screen a view
- [x] Navigate to this during login
- [x] Navigate from this after everything has loaded.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
I would make a generic loading component and then a statefull logging in view that determines when to move on during login / recovery.
