### ISSUE TITLE
[Task]: Adjust app crash reporting logic

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4121]
### Task description

There are some changes to crash reporting for the app.

### Requirements

- [ ] Remove the "Crash Reporting" view from all onboarding flows
- [ ] Enable `sendCrashReports` by default everywhere
- [ ] Update Privacy Policy and Terms of Service as needed

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
