### ISSUE TITLE
[Task]: Create filter component for assets list

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4128]
### Task description

We want to be able to filter native tokens by various conditions. So we need to add a filter menu to the assets list.

### Requirements

- [x] #4073
- [x] #4075

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
