### ISSUE TITLE
[Task]: Fix ordering of activity list groups

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4130]
### Task description

Currently activities are grouped into lists and each list is in reverse chronological order, so that the newest items are at the top. However, the groups themselves appear to be in chronological order so that the oldest is displayed first at the top.

### Requirements

- [ ] Under groups in activity list so that the newest is at the top.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
