### ISSUE TITLE
[Task]: Make groups in activity list collapsible

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4131]
### Task description

To make it easier to navigate the activity list we should make the activity feed groups collapsible.

### Requirements

- [ ] Design collapsible group
- [ ] Implement collapsible group

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
