### ISSUE TITLE
[Task]: Improve claiming flow to show pending state

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4134]
### Task description

Because claiming an output issues a new transaction we should keep the activity in a pending claim state until the claiming transaction is confirmed. Otherwise the transaction look confirmed straight away and there could also be a conflict.

### Requirements

- [x] Keep activity in claiming state until the claiming transaction has been confirmed

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
