### ISSUE TITLE
[Task]: Close recipient input when clicking away from it

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4135]
### Task description

Recipient input doesn't close when you clickoutside the input or menu which means it can remain open when you open the asset dropdown.

### Requirements

- [x] Close recipient input when clicking outside of it

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
