### ISSUE TITLE
[Task]: Improve rendering speed of wallet tab by using virtual list

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4142]
### Task description

The wallet tab is currently slow to render when you have many assets or activities. This is because it is rendering 100s of items of screen. We could use something like https://github.com/sveltejs/svelte-virtual-list to speed up the rendering.

### Requirements

- [x] Add virtual list to the dependencies
- [x] User virtual list in the assets list
- [x] Use virtual list in the activity list

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
