### ISSUE TITLE
[Task]: Fix padding of asset and activity list

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4161]
### Task description

The padding of the asset and activity list seems to be broken when there is only a small number of items as to not show the scroll bar.

### Requirements

- [x] Fix padding on asset and activity list so there is the same padding with and without scroll bars and the scroll bar is placed in the gap of the padding instead of moving it.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
