### ISSUE TITLE
[Task]: Refactor network configuration settings

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4165]
### Task description

Currently we do not support many of the old network settings just away to add more nodes and all will be used in a pool. We should refactor the network config settings to make it better and allow primary nodes.

### Requirements

- [ ] Refactor app logic out of network settings
- [ ] Improve ui if needed
- [ ] Remove automatic option
- [ ] Allow setting primary node

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
