### ISSUE TITLE
[Task]: Fix file import view for Windows

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4190]
### Task description

When dragging and dropping a file into this view, it does **NOT** update correctly to show what file has been selected.

### Requirements

- [ ] Make sure that chosen file is displayed once either dropped in or selected via file explorer window

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by VmMad** [comment]
It works fine when dropping/selecting a correct stronghold file on Windows 11
