### ISSUE TITLE
[Task]: Refactor `router` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4199]
### Task description

The `router` module was one of the first modules to be created in the initial refactoring effort. There have since been updates to the conventions, and it is time to revisit this particular module.

### Requirements

- [ ] Create `classes` directory for `router.ts` and `subrouter.ts` (also rename `router.class.ts` and `subrouter.class.ts` respectively)
- [ ] Make new `routers` directory for `app-router.ts`, `dashboard-router.ts`, `onboarding-router.ts`, and `settings-router.ts`
- [ ] Rename all filenames to adhere to `NAME.router.ts` rather than `NAME-router.ts`
- [ ] Expand `helper.ts` file into `helpers` directory with multiple files
- [ ] Remove `FireflyEvent` type (was mostly used for onboarding, but now only for a few things ... refactor!)
- [ ] Change `Sidebar` type to `ISidebar` interface (and move to better location, e.g. `app` module?)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
