### ISSUE TITLE
[Task]: Fix Stronghold-based restoration

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4200]
### Task description

There are some fixes needed for Stronghold-based restoration.

### Requirements

- [x] #4202
- [ ] #4203

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
@maxwellmattryan  Please can you check if this and its sub task are already complete?
