### ISSUE TITLE
[Task]: Update wallet and type dependencies to `2.0.2-alpha.14` and `^1.0.0-beta.11` respectively

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4205]
### Task description

Update to the latest dependencies to allow use of a breaking change in the nodes.

### Requirements

- [x] Update iota/wallet to `2.0.2-alpha.14`
- [x] Update iota/types to `^1.0.0-beta.11`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
