### ISSUE TITLE
[Task]: Reset profile state when changing profileSetupType

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#4212]
### Task description

In the createWallet flow, once the user gets past the `SetStrongholdPasswordView.svelte` stage and they then choose to go backwards in the flow to `SetupView.svelte` the profile state doesn't sufficiently reset. So if they change to a recoverWallet flow and try to recover via a mnemonic, then an error will be thrown:

```json
{
    "type": "ClientError",
    "error": "`invalid stronghold password`"
}
```

### Requirements

- [ ] Reset state when going backwards after verifying the mnemonic in the wallet creation flow

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Closed as bug is not present anymore.
