### ISSUE TITLE
[Task]: Add wallet activity type for Shimmer claiming transaction

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4217]
### Task description

We could improve the UX by showing a particular activity for Shimmer claiming transactions.

### Requirements

- [x] Figure out how to determine if a transaction was a Shimmer claiming one (done locally? using a tag?)
- [ ] Add new activity type for Shimmer reward claiming
- [ ] Display Shimmer reward claiming activities in wallet dashboard 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
