### ISSUE TITLE
[Task]: Fix logout after profile name changes

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#4222]
### Task description
After the profile name changes the app logs out from the profile automatically

### Requirements
- [ ] Find out the root cause of the logout after the profile name changes
- [ ] Fix the issue

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
