### ISSUE TITLE
[Task]: Event-based logic for Shimmer claiming

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4223]
### Task description

Although the flow is currently in a functional state, it will be more reliable to use logic based on outputs and transactions received from wallet events.

#### General

- [x] Add proper error handling when listener returns error
- [x] Refactor event listener subscription logic
- [x] Handle per specific app context (onboarding vs others)
- [ ] ~~Handle per specific profile type (Ledger vs Stronghold)~~
- [x] Consider creating `IWalletApiEventSubscriptionConfiguration` interface if too much
- [x] Ensure that any and all subscriptions are eventually unsubscribed
- [x] Make event handler functions consistent (parameter names, type / interface interface structures, code organization, etc.)
- [x] Change notion of `accountId` to `accountIndex` and use `number` instead of `string` type

#### Shimmer Claiming

- [x] Adjust logic to use `TransactionInclusionEvent` rather than syncing
- [x] Adjust logic for button spinner (just make UX better)
- [ ] ~~Implement syncing-based logic as fallback~~

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
