### ISSUE TITLE
[Task]: Parallelise loading of accounts

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4224]
### Task description

We should load accounts in parallel to save time when logging in.

### Requirements

- [x] Parallelise loading accounts
- [x] Parallelise loading activities

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
