### ISSUE TITLE
[Task]: Test mobile with staked funds & rewards

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4232]
### Task description

Test mobile with actively staked funds
- [ ] if user is actively staking, firefly should display the disclaimer
- [ ] earned rewards should display in the tokens tab
- [ ] earned rewards with warnings should display the warning like in desktop

### Requirements

all previous test cases are tested and successful, or fixed if necessary

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@jeeanribeiro we need this PR merged before we can test this https://github.com/iotaledger/firefly/pull/4276

**Comment by begonaalvarezd** [comment]
Closing issue as I already tested it, with the new bindings and my UI fixes in #4317 should work ok
