### ISSUE TITLE
[Subtask]: Update designs of green success checkmark icon

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4248]
### Task description

The green check mark currently in the codebase is slightly different than the one in the designs.

### Requirements

- [x] Adjust stroke weight of white checkmark (needs to be a pixel or two thicker) in `ConnectLedgerView.svelte`, `ShimmerClaimingAccountTile.svelte`, etc.)
- [ ] Remove duplicate SVG code if exists (see `status-success/error` and `success-check`, maybe `error-check`?)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
