### ISSUE TITLE
[Task]: Fix wallet finder

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4251]
### Task description

We seem to have broken the wallet finder when deleting an old function.

### Requirements

- [ ] Fix wallet finder
- [ ] Get assets and activities after running wallet finder

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
