### ISSUE TITLE
[Task]: Block zero value transactions on the send form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4257]
### Task description

We should block zero value transactions on the send form, as otherwise the validation rules are inconsistent and users think there is a bug.

### Requirements

- [x] Block zero value transactions 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
