### ISSUE TITLE
[Task]: Update wallet.rs to nodejs-binding-v2.0.2-alpha.16

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4259]
### Task description

Update wallet bindings to latest

### Requirements

- [x] Update @iota/wallet to 2.0.2-alpha.16

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
