### ISSUE TITLE
[Task]: Add timelock to activity

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4260]
### Task description

Even though we dont support sending with time locks in firefly, people could receive an output with a timelock and they would need to know that it is not part of there balance yet. This requires displaying to the user that an activity has a time lock on the activity tile and the activity popup.

### Requirements

- [x] Add timelock to activity class
- [x] Add timelock to activity tile
- [x] Add timelock to activity popup

### Creation checklist

- [ ] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
