### ISSUE TITLE
[Task]: Replace `invoke` calls with `send` where appropriate in the Electron API

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4269]
### Task description

We have been using `invoke` for all platform methods, when it is technically more appropriate to use `send` when the function is of the `void` type. 

See more [here](https://www.electronjs.org/docs/latest/tutorial/ipc#2-expose-ipcrenderersend-via-preload).

Thanks @Tuditi for pointing this out!

### Requirements

- [ ] Replace all uses of `invoke` with `send` where the function is not returning a value
- [ ] Test all functionality that uses any of the replaced code

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
