### ISSUE TITLE
[Subtask]: Add disabled props for sendConfirmation deep links

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4284]
- [x]  Add no back button prop to send confirmation form from deep link
- [x]  Add disable expiration time changes for send confirmation deep link
- [x]  Add disable gift storage deposit changes for send confirmation deep link
