### ISSUE TITLE
[Task]: Add official and self verified token status

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4290]
### Task description

We now have new icons for the token verification so we should update the verification statues and badges to accommodate this

### Requirements

- [x] Separate official and self verified token status
- [x] Use a dynamic list for official verified tokens
- [x] Update all icons to use new ones from figma

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
