### ISSUE TITLE
[Task]: Improve reward / balance finding algorithm

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4297]
### Task description

:x: Blocked until this [PR](https://github.com/iotaledger/firefly/pull/4631) is merged.

The balance finding algorithm (also used for finding unclaimed Shimmer rewards) could be slightly improved to help find rewards for more obscure account / address spaces.

### Requirements

- [x] Discuss improvements / better implementations for algorithm
- [ ] Document current, intermediate, and goal algorithm
- [x] Add logic to manage start address search index per account
- [ ] Add locale entry for finding rewards
- [x] Add sensible defaults for Stronghold vs Ledger 
- [ ] Change names of accounts to `claimingAccount` and `depositAccount` (?)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
