### ISSUE TITLE
[Task]: Fix back button issues in non-happy onboarding flows

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4298]
### Task description

There are some weird issues when going backwards in the onboarding flows, particularly when you get to `SetupView.svelte` in the profile setup subflow (the back button has to be clicked twice).

My initial guess is that there is a duplication in the subrouter's history

### Requirements

- [ ] Fix necessary back button double-click in `SetupView.svelte` when going backwards

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
I haven't been able to reproduce this one :thinking: @Tuditi @MarkNerdi @kraftjs if you guys have time, could you test this to try and either find repro steps or verify that it doesn't occur anymore?

**Comment by kraftjs** [comment]
#### I can replicate this issue via two paths by doing the following:
1. Add Profile option
2. Shimmer option in "Choose Protocol" view
3. Testnet option in "Choose Network" view
4. Restore Shimmer Profile option in "Setup a Shimmer Profile" view
5. Use Ledger Device option in "Recover Shimmer Profile" view
6. Back button to "Recover Shimmer Profile" view
7. Back button 2x to get back to "Set up a Shimmer Profile" view

<hr>

1. Add Profile option
2. Shimmer option in "Choose Protocol" view
3. Testnet option in "Choose Network" view
4. Claim Shimmer Staking Rewards option in "Setup a Shimmer Profile" view
5. Use Ledger Device option in "Claim Shimmer Staking Rewards" view
6. Back button to "Claim Shimmer Staking Rewards" view
7. Back button 2x to get back to "Set up a Shimmer Profile" view

This only happens for me when choosing the Ledger option, but it doesn't occur for the Ledger option in "Create a new Shimmer profile", only in "Claim Shimmer Staking Rewards" and "Restore Shimmer Profile"

**Comment by kraftjs** [comment]
Also happens when restoring a stronghold backup and getting to the "You have successfully recovered your backup message", then going back to the "Setup a Shimmer Profile view". It will then require two back clicks to reach "Choose network" view
