### ISSUE TITLE
[Task]: Add protection against restoring a Stronghold with the wrong coin type

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4299]
### Task description

If a user says they are restoring a Shimmer profile, but try to use an IOTA Stronghold they will be using the wrong coin type for that profile, **which could cause lots of confusion about where users' funds appear to be (BIP path with Shimmer coin type) and where they actually are (BIP path with IOTA coin type)**.

### Requirements

- [x] Add function to check that Stronghold backup is of the correct `coin_type` (need to access `account.meta.coinType` to know, use logic in [`restoreBackupForShimmerClaimingProfileManager`](https://github.com/iotaledger/firefly/blob/stardust-develop/packages/shared/lib/contexts/onboarding/actions/restoreBackupForShimmerClaimingProfileManager.ts#L19-L27))
- [x] Refactor the duplicate code
- [x] Add generic error notification locale for using the `wrongProtocol`

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
