### ISSUE TITLE
[Subtask]: Persist modal when clicking "Clear" for activity filters

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4300]
### Task description

When clicking "Clear" in the activity filter modal, it destroys the modal. We can slightly improve UX by persisting the modal since the user may want to apply a different set of filters or just one filter.

### Requirements

- [ ] Persist the modal when the user clicks on "Clear"

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
