### ISSUE TITLE
[Task]: Fix receiving an async transaction while offline does not show in activity feed

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4303]
### Task description

Sometimes receiving an async transaction while offline doesn't show in the activity feed until you logout and in a second time.

### Requirements

- [x] Investigate issue
- [x] Fix issues

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Created bug report on walletrs
https://github.com/iotaledger/wallet.rs/issues/1391
