### ISSUE TITLE
[Task]: Update `recoverAccounts` API method

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4310]
### Task description

There were some changes made to the `recoverAccounts` API method.

### Requirements

- [x] Update the function signature as needed
- [x] Update the `IProfileManager` interface

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
