### ISSUE TITLE
[Task]: Write Shimmer claiming documentation

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4318]
### Task description

It is worthy of documentation in the handbook.

### Requirements

- [x] Convert the current "Onboarding" page into a guide
- [x] Create new "Shimmer Claiming" page
- [x] Write about the following:
    - [x] Staking results and the genesis snapshot
    - [x] How the claiming transactions work
    - [x] What are `ShimmerClaimingAccount`s
    - [x] How Firefly handles two managers app-side 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
