### ISSUE TITLE
[Task]: De-bounce any buttons where double-clicking is problematic

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4319]
### Task description

There are a few places in the onboarding flows that need to be debounced to prevent errors from occuring when the user quickly double clicks the "Continue" button or whatever button calls the functionality then advances the view.

### Requirements

- [ ] Add de-bouncing to the following places:
    - [ ] `profile-backup/views/BackupStronghold.svelte`
    - [ ] `profile-recovery/views/ImportMnemonicPhraseView.svelte`
    - [ ] `profile-recovery/views/ImportStrongholdBackupView.svelte`
- [ ] Check all flows and add de-bounces as necessary

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
