### ISSUE TITLE
[Task]: Add Svelte store for per-profile Shimmer claiming transactions

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4329]
### Task description

This is needed so that the activities can be displayed in a more user-friendly way.

### Requirements

- [x] Add new type for new Svelte store
- [x] Add Svelte store for profile-based Shimmer claiming transactions
- [x] Add logic to remove data on profile deletion

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
