### ISSUE TITLE
[Task]: Add import rules to ESLint

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4339]
### Task description

In many files we have many import statements - it would be nice if these would be organized in a consistent way and forced by the linter.

### Requirements

- [ ] Add import rules to ESLint
- [ ] Ensure that auto-formatting works

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
