### ISSUE TITLE
[Task]: Make all error messages consistent

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4347]
### Task description

The newer error messages that have been added do not include any punctuation, so we need to either **1)** go through the old ones and remove punctuation or **2)** add punctuation to the new ones.

If we go with option 1, we should do so for all of the other locales to avoid translators doing most likely what will be unnecessary work.

### Requirements

- [ ] Decide on option 1 or 2
- [ ] Do it

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
