### ISSUE TITLE
[Task]: Update Ledger connection guide popup

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4348]
### Task description

The popup to guide users to make sure they can connect their Ledger is slightly outdated and needs to be touched up slightly.

### Requirements

- [ ] Remove any vertical or horizontal overflow
- [ ] Fix popup icon buttons
- [ ] Rename component to use `Popup` suffix 
- [ ] Make generic to work with IOTA or Shimmer Ledger apps

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by marc2332** [comment]
Closing because the listed requirements have already being updated.
