### ISSUE TITLE
[Task]: Polish mobile migration UI

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4378]
### Task description

- [ ] Remove dismiss option in balance toast 
![image](https://user-images.githubusercontent.com/3624944/187712003-8db1c1b4-812b-45d2-867e-46ccb12c632b.png)
- [ ] Add autoscroll in seed screen to read checksum 
![image](https://user-images.githubusercontent.com/3624944/187712159-30ae3b68-5b1f-4ab4-bc64-cb2ca2aaf8cb.png)
- [ ] Add bottom safearea to warning screen 
![image](https://user-images.githubusercontent.com/3624944/187712253-f5608795-d5e9-435f-96ef-1fd50d1777d2.png)

### Requirements

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
