### ISSUE TITLE
[Task]: Add async tx support for Ledger profiles

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4383]
### Task description

There is a little bit of logic to change in order to add support for async transactions with Ledger devices

### Requirements

- [ ] Abstract or cleanup logic so that it doesn't assume a software profile
- [ ] Add confirmation popup to accompany prompt on Ledger device (may have to create new handler logic)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
