### ISSUE TITLE
[Task]: Fix restoration logic for Stronghold Shimmer claiming flow

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4407]
### Task description

There are some slight adjustments needed for supporting older Stronghold files from Firefly V1.

#### Dev

- [x] Add logic to copy IOTA Stronghold backup file to profile location
- [x] Add error handling / UX for non-happy flows (see tests)

#### Tests

:heavy_check_mark: = Should work
:x: = Should **NOT** work (not possible, not allowed, etc.)

- [x] Chrysalis backup (IOTA) -> Shimmer claiming :heavy_check_mark: 
- [x] Chrysalis backup (IOTA) -> SMR profile restoration :x:
- [x] Stardust backup (IOTA) -> Shimmer claiming :heavy_check_mark: 
- [x] Stardust backup (IOTA) -> SMR profile restoration :x: 
- [x] Stardust backup (SMR) -> Shimmer claiming :heavy_check_mark:
- [x] Stardust backup (SMR) -> SMR profile restoration :heavy_check_mark: 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
