### ISSUE TITLE
[Task]: Ensure all non-transactional flows and functionality work with ledger

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4408]
### Task description

We need to go through the list and ensure any functionality that is not sending transactions still works when using a ledger profile over a software profile.

### Requirements

TODO:

- [ ] 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
