### ISSUE TITLE
[Task]: Continue send flow after user enables blind signing on ledger

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4410]
### Task description

If a transaction requires blind signing and it is not enabled on the ledger then we display a popup for this when they go to send a transaction. Once the user enables blind signing the popup closes and they have to start the send flow again. We should change this so that when the user enables blind signing it continues the flow where they are prompted to verify the transaction.

### Requirements

- [ ] Verify the transaction after user enables blind signing in the send flow

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
