### ISSUE TITLE
[Task]: Resolve closing UX when the use is prompted to enable blind signing

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4411]
### Task description

If a transaction requires blind signing and it is not enabled on the ledger then we display a popup for this when they go to send a transaction. Once the user dismisses the message on the device they are able to close the popup, but they are not made aware of this as it is just the background click that works.

We should update the ux so its more clear and easy to use. I think we should add the close button at the top when they are able to close the popup, or we could even have a button at the bottom which is disabled until they are in a position to close the popup. We could even expand that to have a back button to allow them to go back in the flow.

### Requirements

- [ ] TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
