### ISSUE TITLE
[Task]: Add vertical variant of key value box to be used in ledger popups

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4412]
### Task description

We should add a vertical variant to ket value box to allow for larger texts to be displayed underneath the key. This should also take a parameter for number of lines before truncation etc.

### Requirements

- [x] Add vertical variant to key value box
- [x] Update styles of key value component to match design
- [x] Use vertical variant on ledger popups for addresses and hashes

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
