### ISSUE TITLE
[Task]: Investigate and fix ledger polling

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4414]
### Task description

Currently the ledger device only connects if it is already connected, unlocked and with the shimmer app open before the firefly app opens / we make a wallet.rs call. After that it is not registering any updates to the ledger status.

We need to investigate if this issue in firefly, most likely to do with polling the ledger status.

Ledger and iota.rs have confirmed it is working correctly on there side.

### Requirements

- [ ] Investigate
- [ ] Fix issues

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Logging the raw output from wallet.rs shows the status being shown incorrectly after a few milliseconds of being connected. This is blocked while investigated by wallet.rs and pmaxuw.
