### ISSUE TITLE
[Task]: Enhance ledger status displayed to user

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4415]
### Task description

Currently I have only seen two status displayed to the user ledger disconnected and ledger connected. Perhaps this is an issue with the polling mentioned in: https://github.com/iotaledger/firefly/issues/4414 but we should have more status such as ledger locked, and app not open.

### Requirements

- [ ] Support additional ledger status

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project
