### ISSUE TITLE
[Subtask]: Improve UX of some onboarding view buttons

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4416]
### Task description

Some on click handler functions for onboarding continue buttons takes too long and we should add a spinner.

### Requirements

- [x] Add spinner to necessary places:
    - [x] `ConnectView.svelte` 
    - [x] `EnterPinView.svelte`
    - [x] `BackupPasswordView.svelte`
- [ ] ~~Consider changing "Continue" to another action word so spinner makes more sense (don't wanna say "Continuing...")~~

### Acceptance criteria

All of the above subtasks are completed.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
