### ISSUE TITLE
[Task]: Fix style of ledger connect ledger prompt

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4417]
### Task description

Style of ledger connection prompt is not consistent with other popups in the app. Lets keep content the same but fix styling so it matches.

Old screenshot for reference:
![Screenshot from 2022-09-02 10-22-52](https://user-images.githubusercontent.com/44885822/188182080-c8c32c98-91ff-4ca9-bfb7-61a6d60f16d7.png)

### Requirements

- [x] Add popup title
- [x] Make CTA button full-width
- [x] Add close button
- [x] Make padding / margins consistent
- [x] Change icon to animation
- [x] Create generic `LedgerAnimation` component
- [x] Add different texts per state:
    - [x] Disconnected (error)
    - [x] Locked (warning)
    - [x] App Not Open (info) 

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
