### ISSUE TITLE
[Task]: Clean up old ledger popups that are not needed

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4418]
### Task description

We should clean up and delete any old popups that are not needed for ledger any more.

### Requirements

- [x] Remove old popups:
    - [x] `LedgerAddress`
    - [x] `LedgerConfirmation`
    - [x] `LedgerLegacyTransaction`
    - [x] `LedgerMigrateIndex`
- [ ] Check name of existing popups conforms to conventions:
    - [ ] `LedgerTransactionPopup` -> `VerifyLedgerTransactionPopup`
    - [ ] Add `Popup` suffix where needed 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
