### ISSUE TITLE
[Task]: Refactor checkStronghold to include a check and prompt for ledger

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4419]
### Task description

We currently have a checkStronghold function which checks if stronghhold is unlocked before executing a call back. If not i8t prompts the user to input the password before executing the callback.

We can make this more generic so that it works for ledger too. This way we can prompt user to connect ledger if its not connected.

### Requirements

- [ ] Refactor to a generic check unlocked function and then execute callback or prompt user to unlock either ledger or via password popup.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
