### ISSUE TITLE
[Task]: Navigate to send confirmation quicker after signing transaction on ledger

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4420]
### Task description

Can we navigate to the send confirmation page quicker after we sign the transaction on ledger. Once they click the button to verify it should go back to the send confirmation page and show in progress. Right now there is quite a delay and it means the send confirmation popup flashes for a very short time before closing. And the verification popup is open to loong.

### Requirements

- [ ] Navigate as soon as user clicks verify.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Currently not possible, because the only way we can detect that the user verified the transaction is to listen for the `PoW` event. 
A possible solution would be to ask the ledger simulator devs to include new events

**Comment by nicole-obrien** [comment]
We are just going to ignore this step and go straight to the dashboard
