### ISSUE TITLE
[Task]: Cleanup old Ledger JSON animations

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4424]
### Task description

Lots of unused / outdated assets.

### Requirements

- [x] Remove following animations:
    - [x] `ledger-choose-index-desktop`
    - [x] `ledger-generate-address-desktop`
    - [x] `ledger-migrate-desktop`
    - [x] `ledger-switch-app-desktop`
- [x] Rename following animations:
    - [x] `ledger-address-confirmed-desktop` -> `ledger-prompt-confirmed-desktop`
    - [x] `ledger-confirm-address-desktop` -> `ledger-confirm-prompt-desktop`
- [x] Move all Ledger animations to dedicated folder 
- [x] Add `LedgerAnimation` component that uses `ledger-bg-desktop`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
