### ISSUE TITLE
[Task]: Create auxiliary `animation` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4425]
### Task description

We can improve how to deal with animations (in lib).

### Requirements

- [ ] Create `Animation` enum with all variants used (to avoid using hard-coded strings everywhere)
- [ ] Refactor `LedgerAnimation` component to not use hacky CSS (no transforms, no weird max heights)
- [ ] (Opt.) Replace all animation uses with new enum

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
