### ISSUE TITLE
[Task]: Clean up old ledger onboarding files

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4433]
### Task description

It seems there are still some files that we do not use from legacy ledger onboarding and migration we should clean them up.

### Requirements

- [ ] Remove old ledger onboarding views etc

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
