### ISSUE TITLE
[Task]: Clean up stardust-develop branch

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4435]
### Task description

We need to clean up the stardust-develop branch as much as possible before release. To ensure the repo is maintainable and bug free. This includes removing old participation, staking and migration code / components.

### Requirements

- [x] Clean up migration code
- [x] Clean up participation code
- [x] Clean up migration components and logic in other components
- [x] Cleanup staking components
- [x] General cleanup of onboarding views that are not used

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
