### ISSUE TITLE
[Task]: Enhance the onboarding connect ledger view to show each state of ledger connection

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4436]
### Task description

We have cleaned up the ledger states and now we have 4 distinct states: not connected, locked, app not open, and correct app open. So we should use these states on the connect ledger onboarding view.

### Requirements

- [x] Add a tick list item for each of the three states not connected, locked, and app not open
- [x] Clean up animation logic and locales
- [ ] Add animation for pin code

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
