### ISSUE TITLE
[Task]: Use test coin type for testnets

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4438]
### Task description

We should be using the testnet cointype `1` or `0x1` for testnets. Although we may not want to do this for the current alpha and beta builds, because they are only network that people are testing.

### Requirements

- [ ] Support testnet cointype

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Done in https://github.com/iotaledger/firefly/pull/6613
