### ISSUE TITLE
[Task]: Polish wallet tab for R1

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4441]
### Task description

As preparation for release 1 of Firefly V2 we want to polish the wallet tab.

#### General polishing

- [x] #4447
- [x] #4454
- [x] #4456

#### Activity polishing

- [x] #4446
- [x] #4453 
- [x] #4455

#### Button polishing

- [x] #4444
- [x] #4445
- [x] #4462 

#### Input polishing (#4496)

- [x] #4457
- [x] #4458
- [x] #4459 
- [x] #4460 
- [x] #4461
- [x] #4535

#### Filter polishing (#4489)

- [x] #4234
- [x] #4300
- [x] #4448
- [x] #4449
- [x] #4450
- [x] #4451
- [x] #4452

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
