### ISSUE TITLE
[Task]: Validate tag length on send form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4468]
### Task description

The max tag length is 64 characters, we need to validate this on the send form and any deep links.

### Requirements

- [x] Validate tag length on send form
- [x] Validate tag length on deep link

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
