### ISSUE TITLE
[Task]: Update and create animations for ledger (shimmer variants)

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4486]
### Task description

We need to update existing animations to use the shimmer logo instead of any old iota logos. We will still need the IOTA ones for when we have the iota app.

We also might need new animations.

### Requirements

- [ ] Create shimmer variant of ledger animations
- [ ] Create new animations if needed

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
