### ISSUE TITLE
[Task]: Ensure no lingering confirmation prompts on Ledger device

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4498]
### Task description

There should be no cases where a confirmation prompt can linger on the device.

### Requirements

- [ ] Consider if we can call the API from Firefly to cancel Ledger actions 
- [ ] Fix the following scenarios:
    - [ ] Using the menu bar to logout ("Wallet" -> "Logout") while a confirmation popup is displayed 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
