### ISSUE TITLE
[Task]: Improve nsis script

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4529]
### Task description

One of our community members suggested some improvements to the VC installer script:

- [x] #4530
- [ ] #4531

### Requirements

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
