### ISSUE TITLE
[Task]: Log wallet.rs logs only per session

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4548]
### Task description

We should add a date and timestamp to the wallet.rs log name so that a new file is created per session. This will make debugging easier, and easier to clean up old logs.

### Requirements

- [x] Add date time stamp to wallet.rs log file

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
