### ISSUE TITLE
[Task]: Change app name to `Firefly Shimmer`

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4549]
### Task description

For launch of shimmer the app will be called Firefly Shimmer to make it easier to find.

### Requirements

- [x] Change app name to Firefly Shimmer

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
We should look at revising our branch strategy soon, including re-naming `stardust-develop` to `shimmer`, which I'd prefer over `staging`. Definitely need to continue this discussion because it affects lot's of parts of our process like release and branch merge strategies, changing / automating app config, website releases, and the choice around 1 or 2 apps down the line
