### ISSUE TITLE
[Task]: Add functionality to burn native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4550]
### Task description

Now that wallet.rs has exposed the functionality to burn native tokens and we have the designs, we can implement and enable this feature in FF.

### Requirements

- [x] Add burning native token logic
- [x] Add UX flow for burning native token
- [ ] Add activity for burning native token

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
