### ISSUE TITLE
[Task]: Initiate ledger polling earlier in the onboarding flow

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4551]
### Task description

Because we don't initiate ledger polling until onMount of the connect ledger page in onboarding there is an interval before we get the first result of the ledger connection. We can initiate the ledger polling earlier in the flow to prevent this gap.

### Requirements

- [x] Move initiation of ledger polling earlier in the onboarding flow.
- [x] Clean up ledger polling on back of the page that is now used to initiate the flow.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
