### ISSUE TITLE
[Task]: Check connect ledger status before proceeding to login screen after onboarding

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4552]
### Task description

We don't want the user to close the ledger app while first login is occuring as this will break the profile. We can help prevent this by making sure they have the ledger connected and app open before they proceed.

### Requirements

- [ ] Check profile auth before proceeding from onboarding

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
