### ISSUE TITLE
[Task]: Update icons for expiration and timelock

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4553]
### Task description

We now have separate icons for expiration and timelocks that are to be displayed on the activity tiles.

### Requirements

- [x] Add new expiration icon to activity tile
- [x] Add new timelock icon to expiration tile

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
