### ISSUE TITLE
[Task]: Add tooltip to expiration and timelock icons

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4554]
### Task description

We need to add a tooltip to the expiration and timelock icons in activity tile to describe what they are to end user

### Requirements

- [ ] Add tooltip to icons
- [ ] Add tooltip icons to the activity tile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
