### ISSUE TITLE
[Task]: Update animation for onboarding network and protocol

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#4556]
### Task description

Design has created a new animation for the onboarding network and protocol. Check that this animation matches the style of the other animations, and then add to Firefly.

### Requirements

- [x] Add onboarding animation to ChooseNetworkView.svelte
- [x] Add onboarding animation to ChooseProtocolView.svelte
- [x] Add onboarding animation to SetupPrivateNetworkConnectionView.svelte

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
