### ISSUE TITLE
[Task]: Fix account manager handling for Ledger-based Shimmer claiming flow

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4557]
### Task description

We have to take extra caution when handling multiple account managers so that the Ledger is accessed by only one at one time. Functions from different ones can be called in series, but problems arise when we try to parallelize calls.

### Requirements

- [x] Fix account manager handling
- [x] Change device polling to use specific manager (?)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
