### ISSUE TITLE
[Task]: Make filter menu accordion style

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4569]
### Task description

If we select many filters at once in a filter menu there is a potential for the expanded ui to exceed the height of the view. To solve this without needing to add a scroll bar is to make the filter menus accordian style. This means only one filter can be open / editable at once. See the image for updated design:
![Screenshot 2022-09-16 at 18 55 04](https://user-images.githubusercontent.com/89913787/190702325-9be866e5-dd30-4ae6-8ff2-d4826b5d7cef.png)

### Requirements

- [x] Make filters accordion style to match updated design

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
