### ISSUE TITLE
[Task]: Fix width of expiration time picker

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4570]
### Task description

We need to make the width of the expiration time picker dynamic rather than fixed. This prevents the wrapping of dates when we have longer months such as September  vs May. See:
![Screenshot 2022-09-16 at 18 58 17](https://user-images.githubusercontent.com/89913787/190702788-6aaf605b-721b-4f66-b7f6-be0fbf6ee055.png)

### Requirements

- [x] Make width dynamic so that the date/time doesnt wrap

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
