### ISSUE TITLE
[Task]: Add information tooltip component to key value boxes

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4571]
### Task description

We want to have the ability to add an informational tooltip to key value boxes, so we should add a generic component / optional feature to the key value boxes so we can display an informational tooltip.

### Requirements

- [x] Add generic informational icon with tooltip
- [x] Add optional informational tooltip icon to key value boxes

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
