### ISSUE TITLE
[Task]: Add tooltip to optional input buttons

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4572]
### Task description

When the user hovers over an optional input button we want to display a tooltip to help the user understand what that input is for.
![Screenshot 2022-09-16 at 19 03 27](https://user-images.githubusercontent.com/89913787/190703568-13222473-53c7-42ad-a07b-a66beb458416.png)

### Requirements

- [x] Add optional tooltip for optional input buttons
- [x] Add tooltip to send form inputs
- [x] Add tooltip to mint token form

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
