### ISSUE TITLE
[Task]: Remove gray from getIconColorFromString

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4573]
### Task description

Having the icon color grey for assets could potentially clash with our dark mode backgrounds as we user gray. We should remove the gray colour set from the generator.

### Requirements

- [ ] Remove gray colour set from the generator.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
