### ISSUE TITLE
[Task]: Cache all foundry metadata for native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4575]
### Task description

We currently request the foundry metadata for all native tokens, and then only persist the metadata if it sticks to irc30, we should change this so that we cache all metadata this will reduce pointless api requests each time we login.

### Requirements

- [ ] Cache all metadata not just irc30, but still only show irc30 assets.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
