### ISSUE TITLE
[Task]: Sync incoming transactions during recovery / sync calls

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4576]
### Task description

Currently we don't enable the sync incoming transaction flag everywhere we make a sync call etc to wallet rs, only when we enable background syncing. We should therefore update anywhere possible to set this flag.

### Requirements

- [ ] Add incoming transaction sync flag to sync options of all sync calls and recover account calls

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
