### ISSUE TITLE
[Task]: Scroll to selected wallet in wallet switcher

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4578]
### Task description

When you have to many wallet in the wallet switcher there is a scroll bar added for the overflow. When opening the wallet switcher the scroll is always at the top, so if you have a selected account that is passed the initial view you can not see the one you have selected. I think it would be better to scroll so that the selected account is visible.

### Requirements

- [x] Auto scroll on wallet switcher so the selected account is visible.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
