### ISSUE TITLE
[Task]: Remove sync button from the activity pane

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4579]
### Task description

The sync button was added before we had background sync enabled, and we do not need it when background sync is working. Not to mention it currently only calls sync on the account but doesn't do any state updates so we should remove it.

### Requirements

- [x] Remove sync button from activity pane
- [x] Cleanup now unused code

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
