### ISSUE TITLE
[Task]: Fix delete profile by doing it from electron

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4580]
### Task description

Instead of relying on wallet.rs to delete a profile, we can just destroy the manager and delete the folder on the electron side. This is because while having the profile manager open there could be a lock on the resources causing the profile deletion to fail.

### Requirements

- [ ] Change logic to delete profile from the front end instead
- [ ] Change logic so we check profile auth before deleting a profile?

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
