### ISSUE TITLE
[Task]: Fix storage deposit not showing when gifting

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4581]
### Task description

When we are gifting the storage deposit, we still should show the amount of the base coin that will be sent with the transaction as the storage deposit. This seems to have broken recently and is now showing 0.

### Requirements

- [ ] Show SMR amount as storage deposit when sending a native asset and gifting the storage deposit.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
