### ISSUE TITLE
[Task]: Remove block on connecting to nodes via http

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4582]
### Task description

This is supported by wallet.rs there is no need to block this on the frontend. In the future we can improve the UX by warning the user if they are connecting to a node via http instead of https.

### Requirements

- [ ] Remove hard coded block preventing http
- [ ] Where we validate a node, allow insecure should be set to true

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
