### ISSUE TITLE
[Task]: Validate the amounts on the send confirmation popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4583]
### Task description

Because you can enter the send confirmation popup via a deep link, we should validate on the send click that the amount is available to spend before asking the user for the password or initiating the transaction.

### Requirements

- [x] Validate amounts on the send form, including the storage deposit requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
