### ISSUE TITLE
[Task]: Allow sending native token and base coin through send confirmation deep link

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4584]
### Task description

To support ecosystem projects, we should suppor sending native token and base coin through send confirmation deep link.

### Requirements

- [x] Allow specifying native token amount and base coin amount in send confirmation deep link
- [x] Show this base coin amount as storage deposit and forced gifting when it is added at same time as a native token amount.
- [ ] Add a warning hint that base coin amount is displayed instead of storage deposit.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
