### ISSUE TITLE
[Task]: Scroll to top of lists when filter or search criteria changes

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4594]
### Task description

Because we use virtual lists if the user is far down a list and they change the search criteria or filter so now they are scrolled to an item index greater than the number of items in the list, then the list appears blank and they need to scroll up.

### Requirements

- [x] Scroll to top of activity list when the filter or search criteria changes
- [x] Scroll to top of the asset list when the the filter changes

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
