### ISSUE TITLE
[Task]: Fix default expiration time when a storage deposit is added

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4595]
### Task description

This functionality appears broken. When we perform a transaction where a storage deposit is going to be added we should be adding a default expiration time of 1 day that is selected in the menu. This includes navigating to the send form when we have a value less than the minimum storage deposit required for the outputs selected. 

We should also remove the default expiration time if a user chooses to gift the storage deposit.

### Requirements

- [x] Set the default expiration time if there is a storage deposit
- [x] Remove the default expiration time if the storage deposit is gifted
- [x] Allow the user to replace the default with none, or a specific time

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
