### ISSUE TITLE
[Task]: Fix passing boolean parameters to deeplinks

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4601]
### Task description

When passing parameters to deeplinks we will be using strings, and therefor we can now parse a boolean using Boolean('false') or Boolean ('true') as they will both result in true. 

### Requirements

- [x] Create isTrue function for strings
- [x] Use when parsing booleans in strings

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
