### ISSUE TITLE
[Task]: Fix / ensure we are not using any hardcoded hrps

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4614]
### Task description

Just found an occurrence where we had hardcoded 'rms' which prevent the new output event from creating an activity

### Requirements

- [ ] Remove hardcoded hrp 'rms' from newOutput event handler
- [ ] Check rest of app

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
