### ISSUE TITLE
[Task]: Add network screen for onboarding

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#4620]
### Task description

Add network selection screen as router component to the mobile package and adjust the presentation.

Note: Private network doesn't have to be selectable.

### Requirements

- [ ] Router component added to the mobile project
- [ ] Presentation adjusted for mobile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
