### ISSUE TITLE
[Task]: Add shimmer profile setup screen for onboarding

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#4621]
### Task description

Add shimmer profile setup screen as router component to the mobile package and adjust the presentation.

Note: claim and restore do not have to be selectable.

### Requirements

- [ ] Router component added to the mobile project
- [ ] Presentation adjusted for mobile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
