### ISSUE TITLE
[Task]: Add mnemonic screens for onboarding

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#4625]
### Task description

Add the mnemonic screens (recovery phrase and recovery phrase validation) as router components to the mobile package and adjust the presentation.

### Requirements

- [ ] Router components added to the mobile project
- [ ] Presentation adjusted for mobile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
