### ISSUE TITLE
[Task]: Add success screen for onboarding

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#4626]
### Task description

Add success screen as router component to the mobile package and adjust the presentation.

### Requirements

- [ ] Router component added to the mobile project
- [ ] Presentation adjusted for mobile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
