### ISSUE TITLE
[Task]: Fix `NaN` issue when displaying total claimed rewards

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4632]
### Task description

There is a bug that ends up causing the total number of rewards claimed to be `NaN`.

### Requirements

- [x] Find problem
- [x] Fix problem

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
