### ISSUE TITLE
[Task]: Align all action menus correctly wrt to the open button

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4646]
### Task description

I have asked ux team to define and make consistent the position of the menus opening wrt the button used to open it.

### Requirements

- [x] Align position of all menus
- [x] Move meny to the right on the token information popup

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
blocked: waiting for designs

**Comment by jeeanribeiro** [comment]
https://www.figma.com/file/rrTiOHqpjQ54UGhT38nKy0/Wallet-tab-%5BWIP%5D?node-id=566%3A225745
