### ISSUE TITLE
[Task]: Adjust last onboarding page for ledger

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4647]
### Task description

We havent quite finished onboarding until the loading page is complete and we are on the dashboard. For ledger devices the user could disconnect or lock the ledger during the process so we should add a warning to the congratulations view and the loading screen.

### Requirements

- [ ] Update text on congratulations page
- [ ] Add warning text hint for ledger on congratulations page

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
