### ISSUE TITLE
[Task]: Hide pointless activity where amount = return amount and rest of output is empty

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4648]
### Task description

People can spam us with basic outputs where the return amount = the amount and there is no native tokens, there is no point claiming it as all the funds are just being sent back to the sender.

### Requirements

- [ ] Do not build activity for this specific case where there is no additional assets in the ouput and the amount = the return amount

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
