### ISSUE TITLE
[Task]: Fix minting native tokens

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4649]
### Task description

With the latest update to wallet.rs-beta.28 we need  now create the alias output separate to minting a token (creating foundry) We therefore need to adjust the logic to do both these actions in FF.

### Requirements

- [ ] Adjust logic to create alias if needed in the mint token logic

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
