### ISSUE TITLE
[Task]: Fix clear active profile at start of onboarding

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4660]
### Task description

With new changes to make onboarding more robust, if we have an active profile at start of onboarding, later on we do not create a new persisted profile. The best option is to make sure the active profile is clear at the start of onboarding.

### Requirements

- [ ] Clear active profile at the start of onboarding

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
