### ISSUE TITLE
[Task]: Enforce one claiming transaction per account

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4664]
### Task description

Currently the UI allows the user to continue making claimed transactions if they searched after making a previous one. The library logic does not support it, so we must enforce it also on the UI level.

### Requirements

- [x] Disable search for rewards buttons after claiming transactions have been made

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
