### ISSUE TITLE
[Task]: Fix Stronghold Shimmer claiming flow on wrong password

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4673]
### Task description

If the user enters a wrong password, Firefly throws two errors instead of one.

### Requirements

- [x] Ensure only one error is thrown
- [x] Ensure flow is recoverable after error (spinner spins forever) - if password is wrong stop continuing

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
