### ISSUE TITLE
[Task]: Fix tooltip style on optional inputs

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4688]
### Task description

The tooltip on the optional input components does not match the tooltip style in the design or other tooltips.
![Screenshot 2022-09-26 at 13 23 42](https://user-images.githubusercontent.com/89913787/192275606-fb64f1a3-7942-42f5-b5d5-d0392c521075.png)
![Screenshot 2022-09-26 at 13 25 48](https://user-images.githubusercontent.com/89913787/192275724-f8cbca88-1a44-4e3a-aee8-d1aacd1e4444.png)

### Requirements

- [ ] Update style of the tooltips to match design and be consistent across the app

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
