### ISSUE TITLE
[Task]: Fix: send confirmation is visually incorrect after inputting password

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4689]
### Task description

When we reopen the sendconfirmation popup after navigating away from it, and its showing an inprogress state. If we previously toggled the gift storage deposit then when navigating back it does not show as toggled. And therefore looks visually wrong than what is actually happening.

### Requirements

- [ ] Make sure the storage deposit and toggle is correct when reopening the send confirmation popup after verifying auth.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
