### ISSUE TITLE
[Task]: Set expiration time to none after choosing to gift the storage deposit

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4690]
### Task description

If we toggle to gift the storage deposit it's know longer advisable to add the expiration time to the transaction. So we should set it to none.

### Requirements

- [x] Set expiration time to none after toggling gift storage deposit into the true position
- [x] Re add expiration time when toggle is set to false

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
