### ISSUE TITLE
[Task]: Fix: two reject transaction buttons lead to different styled confirmation popups

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4691]
### Task description

When rejecting from the activity popup the following confirmation popup opens, which also doesn't look like it has the correct styles.
![Screenshot 2022-09-26 at 13 43 03](https://user-images.githubusercontent.com/89913787/192279206-1d32f413-8d71-465c-8fff-9db348f0711c.png)
Rejecting from the activity tile opens this popup which looks correct.
![Uploading Screenshot 2022-09-26 at 13.43.08.png…]()

### Requirements

- [x] Make it so they open the correctly styled popup with warning and red button.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
