### ISSUE TITLE
[Task]: Validate amount fields in deep links are integers

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4692]
### Task description

Because deep links use the smallest possible value for the amount we should ensure that they only allow integer values.

### Requirements

- [x] Only allow integer values for amounts in deep links

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
