### ISSUE TITLE
[Task]: Add mobile login views

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4695]
### Task description

If the PR gets too big we can split the PR into each of these views, but perhaps to kickoff we could keep it all in the same PR, the dev should see.

Views to add:
- [ ] Select Profile
- [ ] Enter Pin
- [ ] Load Profile 

### Requirements

Above mentioned requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
