### ISSUE TITLE
[Task]: Fix native tokens no longer showing in activity history

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4700]
### Task description

Native tokens are no longer showing in activity history when they are received. Neither when online or after login.

### Requirements

- [x] Find issue
- [x] Fix issue

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
