### ISSUE TITLE
[Task]: Use the button component on the activity popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4702]
### Task description

We don't use the generic activity buttons for the claim actions on the activity popup, this means that the styles are wrong.

### Requirements

- [x] Use generic button component on activity popup.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
