### ISSUE TITLE
[Task]: Hide expiration time on claimed activity popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4703]
### Task description

After the activity is claimed there is no longer a need to show the expiration time if there was one.

### Requirements

- [x] Remove expiration time from ui of claimed transactions

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
