### ISSUE TITLE
[Task]: Remove autofocus on all buttons

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4704]
### Task description

Until we complete the accessibility upgrades and focus states of all elements we shouldn't autofocus on random buttons, and therefore should go through the app to remove this autofocus.

### Requirements

- [ ] Remove autofocus of all buttons

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
