### ISSUE TITLE
[Task]: Calculate and show the surplus amount for activities

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4706]
### Task description

You could potentially be sending a surplus amount more than the required storage deposit or sending an amount while sending native tokens. This should show up on the activity details as a surplus amount.

### Requirements

- [ ] Calculate surplus amount to show on activity popup

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
