### ISSUE TITLE
[Task]: Add correct tooltips for optional inputs on the mint native token form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4707]
### Task description

Incorrect tooltip text is displayed on the optional inputs of the mint native token form.

### Requirements

- [x] Add correct tooltip locales

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
