### ISSUE TITLE
[Task]: Fix spinner in busy button is not white

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4708]
### Task description

Because the spinner is disabled and busy at the same time, the spinner is showing as grey instead of white.

### Requirements

- [ ] Make busy spinner in button white even when button is disabled

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
The problem was that the button was not using the Button component

![Image](https://user-images.githubusercontent.com/42754063/192612128-6d3ad6bc-dda5-4d13-8ea2-27ba6a6215b2.png)

Now when the button is disabled it looks like disabled, and a white spinner wouldn't have good contrast with the background, so I think it is looking better now than before

**Comment by jeeanribeiro** [comment]
If someone agrees with my point of view I think we can close this issue
