### ISSUE TITLE
[Task]: Set parameters and feature flags for first shimmer production release

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4710]
### Task description

We need to prepare the app for the first release of the Shimmer network. This requires us to update the node urls, explorer urls, and any feature flags.

### Requirements

- [x] Add official Shimmer node url
- [x] Add official Shimmer explorer url
- [x] Set feature flags
- [x] Polish up `README.md` with Shimmer / Stardust rather than IOTA (or both?)

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
