### ISSUE TITLE
[Task]: Skip protocol selection during onboarding

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4713]
### Task description

Because there is only one protocol supported for now we should skip the protocol selection page.
Non devs should go straight to choose the type profile setup, and dev profiles can go to network selection page.

### Requirements

- [x] Skip profile selection page

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
