### ISSUE TITLE
[Task]: Allow restoration on shimmer network with old strongholds

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4763]
### Task description

Currently we are blocking restoration of stronghold if its an older stronghold or from a different network. We should allow the user to import the stronghold anyway and use it to import the seed and then just recover accounts.

### Requirements

- [x] Allow older / mismatched strongholds
- [x] Call recoverAccounts in all restore flows during loading

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
