### ISSUE TITLE
[Task]: Allow user to continue if they didn't have any rewards to claim

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4764]
### Task description

In the claim flow if the use has no rewards to claim then allow the to continue restoring as normal without claiming.

### Requirements

- [x] After search show a continue without claiming button

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
