### ISSUE TITLE
[Task]: Clear the onboarding and active profile before onboarding starts

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4765]
### Task description

In some cases the active profile or onboarding profile could be present before onboarding flow starts, and this could lead to problems.

### Requirements

- [x] Clear onboarding profile when...
    - [x] Entering onboarding flow
    - [x] Completing onboarding flow 
- [x] Clear active profile when...
    - [x] Logging out
    - [x] Entering onboarding flow 
- [x] (Opt.) Refactor a function for initiating the onboarding flow to be used in the multiple places the flow starts

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
