### ISSUE TITLE
[Task]: Fix NetworkSummaryModal with broken layout

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#4767]
### Task description
The NetworkSummaryModal component is with a broken layout so we need to make it more resilient and not break it when info is missing

![Image](https://user-images.githubusercontent.com/42754063/193102083-56885bcd-1922-4c17-9246-92c2c26f2bdc.png)

### Requirements
- [x] Layout does not break with missing info

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
