### ISSUE TITLE
[Task]: Upgrade wallet.rs to `2.0.3-rc.1`

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4777]
### Task description

Latest wallet.rs with getAddressIndexs and making meta private has been released.

### Requirements

- [ ] Update wallet.rs to 2.0.3-rc.1
- [ ] Remove uses of account.meta
- [ ] Use getAccountIndexes instead of getAccounts
- [ ] Resolve other change logs

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
