### ISSUE TITLE
[Task]: Fix received transactions that have expired not showing expired label on tile 

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4788]
### Task description

The received transactions that have expired no longer show the expiration label, so its hard to see that they have expired.

### Requirements

- [x] Show expired label on all expired transactions.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
