### ISSUE TITLE
[Task]: Remove unnecessary views from mobile onboarding

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4800]
### Task description

- [ ] Remove select profile type SW/HW
![image](https://user-images.githubusercontent.com/3624944/193809690-15d999b4-f129-493f-aa83-3a09eccfa4fb.png)

### Requirements

Mobile onboarding cleaned up

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
