### ISSUE TITLE
[Task]: Fix busy state on alias creation confirmation form

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4814]
### Task description

The busy state is broken on the create alias flow since we moved the transferring store to the account store. We need to fix this to match the send confirmation flow.

### Requirements

- [x] Fix busy state in alias creation confirmation page

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
