### ISSUE TITLE
[Task]: Add fiat price data for shimmer

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4817]
### Task description

Now that shimmer has a market value we can add a fiat price to the balance of shimmer. We can get this from the coingecko api for free we just need to add attribution to the currency selector in settings.

### Requirements

- [ ] Add fiat conversion to asset / balance of asset
- [ ] Add polling of coin gecko api for shimmer balance
- [ ] Add attribution to currency selector

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
