### ISSUE TITLE
[Task]: Create Split Button for different sending flows

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4848]
### Task description
- [ ] Create an option for sending L1 -> L2 that can be enabled/disabled with a feature-flag
- [x] #4900

- Send funds on L1
- Send funds to L2
- Send NFT (implement this later, not in this issue)

Once you set it, it stays constant as long as you don't switch accounts/log out.

Design can be found here: https://www.figma.com/file/rrTiOHqpjQ54UGhT38nKy0/Wallet-tab-%5BWIP%5D?node-id=3348%3A286842

### Requirements

#4891 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Close, since, we're moving towards a different approach for sending to L2.
