### ISSUE TITLE
[Task]: Write Governance technical specification

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4859]
### Task description

In order to develop this feature efficiently, it first must be designed and spec'd out.

### Requirements

- [x] Write the [document](https://hackmd.io/@maxwellmattryan/SJ4h-47Qo)
- [x] Write the `wallet.rs` API side of things
- [x] Gather feedback on specification
- [ ] ~~Add specification to handbook (in more polished form)~~

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
