### ISSUE TITLE
[Task]: Create library modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4860]
### Task description

:x: Blocked until the technical specification (#4859) is complete!

`participation` - a core module containing the logic for event participation
`governance` - a context module containing higher-level logic for a dynamic voting system

### Requirements

- [ ] Refactor any existing participation library code
- [ ] Create core `participation` module
- [ ] Create context `governance` module 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
