### ISSUE TITLE
[Task]: Add initial Governance dashboard with mocked proposals

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4861]
### Task description

:x: Blocked until libraries are developed (#4860)!

This is responsible for the initial Governance tab.

### Requirements

- [ ] Create Governance dashboard
- [ ] Add necessary `AppRoute` and router logic
- [ ] Add mocked proposals (clickable but `onClick` is stubbed)
- [ ] Refactor any existing Governance UI components

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
