### ISSUE TITLE
[Task]: Add automatic proposal querying for nodes in client options

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4862]
### Task description

We should query all events available for every node that a user has specified in their client options / network configuration.

### Requirements

- [x] Register proposals for primary node in client options
    - [x] Only if they haven't already been registered, even if registered with a different node
- [x] Keep registered events if primary node is removed or becomes non-primary

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until this is resolved: https://github.com/iotaledger/wallet.rs/issues/1670

**Comment by Tuditi** [comment]
Blocked until wallet.rs is updated (https://github.com/iotaledger/firefly/pull/5682)
