### ISSUE TITLE
[Task]: Add proposal view with mocked event

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4863]
### Task description

The next step after the dashboard is the proposal view where users see information about the proposal and the questions and answers to cast votes for.

### Requirements

- [ ] Add form logic with mocked data for "Confirm votes"

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
