### ISSUE TITLE
[Task]: Register proposal via deep links

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4865]
### Task description

This handles adding a proposal to Firefly via a deep link.

### Requirements

- [x] Write documentation for Firefly deep links
- [x] Add parameter validation
- [x] Add logic to open registration popup (pre-filled)
- [ ] ~~Add deep link warning popup~~

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
