### ISSUE TITLE
[Task]: Add modal containing event phases and timeline

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4866]
### Task description

When a user hovers over the label of a proposal, they will trigger a modal with the different phases of the events and their respective starting dates.

### Requirements

- [ ] Add UI component for modal
- [ ] Add on hover display logic to proposal label component

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Already done
