### ISSUE TITLE
[Task]: Implement Governance activities

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4868]
### Task description

We'll need activities for casting and uncasting votes for Governance events. 

As for how to determine if an output / output relationship is considered to be casting or uncasting votes, there's a few different ways:
- Adding data to a store indicating what transaction IDs are associated with what Governance actions
    - (Pro) Is simple and easy to implement
    - (Con) Is **NOT** multi-device solution
- Adding logic to derive actions from relationships between outputs
    - (Pro) Is multi-device solution
    - (Con) Is complex and hard to implement

### Requirements

- [ ] Add logic for new activity types:
    - [ ] Casting
    - [ ] Uncasting
- [ ] Add UI for new activities

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
