### ISSUE TITLE
[Task]: Implement search functionality for Governance proposals

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4869]
### Task description

Users will potentially have many proposals and may want to find a specific one by searching for it rather than scrolling through.

### Requirements

- [ ] Add search logic to component

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
