### ISSUE TITLE
[Task]: Write deep link documentation for registering events

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4872]
### Task description

In order to see non-official Governance proposals on your dashboard, you have to "register" them via deep links. The specification for these deep links (as well as Firefly's other deep links) has **NOT** been written yet.

This is important for platforms like Soonaverse that would like an easier integration to interact with Firefly. It may be worth thinking for the future about an externally facing library both us and the community can use for parsing and building deep links.

### Requirements

- [x] Add external doc (somewhere? wiki?) for Firefly deep links

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
