### ISSUE TITLE
[Task]: Add validation for l1 -> l2

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4906]
### Task description

The following inputs should be validated in the send form pop-up:
- [x] EVM Address
- [x] Alias address validation

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
