### ISSUE TITLE
[Task]: Update confirmation Popup for L1 -> L2 transactions

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4907]
### Task description

The confirmation panel should be adjusted to include L1 -> L2 asset sending as well.

### Requirements

- [x] Show destination network
- [x] Add smart contract pill

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
