### ISSUE TITLE
[Task]: E12.M1 - Create NftPlaceholder component

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#4910]
### Task description

Media for NFTs will not be supported until completion of E12.M3. Until then, we will need a placeholder to show the NFT type. This placeholder will also be helpful after delivering E12.M3 while awaiting fetching of NFT data or if data is unavailable.

This placeholder will need to change depending on the NFT MimeType. It will also appear in the NFT details view, in the NFT gallery view, and in the send | receive | and activity flows of the wallet tab. I suggest an extra small, small, medium, large, extra large prop type to handle for this.

- [x] activity feed (extra small)
- [x] confirm send, receive, claim (small)
- [x] initial send view popup (medium)
- [x] gallery view and collection overview (large)
- [x] details view (extra large)

For now, just use a text placeholder. But a more long term solution is to create icons for each of the parent mime types.

### Requirements

- [x] Create NftPlaceholder component with extra-small | small | medium | large | extra-large sizes
- [x] Display parent MimeType for given NFT or unknown if not within IRC27 standard

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
