### ISSUE TITLE
[Task]: E12.M1 - Improve NFT developer tool

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#4914]
### Task description

The new NFT developer-only tool needs validation and the fields for the "attributes" and "royalties" fields need to be improved.

### Requirements

- [x] Add validation to MintNftFormPopup
- [x] Change royalty and attribute fields to support object datatype
- [x] Change MintNftConfirmationPopup to use NftDetails component instead of explicit KeyValueBox components

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
