### ISSUE TITLE
[Task]: Separate desktop routers from core `router` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4922]
### Task description

There is desktop-specific code inside of the `routers` module that is now being included in the mobile build. 

### Requirements

- [ ] Remove all routing logic from inside `core` and `context` modules
- [ ] Implementing required routers for mobile (desktop can be copied over)
    - [ ] Add necessary enums for different routes
    - [ ] Duplicate subrouters as necessary
- [ ] Writing initialization / reset logic for the routers of both platforms (in respective `routers` modules)
- [ ] Ensure that `core/router` does **NOT** contain any platform-specific code (reduce the module to purely base classes, e.g. `Router`, `Subrouter`) 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
