### ISSUE TITLE
[Task Tracker]: UI: Initial dashboard general view

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4933]
### Task description

This task is only to prepare the canvas, no actions/drawers are needed at this step, is just to prepare

- [x] #4934
- [x] #4935
- [x] #4936
- [x] #4937
- [x] #4938
- [x] #4939
- [x] #4940
- [x] #4941

### Requirements

All tasks above are done and merged

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
