### ISSUE TITLE
[Task]: Add receive feature

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4942]
### Task description

- [ ] Add receive drawer & needed components
- [ ] Add route and logic to open/close

### Requirements

Read above

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
