### ISSUE TITLE
[Task Tracker]: Send Flow

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4943]
### Task description

- [x] #4944
- [x] #4945
- [x] #4946
- [x] #4948
- [x] #4949
- [x] #4950
- [x] #4951
- [x] #5015
- [x] #5103
- [x] #5245
- [x] #5343
- [x] #5509

### Requirements

Above tasks are done 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
