### ISSUE TITLE
[Task Tracker]: Selected token

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4955]
### Task description

- [x] #4956
- [x] #4957
- [x] #4958

### Requirements

Above tasks

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
