### ISSUE TITLE
[Task Tracker]: Activities

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4959]
### Task description

- [x] #4960
- [x] #4961
- [x] #4962
- [x] #5248
- [x] #5249
- [x] #5250

### Requirements

Above tasks

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
