### ISSUE TITLE
[Task]: Wallet switcher feature

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4963]
### Task description

- [x] Add wallet switcher drawer & needed components
- [x] Add routes and logic to open/close

### Requirements

Above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
