### ISSUE TITLE
[Task Tracker]: Wallet actions

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4964]
### Task description

- [x] #4965
- [x] https://github.com/iotaledger/firefly/issues/4969
- [x] https://github.com/iotaledger/firefly/issues/4970
- [x] #4967

### Requirements

Above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
