### ISSUE TITLE
[Task Tracker]: Profile view

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4971]
### Task description

- [ ] [Task]: Profile view: Toggle profile view
- [ ] [Task]: UI: Profile view: Top profile section
- [ ] [Task]: Profile view: Backup profile action
- [ ] [Task]: Profile view: Network status

### Requirements

Above requirements

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
