### ISSUE TITLE
[Task]: Add fiat price data for shimmer

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4983]
### Task description

When desktop merges the fiat price, we can include it in our balance also, tasks.
Depends on https://github.com/iotaledger/firefly/issues/4817

### Requirements

- [ ] Add fiat conversion to asset / balance of asset
- [ ] Add polling of coin gecko api for shimmer balance
- [ ] Add attribution to currency selector

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
fiat is already included
