### ISSUE TITLE
[Task]: Add share address button to receive drawer

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4997]
### Task description

Add share address button to receive drawer

### Requirements

Add share address button to receive drawer

- [ ] Share sheet 
- [ ] Button

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
