### ISSUE TITLE
[Task]: Add wallet feature

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4999]
### Task description

Dependent on https://github.com/iotaledger/firefly/issues/4963
Add the "add wallet" feature

### Requirements

- [ ] Add routes to wallet switcher subrouter, or add a new dashboard router
- [ ] add wallet button
- [ ] add views/drawers

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
