### ISSUE TITLE
[Task]: Follow deeplink from logged out profile doesnt open send flow on Linux after login

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5006]
### Task description

In linux, if you follow a deeplink from a logged out profile (either open app or closed), when you enter the pin the send flow doesnt open nor the send fields are preflled

_Something to note is that it might be an issue of the app image launcher we use in linux, it might be worth testing this_

### Requirements

Follow a deeplink in linux always prefills send data and opens the flow for:
- [ ] logged profiles (this already happens)
- [ ] logged out profiles
- [ ] closed apps

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
