### ISSUE TITLE
[Task]: Remove `shell` lib folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5010]
### Task description

This code is old and unused.

### Requirements

- [x] Remove folder
- [x] Adjust code as needed

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
