### ISSUE TITLE
[Task]: Include keyboard height to Drawer component

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5013]
### Task description

The drawer component should adapt based on the keyboard height

### Requirements

For now the keyboard affects the following drawers:
- [ ] Add new wallet
- [ ] Send
- [ ] Unlock stronghold via profile action

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
