### ISSUE TITLE
[Task Tracker]: Remove routing logic from shared folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5026]
### Task description

Routing logic assumes the code is for a specific platform, so for any code that is to be shared then it must be removed.

### Requirements

- [x] #5141
- [x] #5142
- [x] #5180
- [ ] #5181
- [ ] #5138 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
