### ISSUE TITLE
[Task]: Create mobile `assets` folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5027]
### Task description

The mobile specific assets should be in one place to make them easy to find.

### Requirements

- [ ] Move any assets from the shared assets to this folder if used in mobile
- [ ] Move `mobile/icons` to this folder
- [ ] Move assets in `capacitor/assets` to this folder 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
