### ISSUE TITLE
[Task]: Create desktop `assets` folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5028]
### Task description

The desktop-specific assets should be inside of the desktop folder.

### Requirements

- [ ] Move any shared assets from shared into the desktop folder
- [ ] Delete the shared assets folder (so long as the mobile one has been created and adjusted too)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
