### ISSUE TITLE
[Task]: Refactor more `utils` submodules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5031]
### Task description

`utils` core module and some existing lib code need to be refactored.

:warning: Be careful of dependency nonsense when moving these files around (and really hard-to-determine import / dependency errors).

### Requirements

- [x] Remove `.utils` filetype specifier (hard-to-read, redundant)
- [x] Cleanup types (move code to interfaces where necessary)
- [x] Cleanup the following `lib` files:
    - [x] `actions`
    - [x] `address`
    - [x] `base64`
    - [x] `bech32`
    - [x] `bech32Helper`
    - [x] `converter`
    - [x] `ed25519`
    - [x] `helpers`
    - [x] `time`
- [x] Remove `lib/chrysalis.json`
- [x] Consolidate imports for `@core/utils` in all lib and component files
- [x] Ensure all `utils` submodules are using proper import rules

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
