### ISSUE TITLE
[Task]: Move desktop routes from shared folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5034]
### Task description

These view components need to be moved out of shared as they are platform-specific to desktop.

### Requirements

- [x] Move the `routes` folder to desktop package
- [x] Rename `routes` to `views` 
- [x] Adjust code as needed

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
