### ISSUE TITLE
[Task]: Create path aliases for platform-specific 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5041]
### Task description

We need them.

### Requirements

- [x] Create path alias for mobile components
- [x] Create path alias for desktop components

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
