### ISSUE TITLE
[Task]: Move shared `features` to desktop

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5045]
### Task description

The features should be moved.

### Requirements

- [x] Move `features` to desktop

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
