### ISSUE TITLE
[Task]: Integrate Madge into development pipeline

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5055]
### Task description

[Madge](https://github.com/pahen/madge) is a tool to detect circular dependencies inside a codebase. We can use this tool to ensure that our codebase is free of circular dependencies and (hopefully) never result in weird instances where a single import can break the compilation.

### Requirements

- [ ] Reduce circular dependencies
- [ ] Create GitHub Action for checking this with merges and PRs

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
