### ISSUE TITLE
[Task]: Refactor `currency.ts` lib file

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5056]
### Task description

A lot of the currency code is old and unused.

### Requirements

- [x] Refactor

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
