### ISSUE TITLE
[Task Tracker]: Shimmer claiming

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#5062]
### Task description

- [x] #5059
- [x] #5060
- [x] #5061
- [ ] #5603

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
We have to set up a stacking event to test the claiming flow
