### ISSUE TITLE
[Task]: Establish initial Governance UI/UX design

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5071]
### Task description

To begin planning the technical side and developing the libraries and UI, we need to establish an initial version of the interface. 

### Requirements

- [ ] Handoff an initial but complete design

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
