### ISSUE TITLE
[Task]: Refactor `device.ts` lib file

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5080]
### Task description

There is some existing older code in the root shared `lib` folder that needs to be refactored into modules.

### Requirements

- [x] Create new e.g. `scanner` auxiliary module in `packages/mobile`
- [x] Move the QR scanner code (`lib/device.ts`) to new module
- [x] Remove `BarcodeManager` from `IPlatform` interface

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
