### ISSUE TITLE
[Task]: Refactor `transactionHistory.ts` lib file

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5081]
### Task description

This code is old and should be removed.

### Requirements

- [x] Remove the code

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
