### ISSUE TITLE
[Task]: Refactor `typings` lib folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5083]
### Task description

Old code that should be removed.

### Requirements

- [x] Remove all files in this folder

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
