### ISSUE TITLE
[Task]: Add searchbox to activity tab

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5104]
### Task description

Add this searchbox 
![image](https://user-images.githubusercontent.com/3624944/199808024-2035a4d6-9c88-4cc1-bf04-ee01132a1c9f.png)

### Requirements

- [ ] component
- [ ] search works

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
