### ISSUE TITLE
[Task]: Add filters to activity tab

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5105]
### Task description

Add this filter feature
![image](https://user-images.githubusercontent.com/3624944/199808238-604ad0e3-aa54-455f-9174-f24081c12014.png)
![image](https://user-images.githubusercontent.com/3624944/199808311-cfc48d62-1c61-41bb-a93a-30e9ededa204.png)

### Requirements

- [ ] filter component
- [ ] filter route
- [ ] filters work

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
