### ISSUE TITLE
[Task Tracker]: Mobile settings

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5106]
### Task description

Add settings to mobile

### Requirements

- [x] #5107
- [x] #5108
- [x] #5109
- [x] #5110
- [x] #5111
- [x] #5113
- [x] #5114
- [x] #5115
- [x] #5116
- [x] #5117
- [x] #5118
- [x] #5119
- [x] #5121
- [x] #5122
- [x] #5123
- [x] #5124
- [x] #5125
- [x] #5444

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
