### ISSUE TITLE
[Task]: Remove routing logic for `core` modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5141]
### Task description

The core modules contain routing logic, and they shouldn't.

### Requirements

- [x] `deleteAccount.ts`
- [x] `sidebar.ts`
- [x] `logout.ts`
- [x] `login.ts`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
