### ISSUE TITLE
[Task]: Remove routing logic for `contexts` modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5142]
### Task description

The contexts modules contain routing logic, and they shouldn't.

### Requirements

- [x] `deleteProfile.ts`
- [x] `initialiseOnboardingFlow.ts`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
