### ISSUE TITLE
[Task]: Remove router dependencies in shared `auxiliary` modules

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5180]
### Task description

The auxiliary modules contain routing logic, and they shouldn't. 

### Requirements

- [ ] #5918
- [ ] Create two `settings-icon-svg.ts` files in both mobile and desktop (in `contexts/settings`) - this will require moving `settings` to desktop 
    - [x] Move `exportStronghold` function to `stronghold` core module 

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
