### ISSUE TITLE
[Task]: Remove router dependencies in shared `components`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5181]
### Task description

The shared components contain routing logic, and they shouldn't. The two ways to solve this are to either move the components to the desktop folder (if they're desktop-specific) or wrap the component such that the base component doesn't contain routing logic but it's parents (that live in their respective platforms' `components` folders) do.

### Requirements

- [ ] Move the following components to desktop `components` folder:
    - [x] #5887
    - [ ] `ProfileActions.svelte` (will be moved in #5801)
        - [ ] Rename to `ProfileActionsModal.svelte` 
    - [x] #5903 
    - [x] #5908
- [x] #5888 
- [ ] Wrap platform-specific components around the following components:
    - [ ] `NftActivityDetails.svelte`
    - [ ] `NftGalleryItem.svelte`
    - [ ] `ProposalCard.svelte`

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
