### ISSUE TITLE
[Task]: Update wallet.rs to new release

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5219]
### Task description

Update to a new wallet.rs version for NFT compatibility

### Requirements

- [x] https://github.com/iotaledger/iota.rs/issues/1385

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Waiting for new wallet.rs release
