### ISSUE TITLE
[Task]: Update basic transactions to new structure

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5234]
### Task description
The new approach to display activity information with Tabs also needs to be adapted for basic transactions.

### Requirements:
- [x] Remove keyvalues box duplication from `BasicActivityDetails`
- [x] Rename `ActivityType.Transaction` to `ActivityType.Basic`
- [x] Update `SendConfirmation` such that it correctly uses the new tabs for basic transactions
