### ISSUE TITLE
[Task]: Change the way errors are handled at address validation

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5240]
### Task description

Currently `validateBech32Address` and `validateEthereumAddress` are returning error strings instead of throwing actual errors.

This is problematic, since if for some reason the validate functions are not called, the `error` string will be `undefined` and validation will pass. This should be addressed as follows:

- [x] `validateBech32Address` & `validateEthereumAddress` return booleansif validation passes
- [x] `validateBech32Address` & `validateEthereumAddress` throw errors if validation doesn't pass
- [x] `AliasInput`, `RecipientInput` & `MintNftFormPopup` uses try/catch paradigm to check validation

### Requirements

- https://github.com/iotaledger/firefly/pull/5218

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
