### ISSUE TITLE
[Task]: Show parsed metadata in the UI

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5242]
### Task description

We should correctly show the parsed metadata for smart contract function calls. The following fields have to be added in a separate smart contract tab:

- Target Contract
- Contract Function
- Gas Budget

### Requirements

- [x] #5216 
- [x] Tests

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
