### ISSUE TITLE
[Task]: Implement gas selector for smart contract calls

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5254]
### Task description

Implement the gas selector for smart contract function calls.

### Requirements

- [x] https://github.com/iotaledger/firefly/issues/5253

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Closed, since gas fee is static for now.
