### ISSUE TITLE
[Task]: Implement flow to stop voting for a proposal

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5267]
### Task description

The user may want to manually stop voting for a proposal.

### Requirements

- [x] Implement logic for simple case (user is voting and unvotes)

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
