### ISSUE TITLE
[Task]: Implement Governance proposals dashboard pane

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5272]
### Task description

This is a container that will display all of the registered proposals for a profile.

- [x] Create a Proposal Card
- [x] Create a list of proposals

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
