### ISSUE TITLE
[Task]: Polish L1 -> L2

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5282]
### Task description

- [x] Subtract the total amount sent in activity details
- [x] Change pill name of smart contract

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
