### ISSUE TITLE
[Task]: Remove validation duplication

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5289]
### Task description

Currently there is a lot of duplication present in the validation of the `MintNftFormPopup` and the `parseNftMetadata` form. These should be refactored so that there is only one function that takes care of the validation.

Functions to be refactored:
- [ ] validateRoyalties
- [ ] validateAttributes

### Requirements

- https://github.com/iotaledger/firefly/pull/5281

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
