### ISSUE TITLE
[Task]: Minted NFTs don't appear in gallery view until profile is logged out and in

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5310]
### Task description

Newly minted NFTs dont appear in the gallery view of the collectibles tab. They still appear in the activity feed, though.

### Requirements

- [x] Make minted NFTs appear in gallery view without user needing to relog into wallet.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Was fixed in https://github.com/iotaledger/firefly/pull/5243

**Comment by MarkNerdi** [comment]
Maybe these are connected: https://github.com/iotaledger/firefly/issues/5320

**Comment by jeeanribeiro** [comment]
Newly minted NFTs are showing but looks like the last item from selectedAccountNfts is having its `isOwned` property being set to `false`, and them, because of the `$selectedAccountsNfts` filter it is not being displayed

`$allAccountNfts[$selectedAccount?.index]?.filter((nft) => nft.isOwned) ?? []`

**Comment by kraftjs** [comment]
Sounds similar to what I was seeing. I decided to set isOwned to true in the mintNFT function so it would appear inside the collectible tab. Then after a few moments it would disappear because isOwned would change to false.

**Comment by MarkNerdi** [comment]
In the `handleTranscationInclusionEventInternal` function we update the `isOwned` flag of the NFT. 

The current implementation just looks at the `direction`, so i guess this calculation is not complete
