### ISSUE TITLE
[Task]: Remove network input validation when there is Shimmer address

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#5311]
### Task description

With the network input validation, layer 1 transactions are impossible to send, so the validation for it should be removed

### Requirements

- [x] Remove network input validation for layer 1 transaction
- [x] Network input validation for layer 2 transaction still works

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
