### ISSUE TITLE
[Task]: Initial Governance UI/UX polish

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5372]
### Task description

The following items need polish:

- [x] Grid of proposals aligns under each other instead of taking up the space
- [x] Grid of proposals don't change place when clicked on
- [x] Add form submit for registering proposal popup
- [x] Add form submit when voting for a proposal
- [x] Add reactivity for counted votes when active (already done?)
- [x] Disable voting options when the event is in `upcoming` or `ended` phase
- [x] (When removing a proposal), only show text hint if event is in `commencing` or `holding` phase (doesn't make sense to mention anything about counted votes if the user hasn't voted yet or even had the chance to vote)
- [x] De-bounce buttons and add spinners for proposal registration and node auth popups
- [x] Make voting status reactive (if I vote then want to immediately stop voting, I have to navigate back to the page)
- [x] Disable slider / token amount inputs when "managing voting power" while the tx is being created / broadcasted
- [x] Make node input a smart dropdown (with client options nodes as clickable options), like the network input in the send form
- [x] Add dark mode styling

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
