### ISSUE TITLE
[Task]: Fix collectibles tab scrollbar spacing

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5395]
### Task description

Scrollbar spacing in the CollectiblesGalleryView and CollectibleDetailsView is directly beside the content. Add padding between the scrollbar and content.

### Requirements

- [ ] Add padding to scrollbar in CollectiblesGalleryView
- [ ] Add padding to scrollbar in  CollectibleDetailsView

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
