### ISSUE TITLE
[Task]: Refactor lib to remove core/collectibles

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5396]
### Task description

'core/collectibles' is redundant. NFTs/Collectibles now use the 'core/nft' lib. Remove 'core/collectibles'

### Requirements

- [ ] Remove 'core/collectibles'

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
