### ISSUE TITLE
[Task]: Improve error handling Governance

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5404]
### Task description

Appropriately handle the following errors in the governance milestone:

- [x] Vote, but no unspent output found
- [ ] Registering same event twice should not be possible

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until wallet.rs is updated.
