### ISSUE TITLE
[Task]: Fixes from URL whitelist audit

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5409]
### Task description

There may be fixes need from the audit of the url whitelist changes.

### Requirements

- [x] Fix the issue with .replace being exploited using a link like: `https://shiwww.mmer.network`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
