### ISSUE TITLE
[Task]: Move `governance` to contexts directory

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5438]
### Task description

This module should be within contexts instead of core.

### Requirements

- [x] Move the module over
- [x] Update existing import paths as necessary

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
