### ISSUE TITLE
[Task]: Add loading animation to governance features

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5449]
### Task description

Add loading animations to await all the data that has to be fetched from the client on the following pages:
- [ ] `DetailsView.svelte`
- [ ] `ProposalsView.svelte`

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
