### ISSUE TITLE
[Task]: De-bounce buttons around Governance operations

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5468]
### Task description

When voting or stopping a vote, the user can quickly double click the CTA button, so it should be de-bounced as to avoid potential errors.

### Requirements

- [x] Add spinner to and disable "Vote" button (in ProposalView) while voting or stopping vote
- [x] Add logic to re-enable once tx is confirmed (use wallet event)

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
