### ISSUE TITLE
[Task]: De-bounce / disable buttons whenever managing voting power tx is being confirmed

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5480]
### Task description

While managing your voting power, we must disable some operations while the tx is still being broadcasted / confirmed.

### Requirements

- [x] Register proposal popup

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
