### ISSUE TITLE
[Task]: Show current vote

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5495]
### Task description

Show what the user voted for.

### Requirements

- [x] wallet.rs-rc.11

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
