### ISSUE TITLE
[Task]: Minimize calls to `getParticipationOverview` 

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5506]
### Task description

The UI depends a lot on the `getParticipationOverview` function. This is a slow API call to wallet.rs, so we should cache the response and update it whenever necessary.

### Requirements

- [x] Make sure participation overview changes when...
    - [x] Selected account changes
    - [x] Proposals state changes 
- [x] Use writable store to cache data
- [x] Replace calls to `getParticipationOverview` with read of store
- [x] Fix reactivity on Governance dashboard

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
