### ISSUE TITLE
[Task]: Implement a clear NFT cache button in settings

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5507]
### Task description

Add a new option to settings that will clear the local NFT cache.

### Requirements

- [ ] Add a new option to settings that will clear the local NFT cache
- [ ] When users change max media size option in setting, use this function to remove any cached media that is greater than the new max media size.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Not needed for now
