### ISSUE TITLE
[Task]: Don't display placeholders for cached media

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5508]
### Task description

When media isn't cached and needs to be downloaded, it's normal to display the placeholder. But if the media is already cached, it can be jolting to see the placeholders appear and quickly disappear before the cached media is rendered. So for cached media do not render the placeholder icon first.

### Requirements

- [ ] Add `isCached` prop to `NftMedia` component to avoid rendering placeholder icons for media that is locally cached

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Not needed for now
