### ISSUE TITLE
[Task]: Set NFT as Profile Image

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5510]
### Task description

As a user i want to spice up my wallet by using one of my owned NFT images as a profile image.
In the settings, after the `Change profile name` setting, we should add a dropdown with all owned and downloaded NFT images.
After setting a profile image, on the bottom left of the app and in the profile modal the small thumbnail of the image should be displayed.

### Requirements

- [ ] Add functionality to `Set as profile image` button on NFT details view

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
