### ISSUE TITLE
[Task]: Add persisted store for invalid image head calls

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5511]
### Task description

Create a persisted store for invalid image head calls so we don't make repeated and unnecessary network calls

### Requirements

- [ ] Add persisted store for invalid image head calls

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
