### ISSUE TITLE
[Task]: Add controls for the image/gif media type

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5512]
### Task description

Currently, gifs autoplay in the app when rendered in an `<img  />` tag. Change the behavior of gifs so that they only autoplay when hovered outside of the detailsView component. Inside of the detailsView component, add basic controls (pause, play, time controls).

### Requirements

- [ ] Change display of gifs so that they only autoplay when hovered outside of the detailsView component
- [ ] Add basic controls inside of the detailsView component

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
You can not control GIFs unfortunately. So I think we shouldn't spend time adding fancy libraries and hacks for this.
