### ISSUE TITLE
[Task]: Compress image media type before caching

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5513]
### Task description

We need to compress media to save filespace when locally caching media. Choose a compression function and a filetype we should use when displaying the uncompressed images.

When compressing files we need to compress into different thumbnail sizes:
- [small] activity list, activity summary, nft input
- [medium] profile picture
- [large] gallery view
- [original file size] details view

We also need to figure out the max size to display media in the CollectiblesDetailsView

### Requirements

- [ ] Choose compression function
- [ ] Choose which filetype to display uncompressed non-gif images (jpb, webp, etc.)
- [ ] Compress into different thumbnail sizes (small, medium, large, original file size)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
