### ISSUE TITLE
[Task]: Improve video media support

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5514]
### Task description

Implement compression function for video media types and choose a specific filetype for uncompressing videos. We also need to calculate thumbnails for videos. Which sizes should we generate? We will need to display this thumbnail across all media sizes (activity list and summary, gallery view, and details view). To differentiate videos from images outside of the details view, we should also display the nft video placeholder icon as a layer above the thumbnail.

### Requirements

- [ ] Implement compression function for video media types and uncompress to 
- [ ] Calculate thumbnail for videos and display the thumbnail with the nft video placeholder layered above

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
