### ISSUE TITLE
[Task]: Download and serve nft media

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5516]
### Task description

As part of the login function check to see if owned NFTs are cached. If not, download them in the background (don't await this process before logging in).

Also download and cache NFT media when we receive an NFT and write it to our NFT store. When we send an NFT to someone else we should remove it's data from the local cache and any persistent metadata we keep on it (i.e. HEAD info)

Serve images and video from the filesystem after checking security policy when rendered within the app

### Requirements

- [x] On login, check if owned NFTs with img or video media types are locally cached, if not download them to the filesystem in the background
- [ ] #3451 
- [ ] #3439 
- [ ] #5542

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
not needed anymore
