### ISSUE TITLE
[Task]: Prep designs for NFT related settings

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5517]
### Task description

There are more settings that will be added to the app to support NFT downloading and caching, and IPFS nodes. Collaborate with UX to handle these new options.

### Requirements

- [ ] Downloading and caching NFT settings
- [ ] IPFS settings
- [ ] explore more potential settings

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
