### ISSUE TITLE
[Task]: Additional Governance UI/UX polish

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5546]
### Task description

The following items need polish:

- [x] Correctly style answers being voted on/selected
- [x] Navigate the user to the proposal details view immediately after registering a proposal
- [x] Proposal display order changes (randomly?) after re-navigating to the dashboard
- [x] Animate pulse icon for a question's current voted answer 
- [x] Fix text styling for longer answers (number box becomes squished and text is too close to vote percentages)
- [x] Diminish the height of the proposal title pane in DetailsView.svelte
- [x] Don't use a mouse pointer on the slider if it's disabled
- [x] Fix ProposalCard height and add shadows
- [x] Add the proposal's additional info below the title
- [x] Limit question text to 1 line but fully show once the question is opened
- [x] Limit answer text to 1 line but fully show once the question is opened
- [x] When a question is answered, auto-scroll to and open the next one
- [x] Add total proposals to ProposalsDetails
- [x] Fix scrollbar positioning in proposal questions
- [x] Add illustration from NFTs when zero proposals registered
- [x] Rename register proposal to add proposal
- [x] "add proposal" button in ProposalsView when there is not any proposals
- [x] The first question should be opened as default

### Requirements

_TBD_

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
