### ISSUE TITLE
[Task]: Disallow user from entering `PARTICIPATE` tag manually

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5564]
### Task description

To prevent users from creating multiple voting outputs (which isn't currently supported), it is easiest if we prevent users from entering this as a "Tag" feature for an output.

### Requirements

- [ ] Add error saying "This tag is reserved for voting on Governance proposals." when user enters `PARTICIPATE` into tag field

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
