### ISSUE TITLE
[Task Tracker]: Add CI workflows for mobile artifacts (alpha, beta, production) - Android

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5581]
### Task description

If possible, similar to desktop, we should add github action worflows to build (and deploy) mobile Android artifacts.

### Requirements

Similar to desktop, add github workflow actions for
- [ ] Alpha artifact
- [ ] Beta artifact
- [ ] Production artifact
- [ ] Deploy to store (alpha, beta & production might need different config to limit testing group)
- [ ] Release entry in github by tagging

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/6277
- [ ] https://github.com/iotaledger/firefly/issues/6279
- [ ] https://github.com/iotaledger/firefly/issues/6278
```

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
