### ISSUE TITLE
[Task]: Add CI workflows for mobile artifacts (alpha, beta, production) - iOS

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5582]
### Task description

If possible, similar to desktop, we should add github action worflows to build (and deploy) mobile iOS artifacts.

### Requirements

Similar to desktop, add github workflow actions for
- [ ] Alpha artifact
- [ ] Beta artifact
- [ ] Production artifact
- [ ] Deploy to store (alpha, beta & production might need different config to limit testing group)
- [ ] Release entry in github by tagging

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
