### ISSUE TITLE
[Task]: Adjust default proposal display order

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5589]
### Task description

At the moment, we are ordering events based upon their event ID, but this is very random. We should order them per phase (announcement > commencing > counting > closed) and within the same phase, we order them by increasing milestone

### Requirements

- [x] Sort first by event phases
- [x] Sort second by milestones

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
