### ISSUE TITLE
[Task]: Style announced events

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5591]
### Task description

Adjust the announced phase to correspond to the designs:
- [ ] Remove percentages if in announced phase
- [ ] Change voting button text to `Vote opens in X d and Y h` where d = days and h = hours

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
