### ISSUE TITLE
[Task]: Polish UI: Add mobile safe areas

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5594]
### Task description

TBD: list safeareas that need to be added

Depends on https://github.com/iotaledger/wallet.rs/issues/1536 & https://github.com/iotaledger/wallet.rs/issues/1535

eg:
 - [ ] bottom spacing with CTAs should be 32px 
![image](https://user-images.githubusercontent.com/3624944/216974857-f88134e3-f4ce-4dc7-8c90-81b20c290bd3.png)

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
