### ISSUE TITLE
[Task Tracker]: Polish UI

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5595]
### Task description

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/5594
- [x] #5596
- [x] #5597
- [x] #5598
- [ ] #5599
- [x] #5672
- [x] #5779
- [x] #5780
- [x] #5781
- [x] #5782
- [x] #5868
- [ ] https://github.com/iotaledger/firefly/issues/6357
- [ ] https://github.com/iotaledger/firefly/issues/6359
- [ ] https://github.com/iotaledger/firefly/issues/6389
- [ ] https://github.com/iotaledger/firefly/issues/6424
- [ ] https://github.com/iotaledger/firefly/issues/6439
- [ ] https://github.com/iotaledger/firefly/issues/6451
```

### Requirements

Above list ^

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
