### ISSUE TITLE
[Task]: Add intermediary hint popup if user sets voting power to zero while voting

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5619]
### Task description

If the user sets his or her voting power to zero while votes are being counted, the metadata and tag is removed from the output, meaning that the votes will no longer be tracked.

### Requirements

- [ ] Create intermediary popup
- [ ] Display popup in flow if user is voting and sets the voting power to zero (display before Stronghold password)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
May be closed by #5683
