### ISSUE TITLE
[Task]: Fix clickable key-value box in vote for proposal popup

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5620]
### Task description

I can click the key-value box inside this popup to vote for a proposal, whereas only the action button should be able to do this.

### Requirements

- [x] Make the key-value box non-clickable

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
