### ISSUE TITLE
[Task]: Add hint if no voting power

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5621]
### Task description

I am able to try voting for a proposal even if I do not having any voting power.

### Requirements

- [x] Hint to users that they must increase their voting power to be able to vote on a proposal

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
