### ISSUE TITLE
[Task]: Additional Governance UI/UX polish #2

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5663]
### Task description

- [x] Consistent tooltip styling
- [x] NodeInput selector is not overflowing popup
- [x] It's not possible to collapse a question anymore by clicking the ^ icon.
- [x] Add a decimal place to the proposal answers percentage
- [x] Height of ProposalCard should be preserved even without pill
- [x] Filter padding is slightly off on the bottom-most option

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
