### ISSUE TITLE
[Task]: 

### ISSUE THREAD

**Issue by birddman** [iotaledger/firefly#5709]
### Task description

I have forgotten my firefly wallet password and need a reset link sent to my email address jonnierob2005@yahoo.com!

### Requirements

Need a reset password link sent!

### Creation checklist

- [X] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Unfortunately, we cannot send a reset link, since we do not have your private keys. If you have a stronghold back-up or a mnemonic (24 words), you can restore your wallet by creating a new profile and choosing the restore profile option.
