### ISSUE TITLE
[Task]: Add outdated Node URL state for removed proposals

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5716]
### Task description

We don't handle the fact that an event can be removed from a node. If that happens for events that haven't closed, we should have a warning pill and an option to re-register with a new node.  

### Requirements

- [x] Query poll once at login to get proposal status

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
