### ISSUE TITLE
[Task]: Reset Governance dashboard on wallet switch

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5727]
### Task description

Right now there is some issues when we switch an account because the event may not be added to each account. To solve this we should always reset and refresh the governance dashboard when we switch wallets or when we click on the governance tab icon.

### Requirements

- [x] Reset and refresh governance dashboard when switching accounts
    - [x] From the `GovernanceDashboardView`
    - [x] From the `ProposalDetailsView` 
- [x] Reset and refresh governance dashboard when clicking on the tab icon

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
