### ISSUE TITLE
[Task]: Check all the voting flows for ledger

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5759]
### Task description

Check if the following flows can be completed with ledger:

- [x] Increase/Decrease Voting Power
- [x] Vote/Unvote
- [ ] Revote

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
The flow for users that don't have blind signing enabled throws some errors. Also revoting has some issues, since rejecting a transaction is not handled correctly.

**Comment by Tuditi** [comment]
Blocked until: https://github.com/iotaledger/wallet.rs/issues/1820 is closed and released.
