### ISSUE TITLE
[Task]: Add option to add all events from a given node

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5769]
### Task description

At the moment we need an event ID to add a proposal. Alternatively we could add a checkbox/toggle to indicate that all events from a given node should be registered to.

### Requirements

- [x] Change the form to be... 
    1. `input: node URL`
    2. `checkbox: Add all proposals on this node`
    3. `input: event ID` (disabled if 2 is ticked)
    4. `checkbox: Add proposal to all accounts`
- [x] Change locales as necessary (e.g. for success)

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
