### ISSUE TITLE
[Task]: Cache participation overview for each account

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5784]
### Task description

When switching accounts, the proposal list often shows the state of the previous account, because it is still fetching. To avoid this, we should initially fetch all participation overviews and update that store each 10 sec

### Requirements

- [x] Create store for all participation overviews
- [x] use the cached store everywhere

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
