### ISSUE TITLE
[Task]: Update for next Assembly staking period (desktop)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5786]
### Task description

We need to update some things for the next Assembly staking period.

### Requirements

- [x] Branch off of `main`
- [x] Add `assembly_04.json` file to shared assets
- [x] Update `ASSEMBLY_EVENT_ID`
- [x] Update `ASSEMBLY_EVENT_START_DATE` (use `holding` event phase)
- [x] Update `ASSEMBLY_STAKING_BLOG_POST_URL`
- [x] Update `ASSEMBLY_STAKING_RESULT_FILES`
- [x] Update `LAST_ASSEMBLY_STAKING_PERIOD`
- [x] Update `CURRENT_ASSEMBLY_STAKING_PERIOD`
- [x] Update `ASSEMBLY_REWARD_MULTIPLIER`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
