### ISSUE TITLE
[Task]: Include trimming in TextInput

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#5792]
### Task description

We have a lot of inputs where we want the value to be trimmed e.g. all inputs for any type of address. 
Therefore we should add a `trim` prop to the textinput defaulting to false and add this prop to all address or url inputs where we currently manually trim the value.

### Requirements

- [ ] Add trim logic to textinput
- [ ] Add `trim` prop to all url inputs
- [ ] Add `trim` prop to all address inputs
- [ ] Add `trim` prop to all inputs where we currently trim manually

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
