### ISSUE TITLE
[Task]: Move `modals` to desktop `components` folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5801]
### Task description

These are desktop-specific components that don't belong in shared.

:no_entry_sign: There are a lot of "shared" components that use these modals, so there must be a plan for those before we move the modals themselves. 

### Requirements

- [ ] Move the `modals` component folder inside the desktop `components` folder
- [ ] Replace any relative import paths as necessary (see `ProposalDetailsMenu`)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
