### ISSUE TITLE
[Task]: Move `popups` to desktop `components` folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5803]
### Task description

These are desktop-specific components that should not be in the shared package.

### Requirements

- [x] Move the `popups` inside the desktop `components` folder
- [ ] Create name enum for popups
- [x] Remove relative import paths as necessary (see `SendFormPopup`)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
