### ISSUE TITLE
[Task]: Optimize Webpack bundler

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5826]
### Task description

Webpack has relatively slow bundling times, and while it would be best to upgrade the bundler entirely, it would also be worthwhile to explore optimizations we can make as an intermediary step.

### Requirements

- [ ] Look into using `eval-cheap-module-source-map`
- [x] Look into using `swc-loader` or `esbuild-loader` 
- [x] Rely on IDE for type checking, removing it from the development build process

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
https://webpack.js.org/guides/build-performance/
