### ISSUE TITLE
[Task]: Move `panes` to desktop `components` folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5828]
### Task description

These are desktop-specific components that don't belong in shared.

### Requirements

 - [x] Move the `panes` component folder inside the desktop `components` folder

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
