### ISSUE TITLE
[Task Tracker]: Refactor Drawers

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5871]
### Task description

As discussed, we should refactor the mobile drawers to be a hybrid between the current mobile drawers and the desktop popups

### Requirements

```[tasklist]
### Tasks
- [ ] #5872
- [ ] #5873
- [ ] #5874
- [ ] #5875
- [ ] #5876
- [ ] #5877
- [ ] #5878
- [ ] #5879
- [ ] #5880
- [ ] https://github.com/iotaledger/firefly/issues/5951
```

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
