### ISSUE TITLE
[Bug report]: Fix `Cannot destructure property 'participations' of 'p(...)' as it is undefined` 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5881]
### Task description

Reported in https://discord.com/channels/397872799483428865/988073611287994418/1075355467947180062

### Requirements

- [ ] Fix bug

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
