### ISSUE TITLE
[Task]: Move `Filter` from shared to desktop

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#5903]
### Task description

Filter and children components that are specific to the desktop should be moved from shared to desktop folder

### Requirements

- [ ] Platform-specific code that is shared is moved to its platform folder
- [ ] Any app behavior remains unchanged

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
