### ISSUE TITLE
[Task]: Move `deep-link` module to desktop `auxiliary` folder

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5918]
### Task description

The auxiliary modules contain routing logic, and they shouldn't. 

### Requirements

- [x] Polish `deep-link` module in current state
- [x] Design abstract interface for deep link manager
- [x] Implement deep link manager for desktop
- [x] Move `deep-link` module over
- [ ] Fix tests
- [ ] Figure out manager initialisation

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
