### ISSUE TITLE
[Task]: Improve revote flow

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5927]
### Task description

Revoting flow isn't working correctly with ledger device. Rejecting throws some errors and breaks the flow. This should be fixed.
Additionally, we will improve the revote flow as per requirements below.

### Requirements

- [ ] Add logic to determine if we need to revote
- [ ] Persist revote flag per account
- [ ] Add UI for the revote warning
- [ ] Add meatball menu with revote option

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
