### ISSUE TITLE
[Task]: Use PopupId everywhere to open popups 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5931]
### Task description

Recently we updated the opening of popups such that you can use the id either as a string OR as an enum. 
We tried to open the `BurnNativeTokenConfirmation` popup with the string, but that was outdated.

We should remove the option to use arbitrary strings as ID, and replace everything with the corresponding Enum

### Requirements

- [x] remove `| string` from id-type on `popup-state`
- [x] change every string into the `PopupId`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
