### ISSUE TITLE
[Task]: Correctly calculate storage deposit for foundry

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5932]
### Task description

The storage deposit breakdown for foundries doesn't align with the effective storage deposit on all foundries of the account. 
Check where the issue lies and fix it

### Requirements

- [ ] Correctly calculate SD for foundries

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
