### ISSUE TITLE
[Task]: Validate assetId on deeplinks

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5937]
### Task description

Currently it is possible to access the SendConfirmation page with an unknown assetId by using deeplinks.
Include a validation step to see if the assetId is known for this account.

### Requirements

- [x] Validate `assetId` on deeplinks

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Seems like it already validates if the asset exists in the account
![Image](https://user-images.githubusercontent.com/42754063/221320749-e659251c-190f-4dca-b306-cdeb4585b010.png)

**Comment by jeeanribeiro** [comment]
I'm working in validating the assetId format
