### ISSUE TITLE
[Task]: Update wallet.rs

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5939]
### Task description

We need a wallet.rs release with the following fixes:

- [x] NFT tag/metadata parsed as hex string instead of UTF-8 by wallet.rs
- [x] Unable to claim NFT's with gifted storage deposits in an empty wallet
- [x] Being able to register to all events on a registerParticipationEvent

### Requirements

TBD

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
