### ISSUE TITLE
[Task]: Claimed NFT shows up as burned 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5940]
### Task description

If user gets the storage deposit back from some NFT transaction, it is displayed as a `Burn NFT` activity. This is due to the fact that the user only sees the returned Basic output and the NFT as an input, which is interpreted on our side as burning.

A possible approach would be to extend the condition for burning, such that we check who the owner of the NFT in the inputs was

### Requirements

- [ ] Dont show SDRUC for NFTs as burning 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
