### ISSUE TITLE
[Task Tracker]: Hook native import/export logic

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5946]
```[tasklist]
### Tasks
- [ ] todo: list all onboarding places where we need export
- [ ] todo: list all onboarding places where we need import
- [ ] todo: list all dashboard places where we need export
```

Depends on https://github.com/iotaledger/firefly/pull/5667
