### ISSUE TITLE
[Task]: Improve error handling if user tries to add a proposal which isn't on the specified URL 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#5954]
### Task description

When trying to add/edit a proposal, if the specified `nodeId` isn't found on the specified `nodeUrl`, an error is thrown. The error message isn't very descriptive for the user. 

Improve the error message 

### Requirements

- [ ] Improve the error message

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
