### ISSUE TITLE
[Task]: Kickoff collectibes tab

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5982]
### Task description

Kickoff collectibes tab

### Requirements

- [ ] Add empty collectibles tab
- [ ] Hook tab routing logic
- [ ] Add feature flags (with all to disabled)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
