### ISSUE TITLE
[Task]: Collectibles Gallery View

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5983]
### Task description

add NFT Gallery & NFT Gallery item (ideally refactor shared components for both desktop & mobile if needed along the way)

### Requirements

- [ ] NFT Gallery
- [ ] Number of NFTs  in the gallery
- [ ] Refactor shared components if needed to make everything reusable or platform specific (avoid code duplication)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
