### ISSUE TITLE
[Task]: Collectibles Gallery View - Empty Receive

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5984]
### Task description

When there are not NFTs in the selected wallet, we should display the receive button & open the receive drawer upon click
⚠️ depends on the drawers refactors, ideally this task should be started after this PR has been merged https://github.com/iotaledger/firefly/pull/5953

### Requirements

 - [ ] Display text & button where there are no NFTs
 - [ ] Receive drawer

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
