### ISSUE TITLE
[Task]: Collectibles Gallery View - Search bar

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5985]
### Task description

Allow search in the mobile collectibles view

### Requirements

- [ ] Searchbar
- [ ] Search works
- [ ] No results text without receive button

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
