### ISSUE TITLE
[Task Tracker]: Selected NFT

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5986]
### Task description

List of tasks to be developed to support sleected NFT.
Depends on the drawers refactor

### Requirements

```[tasklist]
### Tasks
- [ ] [Task]: Selected NFT - Kickoff empty drawer
- [ ] [Task]: Selected NFT - NFT details
- [ ] [Task]: Selected NFT - NFT details - Show more toggle
- [ ] [Task]: Selected NFT - Send NFT (send nft only)
- [ ] [Task]: Selected NFT - View on Explorer
- [ ] [Task]: Selected NFT - NFT actions drawer
- [ ] [Task]: Selected NFT - View media in browser
- [ ] [Task]: Selected NFT - Burn NFT
```

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
