### ISSUE TITLE
[Task]: Update generic send drawer to include NFTs

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5987]
### Task description

Allow sending NFTs on mobile
⚠️ Ideally we should start this after the drawers refactor

### Requirements

- [ ] Tabbing
- [ ] NFT send flow

(do NOT include network selector)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
