### ISSUE TITLE
[Task]: Improve filters for mobile

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#5993]
### Task description

In mobile, dropdowns in the filter drawer dont work well, we should replace them with radio selectors

### Requirements

- [ ] Replace dropdowns with radio selectors
- [ ] Improve all filters UI
- [ ] Date selector

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
