### ISSUE TITLE
[Task]: Include Auto-Update for Shimmer app

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6015]
### Task description

For the Shimmer app, currently auto updating is disabled to make sure that the Iota app doesn't get updated to the Shimmer App. 

We want to enable auto updates now for the Shimmer app:
- The Iota App should not detect Shimmer updates
- A Shimmer alpha/beta should only detect newer alpha/betas
- A Shimmer prod should not detect newer alpha/betas

### Requirements

- [x] Re-add auto update logic on frontend
- [x] Re-add auto update logic on backend
- [x] Each release type should only update to the same type
- [x] Implement auto update for all platforms 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
