### ISSUE TITLE
[Task]: Fix scroll bar padding on Proposal List 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6016]
### Task description

Fix the padding between the ProposalList and the scroll bar

### Requirements

- [ ] Fix padding between ProposalList and scroll bar

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
