### ISSUE TITLE
[Task]: Fix text on DeleteAccountPopup

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6018]
### Task description

The Text on the DeleteAccount popup still says that `The wallet has no transaction history` which is now no condition anymore if a wallet is deletable or not.

Update the text to something more useful.

### Requirements

- [ ] Update text

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
