### ISSUE TITLE
[Task]: Improve enable blind signing popup for ledger

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6027]
### Task description

Most transactions (except basic transactions with no metadata/tag) require blind signing to be enabled on the ledger app. When a user hasn't enabled this, sending a transaction requires a prepared output to be stored, so that FF can resend it automatically whenever the user has enabled blind signing. 

This is problematic, since wallet.rs doesn't expose prepare outputs for all types of transactions (e.g.: Governance, mint NFTs, ...).
*Might be fixed if https://github.com/iotaledger/wallet.rs/issues/1821 gets implemented and released.*

Alternatively, FF can detect whether blind signing has been enabled and show a popup to enable this on certain tabs (Dashboard/NFT/...). We would need a design for a popup that warns the user that they should enable blind signing before attempting to perform a transaction.

### Requirements

- [ ] Design for a popup

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
