### ISSUE TITLE
[Task Tracker]: Update wallet.rs to latest version

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6068]
### Task description

Update the wallet.rs version to the latest version that includes the updated stronghold version and APIs to perform the stronghold snapshot migration.

### Requirements

- [ ] Update `wallet.rs` version
- [x] Update `definitions.ts` within Capacitor bindings folder
- [x] Update Java bindings:
    - [x] Add a `fn Actor::` function in https://github.com/iotaledger/wallet.rs/blob/d773dc82a3a6ea50ecf2fdd6b1b8e0a381c72af5/bindings/java/native/src/java_glue.rs.in
    - [x] Expose migration function within the `WalletPlugin.java` file
    - [x] https://github.com/iotaledger/wallet.rs/commit/d773dc82a3a6ea50ecf2fdd6b1b8e0a381c72af5
- [x] Update Swift bindings (see [this](https://github.com/iotaledger/wallet-ios-internal) repo):
    - [x] Expose migration function in `Plugin.swift`
    - [x] Hook up migration function in `Plugin.m`
    - [x] Edit [`iota_wallet_ffi.h`](https://github.com/amadeu2/wallet.rs/blob/add-swift-folder/bindings/swift/native/iota_wallet_ffi.h) file as needed
    - [x] Edit [`wallet_actor.rs`](https://github.com/iotaledger/wallet.rs/blob/production/bindings/java/native/src/classes/actor/wallet_actor.rs) file as needed (@thibault-martinez)
    - [x] Edit [`lib.rs`](https://github.com/amadeu2/wallet.rs/blob/add-swift-folder/bindings/swift/native/src/lib.rs) as needed
    - [x] Edit [header file](https://github.com/amadeu2/wallet.rs/blob/add-swift-folder/bindings/swift/native/header.h) as needed

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/7009
- [ ] https://github.com/iotaledger/firefly/issues/7010
```

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
