### ISSUE TITLE
[Task]: 17. Add real stronghold version used to the profile creation

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6109]
### Task description

atm we are using `const STRONGHOLD_VERSION = 1` and it might be worth adding the real stronghold version so we can detect the real version in future releases

- [x] Update Stronghold version to 2
- [x] Update function to determine up to date strongholds

### Requirements

- Add real stronghold version once we know the real version number
- Update `isStrongholdUpdated` function to check version in the form `x.y.z`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
