### ISSUE TITLE
[Task]: Move UpdateStronhold logic into own folder

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6120]
### Task description

Currently we have the logic and components for UpdateStronhold in the `login` folder.
Because this is used also on the onboarding flow, we extract it into its own folder 

### Requirements

- [x] Move UpdateStronhold logic into own folder

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
