### ISSUE TITLE
[Task]: Royalties input allows raw numbers 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6126]
### Task description

A tester found that our royalties input allows raw numbers (e.g. `royalties = 4`). This is because we only check if it is valid JSON format, and not explicit if it is an object. 

### Requirements

- [ ] Add isObject validation to royalty input 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
