### ISSUE TITLE
[Task]: Fix auto upgrade toasts

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6128]
### Task description

The toasts shown on the auto upgrade flow are broken. They always show `dismiss` instead of the `Download` button, the progress bar and the `Install` button. 

### Requirements

- [ ] Fix toasts

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
