### ISSUE TITLE
[Task]: 6. Add update stronghold view and UI to update stronghold router

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6140]
### Task description

After the user has entered the pin from a profile not using the latest stonghold, they will get routed to the stronghold migration process which starts with the view “update stronghold”. 

### Requirements

- [x] Create view with all necessary UI components
- [x] Add view into the stronghold router

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
