### ISSUE TITLE
[Task]: 7. Add logic to update stronghold view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6141]
### Task description

Now that we have the UI for updating a stronghold we need to add the logic to perform this action. Involving a call to the [wallet.rs](http://wallet.rs/) to to migrate the stronghold snapshots.

### Requirements

- [x] Add logic to migrate stronghold with [wallet.rs](http://wallet.rs/)
- [x] Add logic to store new Stronghold version for created profiles 
- [x] Ensure back button capability
- [x] Ensure wrong password error comes first

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
