### ISSUE TITLE
[Task]: 11. Amend logic and UI in backup stronghold view

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6145]
### Task description

If we are using the existing stronghold backup view inside the update stronghold router / flow we need to update the ui to show different locales if part of this flow and the necessary recommendation hints.

### Requirements

- [x] Adjust locales based on flow
- [x] Add recommendation hint if in the update stronghold flow
- [x] Save backup time in new profile
- [x] Fix UX for import password view

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
