### ISSUE TITLE
[Task]: Add loading animation on NFT media which is currently downloading

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6151]
### Task description

We download images one at a time. Therefore it is important to show to the user, which images are already downloaded (or were tried to download), which are currently downloading, and which are in queue

### Requirements

- [ ] Create a store which contains the NFT id for the currently downloading file
- [ ] Add pulsating animation on downloading NFT
- [ ] Add icon to hint that the NFT isnt yet attempted to be downloaded

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
