### ISSUE TITLE
[Task]: Use different thumbnails on different components

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6152]
### Task description

To improve rendering speed and don’t crash the application if a lot of media is rendered, it is required to render the most optimal images for each component.
Therefore each place where we render an NFT image, should use one of the thumbnails with the closest fitting size.

### Requirements

- [ ] Store thumbnails in multiple files
- [ ] Add size property in NftMedia
- [ ] Display Image with corresponding size

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
