### ISSUE TITLE
[Task]: Generate thumbnails for videos

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6153]
### Task description

For small places where we would render a video, we just want to display a generated thumbnail. Same as in [task] (https://github.com/iotaledger/firefly/issues/6152), we need multiple sizes for different places.
Only on the biggest places, we want to show the actual video.

### Requirements

- [ ] Generate thumbnails for video
- [ ] Show thumbnail in NftMedia if small size is specified
- [ ] Show video in NftMedia if large size is specified

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
