### ISSUE TITLE
[Task]: Implement manual download for NFT media

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6154]
### Task description

If a NFT does not match the specified settings, it doesnt get downloaded. But the user should be able to manually trigger a download for an NFT

### Requirements

- [ ] Add a “Download” button to the NFT details menu
- [ ] Start download/resize pipeline

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
