### ISSUE TITLE
[Task]: Add setting for IPFS Gateway URL

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6155]
### Task description

Currently we download images from IPFS with one of the https gateways.
Some users might change the gateway if e.g. they own one themself. Therefore we need to include a setting to input the desired gateway (defaulting to `https://ipfs.io/ipfs/`)

### Requirements

- [ ] Add Setting section for IPFS Gateway URL
- [ ] Add Text input for url
- [ ] `composeUrl` should use the url specified in this setting

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
