### ISSUE TITLE
[Task]: Add setting for allowed file types

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6156]
### Task description

Currently we try to download all images, videos (and audio in the future).
The users should be able to specify which types they want and don’t want. We need a setting where the user can select those types.

### Requirements

- [ ] Add Setting section for allowed file types
- [ ] Add checkboxes for “Image”, “Video” and “Audio”
- [ ] Use allowed file types in pre-download validation

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
