### ISSUE TITLE
[Task]: Unset NFT as Profile Image

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6157]
### Task description

As a user i want to be able to unset the currently selected profile image

### Requirements

- [ ] Add reset button in Settings to clear Profile Image

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
