### ISSUE TITLE
[Task]: Unset NFT as Profile Image if NFT is not owned anymore

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6158]
### Task description

If the user spends the NFT which they assigned as profile image, the profile image should be unset

### Requirements

- [x] If an NFT is spent, unset the profile image

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
