### ISSUE TITLE
[Task]: Add `Collection` tab to GalleryView

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6159]
### Task description

On the NFT gallery view, we need a second tab, which includes all NFTs grouped together collection.
Each list item should contain a random image as a thumbnail, the collection name + how many NFTs are in this collection.

### Requirements

- [ ] Add second tab to gallery view
- [ ] Show list of collections

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
