### ISSUE TITLE
[Task]: Add `Collection` details view

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6160]
### Task description

If the user clicks on a collection item, the user gets directed to the collection details view, which (for now) looks like the NFT gallery, but only containing NFTs from the selected collection

### Requirements

- [ ] Create Collection Details View as NFT list

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
