### ISSUE TITLE
[Task]: Add Search to `Collection` tab

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6161]
### Task description

Same as on the NFT tab, we need a search input to search through the collections.

### Requirements

- [ ] Add Search Input on Collections Tab
- [ ] Search for collectionId or collectionName
- [ ] Add search logic to only show collections which match the search value

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
