### ISSUE TITLE
[Task]: Add Audio player to NFT details

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6162]
### Task description

If the NFT Media contains a audio file type, the user should be able to listen to it inside Firefly.

### Requirements

- [ ] Add audio player to NFT Details

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
