### ISSUE TITLE
[Task]: Periodically delete logs for dev, alpha & beta builds

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6176]
### Task description

At the moment, we enabled logs for debugging purposes in the alpha, beta & dev builds. These files can quickly become quite large, so we need to find a way to delete them if they are outdated (newer beta version is downloaded).

### Requirements

- [x] Remove logs for older versions
- [x] Remove logs older than 30 days

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
