### ISSUE TITLE
[Task]: Add Sentry support for Firefly Shimmer Desktop

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6177]
### Task description

We need to add support for this version of the app, so that we can receive more detailed information about errors that are occurring in an automated way. 

### Requirements

- [x] Setup `firefly-shimmer-desktop` project in Sentry dashboard
- [x] Create DSN / client key for project
- [x] Add DSN to GitHub
- [x] Adjust desktop build workflow to use new DSN
- [x] Change `project` in webpack config to `firefly-shimmer-desktop`
- [x] Update `.sentrycliignore` as necessary
- [x] Simplify process to enable Sentry if possible (e.g. more sensible / less env vars)
- [x] Disable feature flag for "Crash reports"
- [x] Ensure no PII is being sent to Sentry
- [ ] Test with remote GH workflow 
- [x] Add Sentry information to documentation
- [x] Ensure releases are sent to correct project
- [ ] Delete extra keys when finished
- [ ] Use IPC to handle errors from renderer

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
