### ISSUE TITLE
[Task]: Vote button is active right after voting 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6184]
### Task description

After setting a vote on a `counting` proposal, after the vote has been confirmed, the `Vote` button should be disabled because the already set vote is selected.

[Screencast from 15-03-2023 11:12:11.webm](https://user-images.githubusercontent.com/105642810/225282431-ddeeb8e3-b78f-4ae5-ba97-ca5379c80be7.webm)

### Requirements

- [x]  Update vote button state on voting

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
