### ISSUE TITLE
[Task]: Fix squished proposal information

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6195]
### Task description

If the proposal description is long, the rest of the information gets squished together.

### Requirements

- [ ] Fix text overflowing into other panes

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
