### ISSUE TITLE
[Task]: Hide/unhide NFTs in Collectibles gallery

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6203]
### Task description

In the NFT details view, add a button to the menu to hide/unhide this NFT.
Hidden NFTs shouldnt be displayed in the gallery, related activities should still be shown.

### Requirements

- [ ] Impement hide/unhide button in NFT details view
- [ ] Hide NFTs in gallery

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
