### ISSUE TITLE
[Task]: Add Filter to Collectibles Gallery

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6204]
### Task description

Add a filter button to the Collectibles Gallery. The opened modal should contain a filter to `Show hidden` Nfts.
After applying the filter in the popup, the list of collectibles should be updated 

### Requirements

- [ ] Add Filter button + modal to collectibles
- [ ] Implement `Show hidden` filter

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
