### ISSUE TITLE
[Task]: Proposal questions are not collapsible

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6207]
### Task description

If clicked on a proposal question, the text gets collapsed, but the answers are still shown. 

### Requirements

- [ ] Make questions collapsible again

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
