### ISSUE TITLE
[Task]: Add media validation to MintNftForm

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6219]
### Task description

It often happens that users mint nfts and dont set the correct `filetype`. 
On the Form popup, add a validation to check if the type of the media is equal to the specified file type. Use `fetch` to get the `HEAD` behind media url

### Requirements

- [x] Add check if media type matches the specified type

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
