### ISSUE TITLE
[Task]: Refactor getOutputOptions

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6221]
### Task description

Refactor get output options to accept an object instead of 3+ arguments.

### Requirements

- [ ] Add tests

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
