### ISSUE TITLE
[Task]: Add fault tolerance to NFT download for unreachable urls

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6226]
### Task description

It can happen that the server doesnt return anything. If this happens, the whole pipeline stops working.

Implement a stop condition after a certain amount of time

### Requirements

- [ ] Implement a stop condition after a certain amount of time

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
