### ISSUE TITLE
[Task]: Load NFT immediatly after validated

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6227]
### Task description

Currently the nfts are only shown after all of the nfts are validated. Improve this by loading each nft individually once it is validated/downloaded

### Requirements

- [ ] Update NFT instant after validation
- [ ] Update NFT instant after download

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
