### ISSUE TITLE
[Task]: Improve NFT loading performance

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6228]
### Task description

The initial load for NFTs takes up quite some time, but there are a few improvements we can do.

### Requirements

- [x] Only start downloading NFTs for selected account when going to the NFT gallery
- [x] Parallelize initial validation to load things immediately 
- [x] If we didnt finish download all `nftsToDownload` on account switch, we should interrupt that

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
