### ISSUE TITLE
[Task]: Upgrade Python version in CI

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#6236]
### Task description

For the macOS build, we get the error that it doesnt support `python2` anymore. Therefore we get an error when setting that up. Upgrade it to version 3

### Requirements

- [x] Upgrade Python2 to Python3 in CI

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
