### ISSUE TITLE
[Task]: Upgrade deprecated features of the CI

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6238]
### Task description

Github depraced the use of `set-outptus` and `save-state`. Upgrade our CI to use the new approach: https://dev.to/cicirello/how-to-patch-the-deprecated-set-output-in-github-workflows-and-in-container-actions-9co

### Requirements

- [x] Upgrade `set-outptus`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
