### ISSUE TITLE
[Task]: Update mobile icon assets to latest shimmer

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6244]
### Task description

We have a new icon set for alpha, beta & production https://github.com/iotaledger/firefly/tree/develop/packages/desktop/public/assets/icons

### Requirements

- [ ] Working assets in app icon

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
