### ISSUE TITLE
[Task]: Improve check if Nft media is downloaded

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6252]
### Task description

Currently we check if the Nft s already downloaded by `fetch`ing the path. This has the downside that it logs a lot of 404 for files that dont exist.

Write a Electron endpoint `isNftMediaDownloaded` which checks if the file exists (maybe by using `fs`)

### Requirements

- [x] Write a Electron endpoint `isNftMediaDownloaded` which checks if the file exists

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
