### ISSUE TITLE
[Task]: Rename `nfts` core module to `nft`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6258]
### Task description

This module name is plural, implying that it contains multiple types of the same object / code / etc. Instead it's a collection of logic related to NFTs, so the name should be singular.

### Requirements

- [ ] Rename the module

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
