### ISSUE TITLE
[Task]: Remove `.vscode` directory from root

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6260]
### Task description

It contains a single file `launch.json` that is used for debugging the (old) backend NodeJS bindings. Although the file referenced is of the same name and location, we no longer use the backend like in V1, so we should remove this.

### Requirements

- [ ] Remove `.vscode` folder
- [ ] Add `.vs/` and `.vscode/` folders to `.gitignore`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
