### ISSUE TITLE
[Task]: Adjust `@features` path alias / `features` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6262]
### Task description

Currently when we read from the features, we have to write imports like this:
```typescript
import features from '@features/features'

console.log(features.governance.enabled)
```

It would be much cleaner if we could write them as such:
```typescript
import { governance } from '@features'

console.log(governance.enabled)
```

Perhaps that name is too generic, in which case this would also be better:
```typescript
import { features } from '@features'
```

### Requirements

- [ ] Implement preferred usage

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
