### ISSUE TITLE
[Task]: Breakup the `wallet` core module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6263]
### Task description

The `wallet` core module contains lots of code that could be in a better place.

### Requirements

- [ ] Create `activity` core module
- [ ] Move NFT-related code to `nft` core module
- [ ] Move token-related code to `token` module
- [ ] Move minting- / burning-related code to `developer` context module
- [ ] Move participation-related code to `governance` context module

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
