### ISSUE TITLE
[Task]: Update Sentry SDK to latest version

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6280]
### Task description

While we are currently using the Sentry SDK, the version is the same as what we initially used in V1, so we should update to the latest version. It's likely that there will be some breaking changes, mainly with where the distribution files are at within the NPM package and also using a specific distribution file for the preload script.

:no_entry_sign: Blocked until #6177 is completed.

### Requirements

- [ ] Update `@sentry/electron` to latest version*
- [ ] Update `@sentry/webpack-plugin` to latest version*
- [ ] Fix existing code and configuration as needed (will likely need to modify `sentry.js` and `preload.js`)

\* It's most likely best to do these separately to see if only one of them causes an issue.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
