### ISSUE TITLE
[Task]: Add "phone home" error for Sentry reporting

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6281]
### Task description

To help us get more accurate information about our user base, we can send an empty "phone home" error to Sentry whenever a user starts the application.

### Requirements

- [ ] Add a call to `Sentry.captureException` with a "fake" error when the user starts the app

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
