### ISSUE TITLE
[Task]: Create global NFT download queue

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6284]
### Task description

We need a global downloading queue store where new NFTs can be added from everywhere. This queue will then be processed one by one

### Requirements

- [ ] make download queue global
- [ ] on incoming NFT, push item to queue

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
