### ISSUE TITLE
[Task]: Interrupt download if it is taking too long 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6287]
### Task description

If a download is taking too long, we should interrupt it, such that the other downloads can continue

### Requirements

- [ ] Interrupt download if it is taking too long 
- [ ] Remove item from queue

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
