### ISSUE TITLE
[Task]: Add MaxDownloadTime setting 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6293]
### Task description

If a download takes too long, the download will be interrupted after a fixed amount of time. 
We should include a setting to let the user choose the desired max amount

### Requirements

- [ ] Add MaxDownloadTime setting 
- [ ] If the settings changed, try to download all NFTs which have been timed out

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
