### ISSUE TITLE
[Task]: Upgrade to NodeJS 18 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6299]
### Task description

Now with version 18 of NodeJS having been released, it would be worthwhile upgrading. This affects nearly our entire stack, so there are lots of things to test and verify are still working.

Be sure to update your local node version as well.

### Requirements

- [ ] Check compatibility with...
    - [ ] `wallet.rs` NodeJS bindings
    - [ ] Jest
    - [ ] ESLint / Prettier
    - [ ] Retype
- [ ] Update workflows:
    - [ ] `build-desktop.yml`
    - [ ] `ci.lint.yml`
    - [ ] `ci.test.yml`
    - [ ] `ci.ts.yml`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by marc2332** [comment]
Closing as chrysalis is deprecated and both Firefly Shimmer and Firefly IOTA are using NodeJS 18.
