### ISSUE TITLE
[Task]: Make `clearFilters` utils function generic

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6301]
### Task description

This function inside of the `utils` core module should be made generic so that we can remove the dependencies on higher-level modules and de-duplicate code. Rather than procedurally resetting filters inside the function, we can simply pass it as many filter stores as we'd like and have it reset each one. If needed we can write a higher level function `clearAllFilters` that calls `clearFilter` for all filters.

E.g.
```typescript
export function clearFilter(filter: Writable<unknown>): void {
    filter.update((state) => {
        for (const key in state) {
            state[key].active = false
            state[key].value = undefined
        }
        return state
    })
}
```

Or
```typescript
export function clearFilters(...filters: Writable<unknown>[]): void {
    for (const filter of filters) {
        filter.update((state) => {
            for (const key in state) {
                state[key].active = false
                state[key].value = undefined
            }
            return state
        })
    }
}
```

### Requirements

- [ ] Implement generic method for clearing a filter or multiple filters
- [ ] Remove `clearFilters.ts` from core utils module and move logic to `ui.ts`

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
