### ISSUE TITLE
[Task]: Write unit tests for core `utils`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6302]
### Task description

Since these are lower-level functions usable potentially anywhere in the application, they should be tested to make sure that they are working as intended. 

To keep the changes clean and concise, please create a sub-task for each module listed below when it comes time to work on it. Put the tests inside of `packages/shared/lib/core/utils/tests`.

### Requirements

:red_circle: High priority
- [x] `convert.ts` (@maxwellmattryan)
- [x] `string.ts` (@MarkNerdi) #6772
- [x] `unit.ts` (@jeeanribeiro) #6674
- [x] `time.ts` (@kraftjs) #6673 
- [ ] `validation.ts` (@maxwellmattryan)
- [x] `object.ts` (@MarkNerdi)
    - [x] Remove `deepCopy` and replace with native `structuredClone`
- [x] `date.ts` (@jeeanribeiro) #6679
- [x] `math.ts` (@kraftjs) #6675

:yellow_circle: Medium priority
- [ ] `encode.ts` (@maxwellmattryan)
- [ ] `iter.ts` (@MarkNerdi)
- [x] `number.ts` (@jeeanribeiro) #6680
- [x] `format.ts` (@kraftjs) #6678 
- [ ] `random.ts` (@maxwellmattryan)
- [ ] `sort.ts` (@MarkNerdi)
- [x] `function.ts` (@jeeanribeiro) #6681
- [x] `ui.ts` (where applicable) (@kraftjs) #6768 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
