### ISSUE TITLE
[Task]: Rename `tests` directory to `test`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6303]
### Task description

This module isn't a collection of tests, but rather setup / config for all of the tests, so it's name should be reflective of that.

### Requirements

- [ ] Change directory name from `tests` to `test`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
