### ISSUE TITLE
[Task]: Move `filter` utils to core `wallet` module

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6304]
### Task description

This function deals explicitly with domain-related logic and concepts, so it does not belong inside the core `utils` module. 

### Requirements

- [ ] Move code inside `filter.ts` to `core/wallet/utils`
- [ ] Delete `filter.ts` file

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
