### ISSUE TITLE
[Task]: Write tests for core `nfts` utils and helpers

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6306]
### Task description

We need tests for this module.

### Requirements

- [ ] Write tests for **all** utils

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
