### ISSUE TITLE
[Task]: Write tests for core `wallet` utils and helpers

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6307]
### Task description

This is a large module with lots of functionality that should be tested.

### Requirements

- [ ] Write tests for **all** helpers
- [ ] Write tests for **all** utils (where possible)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
