### ISSUE TITLE
[Task]: Write tests for context `settings` utils and helpers

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6308]
### Task description

We need tests here!

### Requirements

- [ ] Write tests for **all** utils

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
