### ISSUE TITLE
[Task]: Write tests for context `onboarding` utils and helpers

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6309]
### Task description

There's lot of functionality here that needs tests.

### Requirements

- [ ] Write tests for **all** helpers (where possible)
- [ ] Write tests for **all** utils

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
