### ISSUE TITLE
[Task]: Write tests for context `governance` utils and helpers

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6310]
### Task description

Lots of functionality that needs testing!

### Requirements

- [ ] Write tests for **all** utils (where possible)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
