### ISSUE TITLE
[Task]: Migrate handbook documentation to Notion

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6311]
### Task description

Now that we are using Notion internally, we no longer have a need for the handbook. It will instead be "re-purposed" into the Firefly Docs.

### Requirements

- [x] Migrate guides
    - [x] Coding Conventions
    - [x] Environment Setup
    - [x] Git
    - [x] Developer Tips
    - [x] Testing 
- [ ] Migrate SOPs
    - [ ] Development
    - [ ] Security 
- [ ] Migrate specifications
    - [ ] Activities
    - [ ] Onboarding
    - [ ] Governance
    - [ ] Library Modules 

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
