### ISSUE TITLE
[Task]: Re-brand handbook for external docs

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6312]
### Task description

We need to make some changes in order to re-brand the handbook into a documentation site for external developers.

:no_entry_sign: Blocked until all documentation has been migrated (see #6311)

### Requirements

- [ ] Modify `retype.yml` configuration file:
    - [ ] Change title to "Firefly Docs"
    - [ ] Remove Wiki link
    - [ ] Put GitHub link first before (then issues then discussions) 
- [ ] Write an "Introduction" page
- [ ] Write a "Getting Started" page
- [ ] Create a "Deep Links" section
    - [ ] Write a "Wallet" page
    - [ ] Write a "Collectibles" page
    - [ ] Write a "Governance" page

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
