### ISSUE TITLE
[Task]: Update `yarn.lock` file 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6320]
### Task description

The lock file is out of sync and needs to be updated for the `develop` branch.

### Requirements

- [x] Update `yarn.lock`

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
