### ISSUE TITLE
[Task]: Add arrow key support for dropdowns

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6322]
### Task description

Having arrow key support for dropdown inputs would be really nice :pray: 

### Requirements

- [ ] Add arrow key support for dropdowns
- [ ] Add sensible styling for highlighted option
- [ ] Check dropdowns throughout the app (recipient for sending, node URL for proposals, etc.)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
