### ISSUE TITLE
[Task]: Add feature flag for NFT caching

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6324]
### Task description

We dont have the required native code yet for caching NFTs on mobile. To still be able to show nfts, we want to feature flag it, such that mobile can use the old implementation

closes: https://github.com/iotaledger/firefly/issues/6363

### Requirements

- [x] Add feature flag

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
