### ISSUE TITLE
[Task]: 5b. Adjust update Stronghold flow for onboarding

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6336]
### Task description

This flow needs to be implemented for both login _and_ recovery.

### Requirements

- [x] Adjust routing to work from login (no subviews)
    - [x] Ensure back button functionality
- [x] Adjust routing to work from profile recovery
    - [x] Ensure back button functionality
    - [x] Ensure profile is successfully created
    - [x] Update locale to reflect recovery flow
- [x] Remove password input if in recovery

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
