### ISSUE TITLE
[Bug report]: Whitescreen after token claim/send

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#6349]
### Task description

A few user reported a whitescreen after they tried to claim native tokens (https://discord.com/channels/397872799483428865/1091063037420638290)
It is reproducable on compiled versions,  but only on the ones created with GHA

Maybe it is connected with the tokens not being of accurate IRC30 standard.

### Requirements

- [ ] Investigate and find issue

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Useful logs: https://github.com/iotaledger/firefly/issues/6201

**Comment by begonaalvarezd** [comment]
@brancoder would be nie trying to reproduce this issue and see if it still is a problem. If not, I would close it

**Comment by brancoder** [comment]
Closing the issue as I can't reproduce it any more. @MarkNerdi996 please reopen if issue is still occurring and provide the steps to reproduce :pray:
