### ISSUE TITLE
[Task]: Adjust crash report setting logic / UI

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6352]
### Task description

While crash reporting is enabled by default, the setting to toggle it on / off is disabled because we need more UI/UX to help the user. Currently, an app restart is required for a change to the "crash reports" setting to take effect. We can either:
- (Ideal) Add logic before sending to detect if the setting is enabled (the problem here is the main process having access to that data)
- (Easy) Add UI text hint telling the user e.g. "Please restart Firefly for this change to take effect."

### Requirements

- [ ] The setting works for the renderer process 
- [ ] The setting works for the main process

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
