### ISSUE TITLE
[Task]: Migrate Webpack config to TypeScript

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6363]
### Task description

With our feature flags being in TypeScript, we cannot currently use them inside of the Webpack config.

### Requirements

- [x] Migrate `webpack.config.js` to TypeScript

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
