### ISSUE TITLE
[Task]: Add `NetworkButton` to top navigation bar

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6365]
### Task description

- [ ] The network icon should move to the top navigation according to this design.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
