### ISSUE TITLE
[Task]: Use `NetworkIconBadge` in `AssetIcon` component

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6371]
### Task description

We will replace the verification status icon with a network icon for native tokens ~~and L2 tokens~~ (will come later when we add support for that).

### Requirements

- [x] Use `NetworkIconBadge` in `AssetIcon`
- [x] Show badge if native token (or L2 asset) in the future

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
