### ISSUE TITLE
[Task]: Add `NetworkCard` component to `ConnectedChainsDrawer`

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6373]
### Task description

We need a reusable network card that contains information about the connected Network. Initially it will have the following fields:

- Name
- Chain address 
- Status (stub out)
- QR code icon
- Generate address button (for Ledger profiles **only**)

### Requirements

- [ ] Hard-code details for Shimmer network
- [ ] Hard-code details for ShimmerEVM network

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
