### ISSUE TITLE
[Task]: Add support for connecting to L2 ISCP Network

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6377]
### Task description

With the UI in place, we want to add support to actually connect with a WASP node. Initially we can add a simple API call for the node's health and log it to the console (eventually will be displayed within the corresponding network card).

See the [REST API](https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/wasp/develop/clients/apiclient/api/openapi.yaml) for more information about available endpoints. We can use the `/health` endpoint specifically.

### Requirements

- [x] Add `INetwork` interface def
- [x] Add `IChain` interface def
- [x] Create `INetwork` class impl.
- [x] Create `IChain` class impl. (`IscpChain` vs `EvmChain`)
- [x] Instantiate `INetwork` and `IChain` classes on login
- [x] Destroy `INetwork` and `IChain` classes on logout
- [x] Add `web3.js` to shared
- [ ] ~~Add intermediate abstraction beneath `IChain` for client library (goal is to be able to swap out impls easily)~~ (will be done when necessary but keep in mind so that this task is as easy as possible in the future)
- [ ] ~~Implement generics to avoid type casting all the time~~ (can be cleaned up later w/ factory class)
- [x] Add ShimmerEVM by default
    - [x] Add constant for ShimmerEVM chain metadata
    - [x] Add this metadata to every profile during onboarding
    - [x] Ensure existing profiles have this metadata also
    - [ ] Handle "chain already added" error for this specific case 
- [ ] Update tech. spec. as needed (will do when merged)

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
