### ISSUE TITLE
[Task]: Add `AddChainDrawer`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6380]
### Task description

This form is to added to the sidebar without any logic (purely UI).

### Requirements

- [x] Create the `AddChainSideDrawerView` component
- [x] Create the `AddChainForm` component and use here

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
