### ISSUE TITLE
[Task]: Received locked NFT showing as minted instead of received

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6390]
### Task description

Received locked NFT showing as minted instead of received

### Requirements

- [ ] Fix wrong type for NFT activity

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Cant reproduce it, tried sending internal and external transfers and it displays correctly in all cases.
Closing issue for now, please reopen if the issue re-spawns
