### ISSUE TITLE
[Task]: Allow minting nft with raw json

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6392]
### Task description

On the MintNFT form, we should allow to enter a raw json string instead of our inputs.
Add a second tab or switch button to switch between the inputs and the json input.

### Requirements

- [ ] Allow minting nft with raw json

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
