### ISSUE TITLE
[Task]: Add "Refresh NFT" button in Settings 

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6393]
### Task description

If some downloads fail or some new feature (e.g. resizing) is implemented, we need the ability to refresh NFT media. This means that we delete all existing nfts for the current profile, and then add them again to the downloadqueue

### Requirements

- [ ] [Task]: Add "Refresh NFT" button in Settings 
- [ ] Delete NFTs and re-download them

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
