### ISSUE TITLE
[Task]: Add `SideDrawer` component 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6403]
### Task description

With the `NetworkButton` in the top navigation bar, clicking it needs to open the side-drawer component.

### Requirements

- [ ] Create `Drawer` (desktop-specific) component
    - Re-use mobile `Drawer` if possible (?)
- [ ] Create `SideDrawer` wrapped on top of `Drawer` (?)
- [ ] Create `NetworkSideDrawer` (will contain the various side drawer views for this milestone) 
- [ ] Close side drawer when user clicks "X" or clicks outside of it

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
