### ISSUE TITLE
[Task]: Add `ChainInformationDrawer`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6404]
### Task description

When a user clicks on a `NetworkCard`, they will be brought to a view (within the sidebar) that displays the corresponding information for that network (chain ID, chain address, node URL, explorer URL, etc.).

If the user clicks on the L1 `NetworkCard` it should bring them to the network settings.

### Requirements

- [x] Add `IscpChainInformation` component for ISCP chains

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
