### ISSUE TITLE
[Task]: Rename `INetwork` interface to `INetworkInfo` 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6416]
### Task description

To reduce confusion once we begin adding L2 network support, we need to rename the `INetwork` interface to `INetworkInfo` as per the technical design spec.

### Requirements

- [ ] Rename `INetwork` interface to `INetworkInfo`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
