### ISSUE TITLE
[Task]: Consolidate 16 outputs instead of 128 for Ledger Nano S 

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#6429]
### Task description

If a user uses Ledger Nano S and they try to create a transaction with more than 16 outputs, it will fail because that lkedger only supports 16 outputs.

In manual consolidation, we should check what the user uses and then consolidate either 128 or 16 outputs.

### Requirements

- [ ] Enable consolidation for only 16 outputs

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Is this an issue in wallet.rs? Do we have control over this?
