### ISSUE TITLE
[Task]: Add 'locked' status option in ActivityList filter

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6430]
### Task description

Transactions shown in the Activity Section of Firefly Shimmer can not be filtered for locked in the status field so this feature should be added.

### Requirements

- [ ] ActivityList filter status option has the 'locked' option
- [ ] The filter works as expected 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
