### ISSUE TITLE
[Task]: Remove `rust` linting job

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6434]
### Task description

This job within the linting workflow is not needed for Firefly V2 since we've removed the Rust-based backend actor system.

### Requirements

- [x] Remove the `rust` job from the linting workflow
- [x] Separate `js` job into `format` and `lint` jobs

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
