### ISSUE TITLE
[Task]: Cancel downloads on RefreshNftMedia

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6476]
### Task description

If you click a lot of times the "Refresh NFT Media" button, it will start downloads again and again. With this, we again get the errors of parallel downloads in electron (e.g. wrong filenames).

We should stop the current download and clear the download queue first, and then start everything

### Requirements

- [ ] Stop current download and clear download queue on "Refresh" click

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
