### ISSUE TITLE
[Task]: Create router for side drawer component

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6505]
### Task description

With the side drawer created, we need to hook up an actual router to it. 

### Requirements

- [x] Add `NetworkConfigRouter` class, implementing `Router` base class
    - [x] Initialise in `NetworkConfigDrawerRouter.svelte` in `onMount`, setting underlying store
    - [x] Destroy / reset store in `onDestroy`
- [x] Hook up to initial `ConnectedChainsSideDrawer` component
- [x] Add back button functionality
- [x] Style back button properly
- [x] Hook up to other side drawer views in the flow (stub them out with title and text to move between flows):
    - [x] `ChainInformationSideDrawer`
    - [x] `AddChainSideDrawer`
    - [x] `ChainDepositAddressSideDrawer`
    - [x] `EditChainSideDrawer`
    - [x] `RemoveChainSideDrawer`
- [x] Create `DrawerHeader` component
- [x] Move `Drawer.svelte` to `drawers` folder
- [x] Type `DrawerRoute`
    - [x] Adjust component code to use new type

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
