### ISSUE TITLE
[Task]: Create `EventFn` type for UI event handlers

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6506]
### Task description

We are defining this UI event handler function type in every component, when it should be defined once and re-used where applicable.

E.g.
```typescript
type EventFn = () => void // could possible use a union with 'unknown' but handler functions by convention shouldn't return anything
```

Potentially `EventFn` isn't descriptive enough given we have events from `wallet.rs` that we handle (even though those would be of the same type, i.e. a function that returns nothing).

### Requirements

- [ ] Define `EventFn` type (probably best in `utils`)
- [ ] Replace duplicated code where possible in the UI components

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
