### ISSUE TITLE
[Task]: Fix delete profile in settings not working 

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6518]
### Task description

Delete profile in settings isnt working
- [ ] Fix
- [ ] Enable feature flag

### Requirements

Fixed delete profile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Duplicated 🙏🏼 https://github.com/iotaledger/firefly/issues/6428
