### ISSUE TITLE
[Task]: App crash after clicking on unknown activity

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6522]
### Task description

The app crashes if we click on an Unknown activity 

### Requirements

- [x] Investigate and fix bug

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
