### ISSUE TITLE
[Task]: Update mobile capacitor iota-sdk to include voting power fixes

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6525]
### Task description

Voting power was added to balance my the iota-sdk team https://github.com/iotaledger/iota-sdk/pull/231 and firefly core libraries are already updated to welcome those changes. We are just missing an update on the mobile files

### Requirements

- [ ] Compiles files updated with latest changes
- [ ] Files uploaded to s3
- [ ] Logic working

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
On Android is done. Working on the iOS side.
