### ISSUE TITLE
[Task]: Remove redundant layer in network health

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6556]
### Task description

The NetworkHealth enum contains values 0-3. Everywhere where we use this enum we need to convert it into strings with the `NETWORK_STATUS_MAP`.

We can instantly use those values inside the enum

### Requirements

- [ ] Use string values in NetworkHealth enum

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
