### ISSUE TITLE
[Task]: If user selects glow in SendForm, it should also use glow in SendConfirmation

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6564]
### Task description

We already fixed that issue once but  it seems to be back.

The SendConfirmation should use the same unit as the user selected in the `SendForm`

### Requirements

- [ ] Fix bug

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
