### ISSUE TITLE
[Task]: Shimmer asset should not be verifiable or hidable

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6566]
### Task description

When going to the AssetInformation of Shimmer, the Verify and Hide button are enabled. But for this asset, these should be hidden, as it is per definition verified and cannot be hidden

### Requirements

- [ ] Remove Verify and Hide button on Shimmer asset info

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
This should be fixed by https://github.com/iotaledger/firefly/pull/6382
