### ISSUE TITLE
[Task]: Storage deposit isnt calculated on SendConfirmation

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6567]
### Task description

If the user tries to send 1glow, the SendConfirmation doesnt immediatly calculte the storage deposit as well as the expiration time isnt set correctly (this may be related to the storage deposit, because we set an expiration time if we have storage deposit)

### Requirements

- [ ] Calculate storage deposit if required on SendConfirmation

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Duplicated in https://github.com/iotaledger/firefly/issues/6572
