### ISSUE TITLE
[Task]: Fix width for activities

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#6568]
### Task description

If the name of an NFT is very long, the width of the activities is broken, see attachments.
Besides that, the activities and the assets have different widths.

![image](https://user-images.githubusercontent.com/105642810/232712380-8ef871ba-a31e-440f-b768-d758e492a08e.png)

### Requirements

- [ ] Fix activity tile width for long contents
- [ ] Unify width for activity and asset tiles

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
