### ISSUE TITLE
[Task]: Remove default `button` on click style

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6569]
### Task description

On mobile, buttons get a default on click color. We should remove that.

 
![image](https://user-images.githubusercontent.com/105642810/232715791-6e348660-a8b4-46c6-bb08-2dd092e7bfb8.png)

### Requirements

- [ ] Remove default `button` on click style

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
