### ISSUE TITLE
[Task]: refactor mobile feature flags

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6570]
### Task description

Desktop has cleaned up and organized its feature flags by splitting the features into contexts and adding interfaces.
Mobile would benefit from this cleanup, see desktop here https://github.com/iotaledger/firefly/tree/develop/packages/desktop/features

### Requirements

- [ ] Split mobile feature flags in contexts
- [ ] Cleanup unnecessary flags and add missing ones (if so)
- [ ] Add and use custom interfaces

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
