### ISSUE TITLE
[Task]: Fix webpack HMR refreshing on error

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6575]
### Task description

On devmode, seems like the recent changes on the HMR are causing the app to refresh on:
- [ ] Logout
- [ ] Onboarding custom network form submit
- [ ] ... might be in more places, havent experienced it though

### Requirements

Fix HMR so it does not refresh the app when it should not

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Seems to be related to unhandled app crashes, instead of throwing an error (which shows up in MacOS), in Linux it reloads

**Comment by MarkNerdi** [comment]
by removing different steps during logout, the place where the hmr occurs is `destroyProfileManager`

**Comment by MarkNerdi** [comment]
The issue lies in `initializeRegisteredProposals`. We make a call to walletrs for every account, which then fetches the participation status for each of them. 
With a lot of accounts, this can take some seconds/minutes, and if we logout during that time, the app crashes
