### ISSUE TITLE
[Task]: Create generic platform methods for overlay UI

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6577]
### Task description

We need a platform method so that we can use `openUrlInBrowser` for mobile.

:warning: This is a temporary fix - the proper fix will come when we can make the shared library package platform-agnostic.

### Requirements

- [x] Add / implement `openOverlayUi` to platform
- [x] Add / implement `closeOverlayUi` method to platform
- [x] Use `Platform.openOveralyUi` in `openUrlInBrowser`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
