### ISSUE TITLE
[Task]: Create `AddEvmChainForm` component

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6581]
### Task description

We need to be able to add EVM-based chains (rather than just ISCP-based ones).

### Requirements

- [ ] Add `AddEvmChainForm` component to `AddChainDrawer` (no validation logic)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked by https://github.com/iotaledger/firefly/issues/6582
