### ISSUE TITLE
[Task]: Prevent date picker drawer to be confirmed without selecting date

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6583]
### Task description

When the date picker drawer has not any dates selected it sets it to 31/12/1969 and it should not set any date

### Requirements

- [ ] Cannot confirm date picker drawer without selecting date

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
