### ISSUE TITLE
[Task]: UI/UX polish for L2 network support

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6585]
### Task description

Small details that need polishing

### Requirements

```[tasklist]
- [x] #6381
- [ ] #6533
- [ ] #6788
- [ ] #6789
- [ ] #6790
- [ ] #6791
- [ ] #6792
- [ ] #6793
- [x] #6794
- [ ] https://github.com/iotaledger/firefly/issues/6819
- [ ] https://github.com/iotaledger/firefly/issues/6858
```

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
