### ISSUE TITLE
[Task]: Fix currency undefined

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6586]
### Task description

The settings active profile currency prop has changed causing the diagnostics info to be undefined

### Requirements

- [ ] Currency shows correctly in diagnostics

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
