### ISSUE TITLE
[Task]: Remove `networkProtocol` & `networkType` from persisted profile

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6596]
### Task description

TBD

### Requirements

- [ ] Remove `networkProtocol` & `networkType` from persisted profile
- [ ] Add migration

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
