### ISSUE TITLE
[Task]: Move client options to persisted network

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6597]
### Task description

To help prepare for the future, we should move the client options to be per-profile. 

### Requirements

- [ ] Move client options onto the `IPersistedNetwork`
- [ ] Adjust onboarding code as needed
- [ ] Adjust network settings as needed
- [ ] Add profile migration logic

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
