### ISSUE TITLE
[Task]: Add `EvmChainInformation` component

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6599]
### Task description

This is the second "view" within the `ChainInformationDrawer` that'll be specifically for EVM chains

:no_entry_sign: Blocked until `ChainInformationDrawer` component exists.

### Requirements

- [ ] Add `EvmChainInformation` component

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked by https://github.com/iotaledger/firefly/issues/6582
