### ISSUE TITLE
[Task]: Add address generation flow for Ledger profiles

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6600]
### Task description

With the Ethereum app library integrated and the components responding reactively to the device confirming a generated address, we need to add the actual components needed for the flow.

### Requirements

- [x] Use "Generate address" button in connect chains view
- [x] Add Address Confirmation side drawer
- [x] Add Connect Ledger side drawer with connection logic

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
