### ISSUE TITLE
[Task]: Make balance breakdown scrollable

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6604]
### Task description

When balance breakdown items are expanded it makes the "Minimize storage deposit" button not visible, so it should be scrollable for the user to reach the button visibility

### Requirements

- [ ] Balance breakdown is scrollable when too large vertically

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
