### ISSUE TITLE
[Task]: Fix wallet deletion

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6605]
### Task description

- Two notifications “Unable to remove wallet” are thrown after deleting the wallet
- The delete drawer is not closed after the wallet is deleted
- If I keep the drawer open and try to delete again it deletes the last wallet in the list and I can delete all wallets of a profile, making the profile corrupted

### Requirements

- [ ] Only one "Deleted successfully" notification
- [x] Delete wallet drawer is closed after the wallet is deleted
- [ ] The deleted wallet or wallet to be deleted corresponds to the wallet name in the title of the delete wallet drawer
- [x] I cannot delete all wallets of a profile
- [ ] Delete wallet function contains all the logic for checking if the wallet can be deleted, the UI is not responsible for that

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
