### ISSUE TITLE
[Task]: Add profile migration for network type & network protocol refactor

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6619]
### Task description

TBD

### Requirements

- [ ] Add necessary migration
- [ ] Remove all remaining types

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
