### ISSUE TITLE
[Task]: Update mobile splash assets to latest shimmer

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6625]
### Task description

We have a new icon set for alpha, beta & production https://github.com/iotaledger/firefly/tree/develop/packages/desktop/public/assets/icons

### Requirements

- [ ] Working assets in splash screen

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
