### ISSUE TITLE
[Task]: Add feature flag for adding a L2 chain

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6646]
### Task description

At least initially, this will be a developer feature so it should be hidden behind a feature flag so we can disable it for prod releases.

### Requirements

- [x] Add feature flag for adding a chain

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
