### ISSUE TITLE
[Task]: Replace `eslint-plugin-svelte3` for `eslint-plugin-svelte`

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6653]
### Task description

[`eslint-plugin-svelte3`](https://github.com/sveltejs/eslint-plugin-svelte3) has been deprecated so it should be replaced by [`eslint-plugin-svelte`](https://github.com/sveltejs/eslint-plugin-svelte)

### Requirements

- [ ] Deprecated packages are uninstalled
- [ ] New packages are installed
- [ ] `.eslintrc` is using the new plugin

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
