### ISSUE TITLE
[Task]: Implement logic for chain status

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6698]
### Task description

Need to write the logic to query for chain status.

### Requirements

- [ ] Write initial logic to query for block
- [ ] Write polling logic (?)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
