### ISSUE TITLE
[Task]: Tiny library refactors for L2 network support

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6711]
### Task description

There are some small fixes we need to make.

### Requirements

- [x] [Task]: Change selected-chain-index.store.ts to selected-chain.store.ts
- [x] [Task]: Remove void this.getStatus() call in the IscpChain constructor
- [x] [Task]: Add optional chaining in the IscpNetwork constructor if  chainConfigurations is undefined

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
