### ISSUE TITLE
[Task]: Improve Token Amount Input

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#6769]
### Task description

The `TokenAmountInput` in the `InputTokenAmountView` needs some improvements for better UX

### Requirements

- [x] If amount contains a lot of digits, it goes off screen. Maybe we should reduce the fontsize if it hits a certain length
- [x] If a decimal point is the first thing inputted, a 0 should be added before the decimal point
- [x] Maybe its possible to block inputting a number which would be bigger than available balance

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
