### ISSUE TITLE
[Task]: Remove duplicate function hex2rgb

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#6770]
### Task description

hex2rgb in `packages/shared/core/utils/ui.ts` is similar to `convertHexToRgba` in `packages/shared/core/utils/convert.ts`. Remove one and refactor the code to use the remaining one instead.

### Requirements

- [ ] remove duplicate function
- [ ] refactor code to use remaining one in place

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
