### ISSUE TITLE
[Task]: Create header safe area for iOS

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#6779]
### Task description

Error messages on iOS appear across the top of the screen behind the notch. Create a safe area at the top of iOS that respects the notch.

<img src="https://github.com/iotaledger/firefly/assets/72045705/221d91fa-b177-4165-8678-858bb97d11a4" width="50%" height="50%" />

### Requirements

- [ ] Create safe area header for iOS

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
