### ISSUE TITLE
[Task]: Wrap error messages on mobile

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#6781]
### Task description

Error messages on mobile do not respect the width of the screen.

<img src="https://github.com/iotaledger/firefly/assets/72045705/b289a64b-eb6d-4b30-a635-e8cea0c9cc41" width="50%" height="50%" />

### Requirements

- [ ] Wrap error messages so that the whole messages is viewable

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
