### ISSUE TITLE
[Task]: Create footer safe area for iOS

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#6782]
### Task description

The tab navigator options clip in iPhone, change the safe area of the footer to fix this issue.

<img src="https://user-images.githubusercontent.com/72045705/234388301-ce45683b-a560-48a7-8047-b1f062f0596b.png" width="50%" height="50%">

### Requirements

- [ ] Tab navigator icons no longer clipping with iPhone footer

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
