### ISSUE TITLE
[Task]: Prepare for 6th ASMB staking period (desktop)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6783]
### Task description

Need to prepare for the next staking event.

### Requirements

- [x] Update CI so building works
- [x] Update the following constants:
    - [x] `ASSEMBLY_EVENT_START_DATE`
    - [x] `ASSEMBLY_EVENT_ID`
    - [x] `ASSEMBLY_STAKING_BLOG_POST_URL`
    - [x] `ASSEMBLY_STAKING_RESULT_FILES`
    - [x] `LAST_ASSEMBLY_STAKING_PERIOD`
    - [x] `CURRENT_ASSEMBLY_STAKING_PERIOD`
- [x] Add 5th period staking results JSON file to `assets/staking-results`
- [ ] ~~Add 5th period staking results JSON file to S3 backup~~

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
