### ISSUE TITLE
[Task]: Add new property to NetworkHealth enum

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#6784]
### Task description

https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/core/network/helpers/getNetworkStatusFromNodeInfo.ts#L26

According to iota-sdk slack, `nodeInfo.status.latestMilestone.timestamp` can be null during "Node Startup, and no milestone received yet". We do not have a property on NetworkHealth to represent this state. Create a property to represent this state and add new colors, icons and translations for this status.

### Requirements

- [ ] add additional property to NetworkHealth
- [ ] change returned NetworkHealth in `getNetworkStatusFromNodeInfo.ts` if timestamp is null
- [ ] update NETWORK_HEALTH_COLORS
- [ ] update NetworkStatusPill

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
