### ISSUE TITLE
[Task]: Prepare for 6th ASMB staking period (mobile)

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6787]
### Task description

Need to prepare for the next staking event.

### Requirements

- [ ] Update CI so building works (if necessary)
- [ ] Update the following constants:
    - [ ] `ASSEMBLY_EVENT_START_DATE`
    - [ ] `ASSEMBLY_EVENT_ID`
    - [ ] `ASSEMBLY_STAKING_BLOG_POST_URL`
    - [ ] `ASSEMBLY_STAKING_RESULT_FILES`
    - [ ] `LAST_ASSEMBLY_STAKING_PERIOD`
    - [ ] `CURRENT_ASSEMBLY_STAKING_PERIOD`
- [ ] Add 5th period staking results JSON file to `assets/staking-results`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
