### ISSUE TITLE
[Task]: Merge release/mobile-2.0.0-alpha-1 into develop

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#6795]
### Task description

Merge `release/mobile-2.0.0-alpha-1` into `develop` so we can test mobile and desktop at the same time and ensure we are up to date with dependencies, improvements, etc in the `develop` branch. This is currently blocked by desktop logic in shared. Resolving issue #5138 and #6275 should unblock this issue.

### Requirements

- [ ] Merge `release/mobile-2.0.0-alpha-1` into `develop`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
