### ISSUE TITLE
[Task]: Add `copyFile` and `deleteFile` Platform methods

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6796]
### Task description

We need the Platform `copyFile` and `deleteFile` methods for the onboarding stronghold migration flow logic, and this requires adding the method in capacitorApi and the filesystem plugin

### Requirements

- [ ] `copyFile` and `deleteFile` methods in the Platform object are working on iOS and Android

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
