### ISSUE TITLE
[Task]: Handle Ledger device error states

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6799]
### Task description

When performing some Ledger operation (for the EVM), the main process should tell the renderer process when an error has occurred (e.g. device is disconnected, wrong app open, etc.).

Because `wallet.rs` is already keeping track of the `LedgerNanoStatus`, we will already have all of the information we need to handle the UX side of things. 

### Requirements

- [x] Handle following scenarios:
    - [x] Disconnected
    - [x] Locked
    - [x] Wrong app / no app
- [x] Log in main process if nothing else

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
