### ISSUE TITLE
[Task]: Add `gift storagedeposit` input to `SendFlow`

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6800]
### Task description

To be able to gift the storage deposit to the recipient, we need the toggle button to specify this. 

### Requirements

- [ ] Implement button on storage deposit to display GiftStorageDeposit toggle
- [ ] Implement logic to gift storage deposit 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
