### ISSUE TITLE
[Task]: Correctly display `surplus` in new `SendFlow`

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6807]
### Task description

In the new SendFlow popup, surplus will be shown as another `TokenAmountTile`. 

The scope of this task should be to add the TokenAmountTile if surplus exists. But currently we can only add surplus through deeplinks (which are not supported rn with the new sendflow), so you have to mock surplus for now

### Requirements

- [ ] Add `TokenAmountTile` for surplus

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
