### ISSUE TITLE
[Task]: Skip `SelectToken` if `SendFlow` is accessed through `TokenInformation`

### ISSUE THREAD

**Issue by MarkNerdi** [iotaledger/firefly#6808]
### Task description

If the Send button on the `TokenInformation` is clicked, the `TokenSelection` should be skipped and the previous token should be selected.

### Requirements

- [ ] Skip `SelectToken`
- [ ] Previous token should be used for the rest of the sendflow

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
