### ISSUE TITLE
[Task]: Add support for caching ERC20 tokens

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6817]
### Task description

We'll need to have this data so we can display various information about it to the user.

### Requirements

- [ ] Change persisted asset data to handle layer 2 tokens
- [ ] Change `IPersistedAsset` to `IPersistedToken`
- [ ] Write migration function if necessary
- [ ] Remove IRC27 standard from `TokenStandard`

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
