### ISSUE TITLE
[Task]: Use wallet evm address to fetch l2 native tokens

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6832]
### Task description

In PR https://github.com/iotaledger/firefly/pull/6801 we use a static EVM address to get the native tokens
We should fetch the l2 native tokens using the EVM address provided with the ledger ethereum app

### Requirements

- [ ] Use evm address generated by the ledger ethereum app
- [ ] Add assets to account (per chain)

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
