### ISSUE TITLE
[Task]: Rename AccountMetadata to AccountPersistedData

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6875]
### Task description

- [ ] Rename AccountMetadata to AccountPersistedData
- [ ] Add needed migration

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
