### ISSUE TITLE
[Task]: Fix Ledger device and profile mismatch

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6898]
### Task description

It is possible to use a different Ledger device with a profile that wasn't created with that same device... so we need a way to check that the profile is being used with the correct Ledger device.

Notes:
- We need to detect a mismatched device / mnemonic before we can know the connection status, since we can only know if there is a device mismatch if the user has the correct app open. 
- Generating an address and checking against persisted data will work, but requires user to have the Shimmer or Ethereum app open.

### Requirements

- [x] Should work for different devices
- [x] Should work with [extra-word passphrases](https://www.ledger.com/academy/passphrase-an-advanced-security-feature)

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
