### ISSUE TITLE
[Task]: Improve readability of node info metrics value

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6899]
### Task description

The confirmation rate in the metrics of the node can be limited to 1 decimal. And it would be good to include a "%"

![image](https://github.com/iotaledger/firefly/assets/42754063/6e25c2f5-195d-4d2a-93cd-916cb81d4f8b)

The suggestion came from #4516 

### Requirements

- [ ] Metrics are more readable

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
