### ISSUE TITLE
[Task]: Add Nano S Plus to locale

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#6900]
### Task description

As reported in https://github.com/iotaledger/firefly/issues/4516, Nano S Plus is missing in the locale for creating new ledger profiles 
![image](https://github.com/iotaledger/firefly/assets/105642810/a6feff10-1f51-494a-a295-889a91eea887)

### Requirements

- [ ] Add Nano S Plus to en locale

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
