### ISSUE TITLE
[Task]: Change "IOTA app" string in ledger tips for connecting

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6901]
### Task description

The string should be "Open the Shimmer app on your Ledger device"

![image](https://github.com/iotaledger/firefly/assets/42754063/3d4775bd-47e0-4d50-a499-eb9fb5e34fe1)

### Requirements

- [ ] Shimmer string in ledger tips

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
