### ISSUE TITLE
[Task]: Update guide to install Ledger app catalog picture

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6902]
### Task description

The guide to install the ledger apps doesn´t fit for Shimmer. IOTA and IOTA Legacy apps are shown in the popup.

![image](https://github.com/iotaledger/firefly/assets/42754063/beeddd7f-b488-4af5-b7f9-1b6027d7fd2e)

### Requirements

- [ ] The picture in Ledger guide shows the Shimmer app

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
