### ISSUE TITLE
[Task]: Support for L2 activities

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6909]
### Task description

We are missing L2 activities for the following actions:

Blocked by UI work.

- [ ] Send token on L2
- [ ] Withdraw token from L1.5
- [ ] Unwrap token from L2 -> L1
- [ ] Smart Contract Interaction

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
