### ISSUE TITLE
[Task]: Update wallet-rs to fix stronghold coin type mismatch bug 

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7007]
### Task description

There is a new `@iota/wallet` release that includes the fix of https://github.com/iotaledger/iota-sdk/issues/503, among others.
We need to test that everything works and the bug has been fixed

### Requirements

- [ ] Update to latest `@iota/wallet` rc
- [ ] Test thoroughly

Tests
 - [ ] Create new profile which uses latest stronghold version
 - [ ] Create a profile using the old version of stronghold and then try to login with the new stronghold update. There should be migration
 - [ ] Import profile using a new version of stronghold
 - [ ] Import profile using an old version of stronghold
 - [ ] Claim shimmer rewards using an IOTA Firefly stronghold
 - [ ] Normal flows to assure nothing broke: import from mnemonic, create accounts, send, dev tools eg mint etc...

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
