### ISSUE TITLE
[Task Tracker]: Cleanup `develop` branch

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7014]
### Task description

The current develop contains EVM support, we should clean that as much as we can
We are not interested in issues that are in https://github.com/iotaledger/firefly/milestone/70 and https://github.com/iotaledger/firefly/milestone/71
The branch should be stable and work as usual

### Requirements

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/7017
- [ ] https://github.com/iotaledger/firefly/issues/7019
- [ ] https://github.com/iotaledger/firefly/issues/7025
- [ ] https://github.com/iotaledger/firefly/issues/7023
- [ ] https://github.com/iotaledger/firefly/issues/7027
- [ ] https://github.com/iotaledger/firefly/issues/7021
- [ ] https://github.com/iotaledger/firefly/issues/7028
- [ ] https://github.com/iotaledger/firefly/issues/7030
- [ ] https://github.com/iotaledger/firefly/issues/7032
```

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
