### ISSUE TITLE
[Task]: Move documentation from notion to handbook

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7040]
### Task description

- [ ] SOPs
- [ ] Coding conventions
- [ ] Epics
- [ ] Milestones

### Requirements

Aboce mentioned

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
