### ISSUE TITLE
[Task]: Calculate gas estimation for l1->l2 txs using wasp api 

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7058]
### Task description

We currently use web3 to estimate the gas for l1->l2 transactions.
After removing web3 from the code, we could start using the wasp api to estimate the gas

Depends on https://github.com/iotaledger/firefly/issues/7032

### Requirements

- [ ] Use wasp api endpoint to estimate gas

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
