### ISSUE TITLE
[Task Tracker]: Cleanup Components

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7062]
### Task description

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/7070
- [ ] https://github.com/iotaledger/firefly/issues/7075
- [ ] https://github.com/iotaledger/firefly/issues/7078
- [ ] https://github.com/iotaledger/firefly/issues/7080
- [ ] https://github.com/iotaledger/firefly/issues/7082
- [ ] https://github.com/iotaledger/firefly/issues/7084
- [ ] https://github.com/iotaledger/firefly/issues/7086
- [ ] https://github.com/iotaledger/firefly/issues/7090
- [ ] https://github.com/iotaledger/firefly/issues/7091
- [ ] https://github.com/iotaledger/firefly/issues/7094
- [ ] https://github.com/iotaledger/firefly/issues/7099
- [ ] https://github.com/iotaledger/firefly/issues/7102
- [ ] https://github.com/iotaledger/firefly/issues/7115
- [ ] https://github.com/iotaledger/firefly/issues/7131
- [ ] https://github.com/iotaledger/firefly/issues/7133
- [ ] https://github.com/iotaledger/firefly/issues/7138
- [ ] https://github.com/iotaledger/firefly/issues/7146
- [ ] https://github.com/iotaledger/firefly/issues/7149
- [ ] https://github.com/iotaledger/firefly/issues/7157
- [ ] https://github.com/iotaledger/firefly/issues/7159
- [ ] https://github.com/iotaledger/firefly/issues/7162
- [ ] https://github.com/iotaledger/firefly/issues/7164
- [ ] https://github.com/iotaledger/firefly/issues/7167
- [ ] https://github.com/iotaledger/firefly/issues/7169
- [ ] https://github.com/iotaledger/firefly/issues/7172
- [ ] https://github.com/iotaledger/firefly/issues/7176
- [ ] https://github.com/iotaledger/firefly/issues/7180
- [ ] https://github.com/iotaledger/firefly/issues/7182
- [ ] https://github.com/iotaledger/firefly/issues/7185
- [ ] https://github.com/iotaledger/firefly/issues/7187
- [ ] https://github.com/iotaledger/firefly/issues/7189
- [ ] https://github.com/iotaledger/firefly/issues/7192
- [ ] https://github.com/iotaledger/firefly/issues/7195
- [ ] https://github.com/iotaledger/firefly/issues/7197
- [ ] https://github.com/iotaledger/firefly/issues/7199
- [ ] https://github.com/iotaledger/firefly/issues/7201
- [ ] https://github.com/iotaledger/firefly/issues/7210
- [ ] https://github.com/iotaledger/firefly/issues/7212
- [ ] https://github.com/iotaledger/firefly/issues/7214
- [ ] https://github.com/iotaledger/firefly/issues/7217
- [ ] https://github.com/iotaledger/firefly/issues/7219
- [ ] https://github.com/iotaledger/firefly/issues/7225
- [ ] https://github.com/iotaledger/firefly/issues/7227
- [ ] https://github.com/iotaledger/firefly/issues/7229
- [ ] https://github.com/iotaledger/firefly/issues/7232
- [ ] https://github.com/iotaledger/firefly/issues/7234
- [ ] https://github.com/iotaledger/firefly/issues/7236
- [ ] https://github.com/iotaledger/firefly/issues/7238
- [ ] https://github.com/iotaledger/firefly/issues/7239
- [ ] https://github.com/iotaledger/firefly/issues/7241
- [ ] https://github.com/iotaledger/firefly/issues/7245
- [ ] https://github.com/iotaledger/firefly/issues/7249
- [ ] https://github.com/iotaledger/firefly/issues/7262
- [ ] https://github.com/iotaledger/firefly/issues/7264
- [ ] https://github.com/iotaledger/firefly/issues/7266
- [ ] https://github.com/iotaledger/firefly/issues/7268
```

### Requirements

- [x] Move auxiliary popup lib back to shared
- [ ] Cleanup unused components
- [ ] Move desktop components to shared folder
- [ ] Remove unitary button components
- [ ] Remove atoms/molecules/organisms system
- [ ] Organize all in categories
- [ ] Apply coding conventions [source](https://iotaledger.github.io/firefly/guides/coding-conventions/components/)
- [ ] Apply tailwind 3 fantasies
- [ ] Remove warnings

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
