### ISSUE TITLE
[Task]: Update ShimmerEVM Testnet Chain ID & serialization

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7063]
### Task description

https://discord.com/channels/397872799483428865/800810467928309790/1124005011148513392

```
EVM info:
Chain ID: 1072 (changed from 1071)
```

### Requirements

- [ ] Add new chain ID
- [ ] Check for possible needed migrations so devnet profiles can still use L1->L2 transactions

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
