### ISSUE TITLE
[Task]: Remove `mobile` folder

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7349]
### Task description

- [ ] Remove mobile folder
- [ ] Cleaup dependencies & yarn.lock

### Requirements

ABove mentioned

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
