### ISSUE TITLE
[Task]: Remove mobile debris

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7350]
### Task description

- [ ] mobile relates stores
- [ ] mobile related logic
- [ ] ....

### Requirements

Above mentioned

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
