### ISSUE TITLE
[Task]: Fix available balance reactivity in SendFormPopup

### ISSUE THREAD

**Issue by brancoder** [iotaledger/firefly#7427]
### Task description

If user initiates new send flow and opens SendFormPopup while there is a pending transaction in progress, when that transaction gets confirmed the available balance is not updated in the popup. User can than input the value that is greater than the new available balance, because the old available balance is still displayed and used in validation, and proceed to SendConfirmationPopup where an error notification will be thrown.

Make available balance reactive in `SendFormPopup` so it reflects the correct state of the balance.
![image](https://github.com/iotaledger/firefly/assets/52735957/2b3ebae2-4105-455e-ac55-fa0747597d2a)

### Requirements

in `SendFormPopup`
- [ ] display correct value of available balance
- [ ] user cannot input and pass validation with incorrect amount 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@brancoder blocked by the refactor, once thats done we can get into improving this
