### ISSUE TITLE
[Task]: Add ShimmerEVM chain to Shimmer profiles

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7436]
### Task description

The shimmer evm will be soon released, so we should be ready. There are 3 things we should do in order to achieve this task
- [ ] Add the ShimmerEVM details (blocked until release)
- [ ] Update encoding (new encoding only for shimmer evm, not for shimmer evm testnet)
- [ ] Add profile migration to include the new chain in existing shimmer profiles
- [ ] Add final ShimmerEVM details when ready (blocked by release date

#### Details about the new encoding:

ShimmerEVM (production) encoding change: 
basically we changed the way we identify "sender contracts" on  L1 requests
how does firefly encode this right now?
I'm guessing at this time is a uint32 (4 bytes) as 0s, right?
now just 1 byte (as 0) is needed, that's it
- a single 0 byte (means  no contract)
- a single byte with value 1, followed by 4 bytes (hname) - (this is the same as it was before, just with the "kind" byte added as a prefix)
- a single byte with value 2, followed by 20 bytes (EVM address)

### Requirements

Add ShimmerEVM network option to all new and existing Shimmer profiles

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
