### ISSUE TITLE
[Task]: Replace output serialization for gas estimation with util iota-sdk 

### ISSUE THREAD

**Issue by msarcev** [iotaledger/firefly#7463]
### Task description

- [ ] Replace output serialization for gas estimation with util iota-sdk. It is currently done with partial code from iota.js
- [ ] Cleanup the iotajs copied code

### Requirements

Depends on https://github.com/iotaledger/firefly/issues/7462

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
