### ISSUE TITLE
[Task Tracker]: Add "View address history" to IOTA app

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7480]
### Task description

Users should be able to see their address history so they can go to the explorer to check their vesting schedule too, knowing all their addresses

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/7593
- [ ] https://github.com/iotaledger/firefly/issues/7594
- [ ] https://github.com/iotaledger/firefly/issues/7597
```

### Requirements

Similar to what we have in the chrysalis app, add "view address history" 
![image](https://github.com/iotaledger/firefly-private/assets/3624944/74cb6612-4c46-4fa8-b1ee-64918a3e33b3)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
