### ISSUE TITLE
[Task]: Update deeplinks documentation

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7751]
### Task description

- [x] IOTA metric system is not allowed anymore, default SMR unit is glow, and default IOTA unit is micro
- [x] `If you wish to target the production version, simply omit this from the prefix` this doesnt make sense, you should just skip the stage for a production version
- [x] Remove `This deep link scheme is NOT compatible with Firefly V1, as` ....
- [x] Update send confirmation screenshot 
- [x] Explain that we have 2 deeplink schemes, `iota` for Firefly IOTA and `firefly` for Firefly Shimmer 
- [x] Review send confirmation & send form screenshots (use IOTA)
- [x] Review send confirmation & send form params to make sure they are accurate
