### ISSUE TITLE
[Task Tracker]: Update dev tools to network upgrade

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7865]
### Task description

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/firefly/issues/7866
- [ ] https://github.com/iotaledger/firefly/issues/7867
- [ ] https://github.com/iotaledger/firefly/issues/7920
```
