### ISSUE TITLE
[Task]: General Polish

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#8110]
### Task description

Test the whole app and list here quick polishes we need to do to have a smooth app
- [x] Delegation view: 
    - [ ] https://github.com/iotaledger/firefly/issues/8233
    - [x] https://github.com/iotaledger/firefly/issues/8148
    - [x] https://github.com/iotaledger/firefly/issues/8172
    - [x] https://github.com/iotaledger/firefly/issues/8112
    - [x] https://github.com/iotaledger/firefly/issues/8167
 - [x] Account management view:  
    - [ ] https://github.com/iotaledger/firefly/issues/8234
     - [x] https://github.com/iotaledger/firefly/issues/8147
     - [x] https://github.com/iotaledger/firefly/issues/8146
     - [x] https://github.com/iotaledger/firefly/issues/8145
     - [x] https://github.com/iotaledger/firefly/issues/8149
 - [x] https://github.com/iotaledger/firefly/issues/8165
 - [x] Implicit creation view:
      - [x] https://github.com/iotaledger/firefly/issues/8197
      - [x] https://github.com/iotaledger/firefly/issues/8198
 - [x] https://github.com/iotaledger/firefly/issues/8199
